### ISSUE TITLE
Missing `name` field on `File` type when using `javascript/object` or `javascript/umd`.

### ISSUE THREAD

**Issue by ConcernedHobbit** [amzn/style-dictionary#1004]
`file.name` is not specified in [`File.d.ts`](https://github.com/amzn/style-dictionary/blob/2cf72f3f89996503608c238d7f3bcbab5b53e719/types/File.d.ts) even though it is used in `javascript/object` and `javascript/umd` formats. This causes type errors when trying to use this functionality.

What's the suggested typing to use? The context is a `Platform` configuration in a `StyleDictionary.Config`.

https://github.com/amzn/style-dictionary/blob/2cf72f3f89996503608c238d7f3bcbab5b53e719/lib/common/formats.js#L289

**Comment by jorenbroekema** [comment]
Fixed in v4 branch
