### ISSUE TITLE
Externalize current transforms, formats, etc.

### ISSUE THREAD

**Issue by elliotdickison** [amzn/style-dictionary#102]
What would you all think about moving the current transforms, formats, etc. (basically everything in the `common` directory) into separate packages that could then be imported as-needed by the user. I'm thinking of something similar to babel v7's scoped plugin setup. For example some packages might be `@style-dictionary/transform-attribute-cti`, `@style-dictionary/format-javascript-es6`, etc.

The benefits of this would be:
* Maintainability - if certain transforms need to pull in new dependencies they won't pollute the main package's package.json and require everyone to download those dependencies, updating individual transforms etc. would not require publishing a new version of the core module, updating specific transforms etc. would only affect the users depending on those particular packages
* Learning curve - users would have to use the register APIs for everything... teaching them how to use those APIs with pre-made transforms (which is pretty simple) might be a good way to ease them into extending style-dictionary with custom behavior
* Ecosystem - this might encourage users to share/publish their own transforms without feeling the need to add their custom behavior to the central style-dictionary repo... any of the officially published transforms would serve as a template they could start from
* Separation of concerns - this would nicely separate core functionality from pluggable behavior, and the decision to add very obscure/niche transforms etc. would not feel like such a big deal (e.g. publishing `@style-dictionary/transform-really-obscure-thing` is a lot less obtrusive than adding whatever "really-obscure-thing" and all its dependencies to the core package)

The downsides:
* Maintainability - There would be more packages to manage, versioning could be tricky with breaking changes in the core module that affect plugins
* Common code - if there's a lot of shared code between transforms etc. it gets trickier to ensure that's not copy-pasted a bunch
* Setup effort - a bit more work is required to get started.. users would have to npm install all the things they need and register then with style-dictionary

**Comment by chazzmoney** [comment]
@dbanksdesign would like to hear your thoughts on this one

**Comment by dbanksdesign** [comment]
I think long-term, this would probably be a better architecture. Right now I think the cost of creating and maintaining so many packages would be tough.

**Comment by chazzmoney** [comment]
Lets close this for now and we can reopen when we think this is a route we want to put energy into?

**Comment by rjoaopereira** [comment]
I would like to upvote this.
Suggesting [lerna](https://github.com/lerna/lerna) as a tool for maintenance.
