### ISSUE TITLE
Drop Lodash

### ISSUE THREAD

**Issue by jorenbroekema** [amzn/style-dictionary#1041]
@tahul

Mostly wanna drop this because Lodash is quite a node_modules bloating thing, and usually modern JS can do it already anyway. We don't use that much of lodash anyway, shouldn't be too much work.

**Comment by lb-** [comment]
By the looks of things, it's only used for the template code & examples.

- lib/common/formats.js
- examples/advanced/custom-formats-with-templates/build.js
- examples/advanced/tokens-deprecation/build.js
- scripts/handlebars/templates/formats.hbs
- lib/register/template.js

I assume these need to still be supported, what would be the best approach here?

Maybe the template package to be used standalone https://www.npmjs.com/package/lodash.template (however, I think Lodash still needs to make utils available inside the function like `forEach`).

**Comment by jorenbroekema** [comment]
With regards to template, I think it would be good to just take the templates and turn them into template literals (function that returns template literal if dynamic vars are needed). ES6 has a good method for templating nowadays so then we don't need some third-party templating lib like lodash for it anymore.
