### ISSUE TITLE
Using require on style dictionary files doesn't play nicely with a watcher

### ISSUE THREAD

**Issue by dbanksdesign** [amzn/style-dictionary#106]
I have a demo where I set up a watcher (node-watch) to watch all my style dictionary JSON files and when it detects a change, rebuilds the style dictionary. However, because node builds a cache for any modules that are required, style dictionary will always load the cached version of the file. This makes it appear that the changes never happened, but they did. 

I don't know if this is something we should fix in style dictionary by deleting the cache before requiring style dictionary files, or if there is a workaround we can have some example code for. Just starting the discussion here as I thought I was going crazy for the past hour wondering why my changes weren't getting picked up.

**Comment by dbanksdesign** [comment]
My current workaround is:

```javascript
  watch('./', { recursive: true, filter: /^(properties)/ }, function(evt, name) {
    console.log('Updating the style dictionary');
    // Delete the cache of the file that was updated
    delete require.cache[`${process.cwd()}/${name}`];
    try {
      var sd = StyleDictionary.extend('config.json');
      sd.buildAllPlatforms();
      console.log('\n🎉 Style dictionary finished!');
    } catch (e) {
      console.log(e);
    }
  });
```

**Comment by elliotdickison** [comment]
Woah, good to know. For the record I've been using [chokidar](https://www.npmjs.com/package/chokidar) to watch files and re-run a custom build script and this has not been an issue so far (and I am using `require` to import token modules).

**Comment by dbanksdesign** [comment]
Hmm, maybe it is just a limitation of node-watch then.. I'll try chokidar and see if that helps.

**Comment by chazzmoney** [comment]
I don't use either, but we should revisit this and decide if we have an action to take. Some options:

- Add something to the documentation
- Create an example showing using a watcher
- Both of those
- Something else
- Nothing at all

**Comment by dbanksdesign** [comment]
Option C (both of those)

**Comment by chazzmoney** [comment]
Added those as separate issues and closing this one
