### ISSUE TITLE
Make the header text returned by fileHeader() optional

### ISSUE THREAD

**Issue by didoo** [amzn/style-dictionary#107]
When I process the design tokens, even if the actual values didn't change, the generated file contains a different header, like in this case:

<img width="453" alt="screenshot_1636" src="https://user-images.githubusercontent.com/686239/43195769-ed72ba54-8ffd-11e8-95ef-edfb7073e3f5.png">

What do you think of having this header optional? As far as I can see in the [formats.js](https://github.com/amzn/style-dictionary/blob/f385fc00540de7297b282b0851e45195d1b02eb2/lib/common/formats.js) file we have access to the config parameter.

Collecting feedbacks before actually attempting to submit a PR :)

**Comment by dbanksdesign** [comment]
Makes sense to me. I have no objections. My suggestion would be to have it configurable but make the default on so as to not change the default behavior.

**Comment by chazzmoney** [comment]
I also like making this as an option. It will enable people to more intuitively see style changes in a code repo. Basically, the file only changes when the style changes - simple.

@didoo did you want to give it a shot still?

**Comment by didoo** [comment]
@chazzmoney @dbanksdesign is it still ok if I pick this one? (is required if we want to do snapshot testing, otherwise they would always fail :) ) 
Or instead we could simply remove it at all (less complexity in the codebase) and people that actually need it can rely on custom formats/templates.
wdyt? I don't have strong opinions, slightly prefer removing it, but I'm ok with both options.

**Comment by didoo** [comment]
I have done a spike to understand the impact of this change. You can see the code here:
https://github.com/didoo/style-dictionary/commit/2de87aaad5c5f37495c199b71bd47b050f75ba86
https://github.com/didoo/style-dictionary/commit/ccb9f2165c6a2e81a48c750d7943503063be1319

This is in the hypothesis to use this format for the config:
```
{
  "source": [
    "properties/**/*.json"
  ],
  "platforms": {
    "scss-variables": {
      "transformGroup": "scss",
      "buildPath": "build/scss/",
      "files": [{
        "destination": "_variables.scss",
        "format": "scss/variables"
      }],
      "options": {
        "hideDoNotEdit": true,
        "hideTimestamp": true
      }
    },
    ...
```
with "options" as a new block where we can imagine to store the options for the plarform declaration.

As you see, it's quite dirty if we want to 1) make optional the header/timestamp and 2) make it visible by default for backward compatibility.
Keep in mind that probably we need to have an option to disable the timestamp - or remove it entirely - in order to proceed on #125 (or the snapshot tests will always fail).

Ideas, thoughts, comments?

**Comment by dbanksdesign** [comment]
Pretty awesome so far. What do you think about: 
1. Having the options in the file objects themselves
1. Just having a 'hideHeader' option rather than 'hideDoNotEdit' and 'hideTimestamp'?

```json
{
  "source": [
    "properties/**/*.json"
  ],
  "platforms": {
    "scss-variables": {
      "transformGroup": "scss",
      "buildPath": "build/scss/",
      "files": [{
        "destination": "_variables.scss",
        "format": "scss/variables",
        "options": {
          "hideHeader": true
        }
      }]
    }
```

Using `this.foo` in a template, `this` is bound to the file object today, so actually for your template code to work `hideDoNotEdit` would need to be a key on the file object itself,

```
{
  "destination": "_variables.scss",
  "format": "scss/variables",
  "hideDoNotEdit": true
}
```

I do like having an 'options' object to put stuff like this though, it makes a cleaner separation. In the template/formats you would just need to call `this.options.hideDoNotEdit`

To give some perspective, the reason why I included those generated comments in the formats/templates initially is to signal that they probably shouldn't be committed or edited as they are generated files and to potentially help with debugging (timestamp). 

Sidenote: pretty cool use of `print` to make the template syntax easier to understand!

**Comment by didoo** [comment]
> Having the options in the file objects themselves

I've thought about it, but in that case it leads to a lot of repetition. 
Have a look at this complex `config.js` file, that I use for local development/testing: 
https://github.com/didoo/style-dictionary-local-development/blob/master/config.json
If we attach the "options" to every `file` item, they will be repeated. I'm not against it – personally, I prefer it – but it may be counter-intuitive. 

> Just having a 'hideHeader' option rather than 'hideDoNotEdit' and 'hideTimestamp'?

Had the same idea, but thought that someone may want to be more granular. Totally agree, let's keep it simple :)

> Using this.foo in a template, this is bound to the file object today, so actually for your template code to work hideDoNotEdit would need to be a key on the file object itself,

That's why I had to do this horrible thing:
https://github.com/didoo/style-dictionary/commit/ccb9f2165c6a2e81a48c750d7943503063be1319#diff-c79f21ccce872d9b3635f36aa3d5e9eaL34
which is a code smell that probably we should use the `file` object to contain the _options_ parameters.

Re. the use of `print` in the templates, it took me an incredible amount of time to figure out how to do "templating" in lodash. At the end, the only documentation available is this one: https://lodash.com/docs/4.17.10#template

That said,  I'll create a new branch (in my fork) with the approach you suggest (and that I prefer) so that we can compare the results and take a decision. Stay tuned!

**Comment by didoo** [comment]
I'll wait for @chazzmoney's thoughts. 

In the meantime... yes, I like it, it can be verbose but I think is a small price to pay. In that sense, and more in general, do you think this would be a sensible approach? (see below)

Imagine that you want to apply the "options" to the whole array of files, but for one or two items you want to have different options. As a developer/consumer of the library, I would expect to write something like this (pseudo-code):

```
{
  "source": [
    "properties/**/*.json"
  ],
  "platforms": {
    ...
    "ios": {
      "transformGroup": "xxxxx",
      "buildPath": "build/xxxxx/",
      "prefix": "yyy",
      "options": {
        "showHeader": true
      },
      "files": [{
        "destination": "xxxxx.plist",
        "template": "ios/plist",
        "options": {
          "showHeader": false
        }
      },{
        "destination": "xxxxx.xml",
        "template": "android/xml"
      },{
        "destination": "xxx.json",
        "template": "json"
      },{
        "destination": "xxx.scss",
        "template": "web/scss"
      }]
    }
    ...
  }
}
```

look at how the `showHeader` option is applied globally to the whole "platform" item, but over-written in a specific "file" item. Which leads me also to another more general question: why the props of the "platform" block (e.g. `prefix` and `options` in this case) are not available at "file" object level? I was surprised by that (or probably I am missing something).

**Comment by dbanksdesign** [comment]
That makes sense to me. I think the hard part is what level of abstraction works best and makes the most sense? For instance, what if we did away with 'platforms' altogether and just had a single array of files and the transforms were applied at the file level? Not saying that is the right thing to do, just thinking out loud. These are the types of conversations that would have helped when I was building this 😫! But good to have them now to correct any mistakes or tweak how the API works that makes more sense to people. 

The question I would pose is: completely blank slate, green field, blue sky, is this the API that makes the most sense?

**Comment by chazzmoney** [comment]
So weirdly I thought I had posted something on this a couple days ago...

I was thinking we should consider a cascading options property, similar to what @didoo posted a couple hours ago. Basically there would be defaults, which would be overridden by the options object at the root. At each sub-level, the options property would be checked and if it exists, would be used something like:

`var opts = Object.assign({}, options, currObj.options);`

This would set a precedent for where options could go in general for SD (not just for platforms/files). At each level, they could be overridden.

The only questions that come up for me are:

1. Are options configurable vi the CLI?
2. If so, how do the CLI options prioritize against the cascading options obj?
3. Is it weird that a root level options object and a platforms level options object would have the same effect on platforms?

Sorry that this wasn't posted a couple days ago, not sure what happened.

**Comment by didoo** [comment]
> what if we did away with 'platforms' altogether and just had a single array of files

As a developer approaching the project for the first time, the fact of having the concept of "platforms" helped me **really a lot** in understanding how SD works (internally and as APIs), how things are organised in the repo, and how I should have organised my config.js and build.
Maybe technically is not needed, but resonates a lot with the way we think when we work on this kind of things.

> Are options configurable via the CLI?

Probably not (if we are talking about the less important options like hiding the header or similar). I imagine that if one needs this kind of complexity/customisation, probably works in an environment/company where is not hard to find a person that can set up a build script in Node.

> Is it weird that a root level options object and a platforms level options object would have the same effect on platforms

Maybe a little bit, but we go back to the first point: is it worth it to remove the "platform" layer just for this. Personally, I don't think is worth it.

**Comment by chazzmoney** [comment]
@dbanksdesign Thoughts on cascading options?

**Comment by dbanksdesign** [comment]
Good to hear the platforms concept makes sense, it makes sense to me, but I want to challenge my assumptions. Nothing is set in stone.

For the CLI, I agree it would be a bit weird to have an option like that there. The CLI should be as simple as possible, especially now that you can write JS configs [like this](https://github.com/dbanksdesign/style-dictionary-node)

So the proposal would be:
1. If there is an 'options' object on the file object, take those options
1. If there is no option in the file object, for example hideHeader, look for it on the platform object
1. Else do some default behavior

That makes sense to me.

**Comment by didoo** [comment]
So in conclusion: for this task I'll assume that there is an "option" object attached to the "file" object, and I'll read the `showHeader` property from there. in the future there will be a way to assign these `option` properties at `file` level or at `platform` level, with the cascading described above. for this there will  a new issue, and we'll see who can work on that (potentially I can, only I don't know if it's too much out of my depth, but I can try and ask help if needed :) 

OK then. In the meantime I'll proceed with this one.

**Comment by dbanksdesign** [comment]
Hey Charles and I just chatted on the phone, I have been convinced about having a cascading options object at all 3 levels in the config (root, platform, and file). My suggestion was to make sure the option names are very explicit to what they are doing as it might be confusing to see an option like 'verbose' at the root level, does that mean the files it outputs are verbose or the console output is verbose?

I'm good with just tacking the first level (file) options object for this and handling the cascading stuff in another PR. I'll take a look at your PR later today. Thanks for all your hard work and great discussion on this issue!

**Comment by dbanksdesign** [comment]
Closing this because the code is merged. Thanks @didoo!
