### ISSUE TITLE
Bug: formatter css/variables outputReferenceFallback does not create Fallback value

### ISSUE THREAD

**Issue by tkgroot** [amzn/style-dictionary#1114]
If options  { outputReferences: true, outputReferenceFallbacks: true }, are provided to the css/variables formatter it does not output nor create fallback values for the css variables.

**Comment by tkgroot** [comment]
reference: #1112 #1113

**Comment by jorenbroekema** [comment]
The linked issues are both closed as fixed in v4 so closing this. Let me know if it's still bugged
