### ISSUE TITLE
Properties to generate comments are not consistent between platforms?

### ISSUE THREAD

**Issue by didoo** [amzn/style-dictionary#113]
Can it be that the "comment" attribute is expected in different places for different platforms? In that case, maybe we could or unify it or support both (to avoid breaking someone's setup).

on Web/Scss:
```
if (prop.attributes.comment)
    to_ret_prop = to_ret_prop.concat(' // ' + prop.attributes.comment);
```
https://github.com/amzn/style-dictionary/blob/f385fc00540de7297b282b0851e45195d1b02eb2/lib/common/formats.js#L28-L30

on Android:
```
<% if (prop.comment) { %><!-- <%= prop.comment %> --><% } %>
```
https://github.com/amzn/style-dictionary/blob/c2c31cb381be05d8324838361188879cd8685f3c/lib/common/templates/android/dimens.template#L26

**Comment by dbanksdesign** [comment]
A PR would be great, if you could do it off of the develop branch so we can include it in a release that would be great. This would go out in the next minor release. I think the way forward would be to update the android templates, and if you want bonus points see if there are other formats/templates that either don't do comments correctly or don't do them at all. For example, the 'javascript/es6' format. 

Let me know if you need any help and feel free to submit a PR just to get feedback. Thanks!

**Comment by chazzmoney** [comment]
Hi @didoo, I just merged master back into develop, so they are synched now for development. You should be able to use that to develop off of now - sorry for not keeping it in sync previously.

**Comment by didoo** [comment]
@dbanksdesign @chazzmoney

I want to pick up this task, which one do you think should be the "correct" way to declare a comment?

This one:
```
{
    "prop": {
        "value": "123",
        "comment": "this is a comment"
    }
}
```
so the resolved oject prop is `prop.comment`

or instead this one:
```
{
    "prop": {
        "value": "123",
        "attributes": {
            "comment": "this is a comment"
       }
    }
}
```
so the resolved oject prop is `prop.attributes.comment` ?

**Comment by chazzmoney** [comment]
I'm of the opinion that we should use prop.value and prop.comment. Basically, create a collection of special / reserved words that affect the output of Style Dictionary.

Alternatively, if we are worried about this collection of special / reserved words conflicting with the namespace(s) that people choose, I could see us going with prop.<special object>, where special object could be 'attributes' or '___attributes' and contains the items that SD acts upon.

The latter would be a breaking change requiring a major version bump.

@dbanksdesign , @didoo , @elliotdickison - what do you think?

**Comment by chazzmoney** [comment]
one more consideration - what do other design-token systems do? (i.e. theo)  Probably should do something similar to them to promote compatibility unless we have a specific reason not to.

**Comment by chazzmoney** [comment]
Theo uses a different format for JSON files, but at the attribute level their definitions look like this:

https://github.com/salesforce-ux/theo-example/blob/master/design-tokens/app.json

**Comment by didoo** [comment]
This `I'm of the opinion that we should use prop.value and prop.comment` plus the fact that Theo uses "comment" at the same level as "value" makes me inclined towards the `prop.comment` solution.

**Comment by dbanksdesign** [comment]
I'd lean towards prop.comment, one gripe a lot of people have (myself included) is Style Dictionary can tend to be a bit overly verbose, the less nesting the better probably.
