### ISSUE TITLE
Modifiers are not removed while overriding variables

### ISSUE THREAD

**Issue by niggeulimann** [amzn/style-dictionary#1150]
We have a quite huge multi theme setup - we have values for each customer/theme and semantic vars which uses modifiers:
e.g.

`{
  "test": {
    "value": "#ffffff",
    "type": "color",
    "$extensions": {
      "studio.tokens": {
        "modify": {
          "type": "darken",
          "value": ".25",
          "space": "srgb"
        }
      }
    }
  }
}`

Some of those customers/themes will override these “default-vars” afterwards e.g.:
`"test": {
    "value": "#ff0000",
    "type": "color"
  }`
Unfortunately the modifiers are not removed in this case:
The export-script uses the right color #ff000 in this case, but additionally adds the modifier.

[see issue in Configurator](https://configurator.tokens.studio/#project=hVPBboMwDP0VlFXqVrVlmrRLd9mh2o6b1N2aagok0GyQIMdURRX/voQAAjptPhE/+9l5eVwIiFQaFLDbvpQqRqmVWX8ZsiEyLzRgsMMqE1vZIAyqIAGdB3Pjsivep+dPVLUNl6Cj/ACmTKIhN0Hd9j2j/hbKrAyWXOrQ8BX2RY6Dquvm28kKd7aOLIk+CQDJhd1WK7vvhaqAEhQGKdkE7mSDkhPLSuEylNwkyb0NSpYdiFXRYrHONFDigJqq2vKnmY5YNmT/n97FX/Q9MhNntDo4tQd0DvHKrL1OI8yhueYyqSbp8SjOwLb2s7qCwaLrh8cr2BQsbmEDaeSV8FF3n+1HPRAp1iqR6UQko0vwZPvuvotFuGiqPPFh6SuLjGHzxiNNYzMVpTfJK+iy8GuOnDS4j2UFkchzexk+gqJSZvyd4dGjzTG088JRVSIzYQb7u5joza0RpGLOkp7q88RAssg2rpv9J/q65Rm2ZrDz+upflT5cKz3Do8iF6aTeH1wuF8g4QzZ1qZNmJ/ANuIDRO3hTD4zY/UXtu7hZ9Q8=
)

**Comment by jorenbroekema** [comment]
Offending code is somewhere in here: https://github.com/amzn/style-dictionary/blob/v4/lib/utils/deepExtend.js

When deep extending objects, we don't seem to take into account that merging:

```json
{
  "test": {
    "value": "#ffffff",
    "type": "color",
    "$extensions": {
      "studio.tokens": {
        "modify": {
          "type": "darken",
          "value": ".25",
          "space": "srgb"
        }
      }
    }
  }
}
```
with 

```json
{
  "test": {
    "value": "#ff0000",
    "type": "color",
    "$extensions": {
      "studio.tokens": {
        "modify": {
          "type": "darken",
          "value": ".25",
          "space": "srgb"
        }
      }
    }
  }
}
```

should result in 
```json
{
  "test": {
    "value": "#ff0000",
    "type": "color"
  }
}
```

and not in
```json
{
  "test": {
    "value": "#ff0000",
    "type": "color"
  }
}
```

**Comment by jorenbroekema** [comment]
No its API is not yet stable, still a few things coming that I think will be API breaking. It's a bit tricky to answer because V4 already solves a loooot of issues with V3 so staying on V3 might be more problematic than migrating to unstable V4 and doing another small migration to the final V4 when it releases (estimated in June)
