### ISSUE TITLE
Some token references could not be found

### ISSUE THREAD

**Issue by okadurin** [amzn/style-dictionary#1186]
Hi all, 
after migrating style-dictionary from v3 to 4.0.0-prerelease.26 I got the error:

```
../node_modules/style-dictionary/lib/StyleDictionary.js:451
      throw new Error(err);
            ^

Error: 
Reference Errors:
Some token references (48) could not be found.
```
Apparently I missed something in the migration. Any suggestion on what could be the reason what I might be missing?

**Comment by jorenbroekema** [comment]
Can you share your style-dictionary script/config? I can't think of what might cause sudden reference errors to be honest

**Comment by okadurin** [comment]
I am closing the issue as it is not related to `style-dictionary`. There is a script on my side which was messing with the source json file where tokens are located. At some point the script was refreshing the json file at the same time the`style-dictionary` was building the platform. That was the reason it stated it could not find some tokens.
