### ISSUE TITLE
Migration guide: format vs formatter

### ISSUE THREAD

**Issue by okadurin** [amzn/style-dictionary#1187]
The [migration guide](https://v4.styledictionary.com/version-4/migration/) mention multiple times that we need to use `format` instead of `formatter`, like in here:
<img width="1564" alt="Screenshot 2024-05-08 at 17 59 53" src="https://github.com/amzn/style-dictionary/assets/8991129/a7049887-aa61-4ddf-9e93-ea0a65ace240">
However in the source code [keeps using](https://github.com/amzn/style-dictionary/blob/v4.0.0-prerelease.26/types/Format.d.ts#L47) `formatter` in `v4.0.0-prerelease.26`. 
Should the doc be changed or should the source code be changed? Or am I missing something?
Thanks!

**Comment by jorenbroekema** [comment]
Yes, apologies, this breaking change is still awaiting release, will be in prerelease.27, it already deployed the updated docs 😅

**Comment by jorenbroekema** [comment]
Released 4.0.0-prerelease.27 , feel free to reopen if still an issue.
