### ISSUE TITLE
Migration guide: node 16 should be upgraded

### ISSUE THREAD

**Issue by okadurin** [amzn/style-dictionary#1191]
`v3` was compatible with `Node 16`. And `4.0.0-prerelease.26` is not anymore. One of reasons is `structuredClone` which [was introduced](https://developer.mozilla.org/en-US/docs/Web/API/structuredClone#browser_compatibility) in `Node 17`. 
The migration guide might mention the requirement for the Node upgrade.

**Comment by jorenbroekema** [comment]
https://github.com/amzn/style-dictionary/blob/v4/package.json#L35 it's in the engines field but I agree, would be great to mention in the migration guide! PR welcome -> https://github.com/amzn/style-dictionary/blob/v4/docs/src/content/docs/version-4/migration.md can be a section at the very top
