### ISSUE TITLE
Transform after replace references

### ISSUE THREAD

**Issue by kwivix** [amzn/style-dictionary#120]
As a developer I want to execute certain transforms after the references are replaced. In my case, perform certain actions on color's such as darken or lighten.

**The why**
I want to theme the design tokens, by having colors a few base colors and calculate the shades from them.

**Comment by kwivix** [comment]
I will keep an eye open for the PR. There is nothing wrong with first performing the transforms and then the references. Intact it makes the code a lot easier. Resolving references (recursive) 'on the go' while performing transforms will be a complex task.

**Comment by chazzmoney** [comment]
@kwivix Can you mention a little more about how you are thinking about using this?

The first part of your first message made me think you wanted to customize colors for specific output - say one color for iOS and another color for web/css.

The second part of that message made me think that you wanted to have a few starting colors and then modify them automatically to be in multiple shades. Something maybe like https://palx.jxnblk.com/00a

It might be possible to have two transforms happen at different times - one on initial token values and another immediately before output via format/template. I want to make sure that we are taking your use case into consideration.

**Comment by kwivix** [comment]
My use case concerns the second suggestion: I would like to start with three base colors that define the brand. From the brand colors I want to calculate the different shades and use the shades in the design tokens, such as tokens for button/heading/accent colors.

1. Define base brand colors
1. Calculate shades of the base colors
1. Use shades in design tokens

By changing the initial three base colors its possible to generate a new brand (or theme).

In the end there will be one design system for multiple brands. Each brand will have it's own colors. The brand colors are brand specific and won't be shared between brands.

**Comment by chazzmoney** [comment]
Thanks for the info, very helpful!

To clarify one more thing based on this use case:

> As a developer I want to execute certain transforms after the references are replaced.

You specifically mention executing transforms after the references are replaced in your first message. For the three step process you listed out in the most recent comment, the main requirement appears to be the ability to perform generative transformations. Was there a specific importance to doing this after the references are replaced?

**Comment by kwivix** [comment]
My first thought was to transform the values after resolving. After giving it some more thought I figured out a more generic solution is needed. It doesn't make sense to have two steps: Define base colors, calculate shades in design tokens. With the two step 'solution' a transformation has to be defined on every token or the application itself needs to use the shades directly. The later one defeats the purpose of having design tokens.

**Example with two steps:**
```json
{
    "color": {
        "brand": {
            "primary": {
                "value": "#ff0000"
            }
        },
        "background": {
            "button": {
                "primary": {
                    "base": {
                        "value": "{color.brand.primary.value}",
                    },
                    "hover": {
                        "value": "{color.brand.primary.value}",
                        "darken": "10"
                    },
                    "focus": {
                        "value": "{color.brand.primary.value}",
                        "darken": "10"
                    }
...
```

**Example with three steps:**
```json
{
    "color": {
        "brand": {
            "primary": {
                "value": "#ff0000"
            }
        },
        "palette": {
            "primary": {
                "base": {
                    "value": "{color.brand.primary.value}",
                },
                "darker": {
                    "value": "{color.brand.primary.value}",
                    "darken": "10"
                }
            }
        },
        "background": {
            "button": {
                "primary": {
                    "base": {
                        "value": "{color.palette.primary.base}",
                    },
                    "hover": {
                        "value": "{color.brand.primary.darker}",
                    },
                    "focus": {
                        "value": "{color.brand.primary.darker}",
                    }
...
```

**Comment by chazzmoney** [comment]
We also quietly added the feature to create property files using JS rather than JSON. Working on documentation for that now, but would that solve your problem?

**Comment by kwivix** [comment]
@chazzmoney Yes, it solves my problem and is even a bit more flexible.

**Comment by chazzmoney** [comment]
Great! Glad it worked for you. Let us know if anything else pops up for you.
