### ISSUE TITLE
outputReferencesTransformed resolves opacity variable in RGBA

### ISSUE THREAD

**Issue by okadurin** [amzn/style-dictionary#1201]
In `v4` the value as follows 
```
--overlay: rgba(var(--color-600), var(--overlay-value))
```
is transformed to something like 
```
--overlay: rgba(51, 51, 51, 0.7)
```
But on `v3` it was transformed to
```
--overlay: rgba(51, 51, 51, var(--overlay-value));
```
Note the opacity variable is resolved on `v4` and it is preserved on `v3`

Here is the code of my setup:
**token:**
```json
{
  "bg": {
    "overlay": {
      "value": "rgba({gray.color-600}, {opacity.overlay-value})",
      "type": "color"
    }
  },
  "gray": {
    "color-600": {
      "value": "#333333",
      "type": "color"
    }
  },  
  "opacity": {
    "overlay-value": {
      "value": "70%",
      "type": "opacity"
    }  
  }
}
```
And the **config**:
```js
import {
registerTransforms as registerTokenStudioTransformsAndParsers,
transforms as tokenStudioTransforms,
} from '@tokens-studio/sd-transforms';
import StyleDictionary from 'style-dictionary';
import { outputReferencesTransformed } from 'style-dictionary/utils';


registerTokenStudioTransformsAndParsers(StyleDictionary);

const config = {
  include: [`tokens/alias.json`],
  platforms: {
    css: {
      transforms: [...tokenStudioTransforms, 'ts/color/css/hexrgba'],
      buildPath: `build/`,
      files: [{
        destination: `variables.css`,
        format: `css/variables`,
        options: {
          outputReferences: outputReferencesTransformed
        }
      }]
    }
  }
};
```
---
Could you suggest how to make configure `v4` so it stops resolving `opacity` variables in an `rgba` function? That is instead of `--overlay: rgba(51, 51, 51, 0.7)` I would like `v4` to generate `--overlay: rgba(51, 51, 51, var(--overlay-value));` as it was on `v3`.

**Comment by jorenbroekema** [comment]
I think it makes sense to leave this issue open:

> Style Dictionary isn't smart enough to know exactly which references within the token value are safe to output as a reference, and which ones aren't

It's pretty late right now and I don't have my early morning brainpower but while writing this it made me go "but can we make it smart enough to determine this per reference in a token, rather than on the token as a whole", and I think that is worth exploring for sure, this may be a non-breaking enhancement to the v4 later down the line.

**Comment by jorenbroekema** [comment]
Closing question issue, considered as answered. See https://styledictionary.com/reference/utils/references/#outputreferencestransformed
