### ISSUE TITLE
CSS TransformGroup

### ISSUE THREAD

**Issue by dbanksdesign** [amzn/style-dictionary#122]
In the docs, https://amzn.github.io/style-dictionary/#/formats, it gives an example of a "css" transformGroup even though the framework does not have one built in. We should either change that to "scss" or add a "css" transformGroup. 

Another issue this causes is that when someone uses a non-existent transformGroup, the framework does not throw an error, which it does if someone tries to use a non-existent transform or format. We should throw an error in this case.

**Comment by didoo** [comment]
> when someone uses a non-existent transformGroup, the framework does not throw an error
I've learned it the hard way :)
