### ISSUE TITLE
Escape strings in ES6 format?

### ISSUE THREAD

**Issue by didoo** [amzn/style-dictionary#124]
Recently I have added a web font stack in a token, like this:
```
{
    ...
    "font-family": {
        "value": "Calibri, 'Helvetica Neue', Helvetica, Arial, sans-serif"
    }
    ...
}
```
which contains this kind of `'` quote. But in the ES format function what we do is to just concatenate the strings:
https://github.com/amzn/style-dictionary/blob/1bdd60b332aadb487df3d176292951a58627150a/lib/common/formats.js#L264-L269

This compiles to:
```
export const [...]_FONT_FAMILY = 'Calibri, 'Helvetica Neue', Helvetica, Arial, sans-serif'
```
which is not valid. Probably we should escape, somehow, the value `prop.value` (in theory also the `prop.name`, but let's be conservative). 

Two questions:
1) do you think we should do it? or are there are ways to avoid this problem? any other ideas?
2) in case we do it, what else should we consider as something to escape? other characters that we should consider special?

**Comment by chazzmoney** [comment]
Fixed in #127. Available in 2.4.0.
