### ISSUE TITLE
How to avoid Collisions on Figma variables with multiple columns?

### ISSUE THREAD

**Issue by bruno-lucas141** [amzn/style-dictionary#1246]
I've recently discovered that it is possible to use style-dictionary to transform Figma information into css/scss variables.

The issue is that i have some variables that have multiple columns and style-dictionary is overriding the variables.

is it possible to use a callback so i could decide what to do with the collisions? Or are there any custom function that i can send to customize the way the variables are created?

PSB an example of variable with multiple columns from Figma

```JSON
{
  "style.Dark.json": {
    "Primary": {
      "$type": "color",
      "$value": "#000000",
      "$description": "",
      "$extensions": { "com.figma": { "hiddenFromPublishing": false, "scopes": ["ALL_SCOPES"], "codeSyntax": {} } }
    },
    "Secondary": {
      "$type": "color",
      "$value": "#000000",
      "$description": "",
      "$extensions": { "com.figma": { "hiddenFromPublishing": false, "scopes": ["ALL_SCOPES"], "codeSyntax": {} } }
    }
  },
  "style.Light.json": {
    "Primary": {
      "$type": "color",
      "$value": "#ffffff",
      "$description": "",
      "$extensions": { "com.figma": { "hiddenFromPublishing": false, "scopes": ["ALL_SCOPES"], "codeSyntax": {} } }
    },
    "Secondary": {
      "$type": "color",
      "$value": "#ffffff",
      "$description": "",
      "$extensions": { "com.figma": { "hiddenFromPublishing": false, "scopes": ["ALL_SCOPES"], "codeSyntax": {} } }
    }
  }
}
```

**Comment by jorenbroekema** [comment]
Right now there isn't a way to customize how token collisions are handled, our deep-merge utility will handle it topologically, so if you specify the source like so:

```json
{
  "source": [
    "tokens/foo.json",
    "tokens/bar.json"
  ]
}
```

Then any collisions between foo and bar will mean that the duplicate definitions in foo will be overridden by those in bar.

So even though there isn't something like an onTokenCollision callback that allows you to customize the behavior, you can somewhat control it through ordering the "source" array values. Note that if you use globs, they will always resolve alphabetically, so `"source": ["tokens/*.json"]`, assuming still that we have `foo.json` and `bar.json`, should mean that the foo definitions will override the bar definitions, the opposite of the previous example.

**Comment by jorenbroekema** [comment]
Btw, I am open to creating a callback, but I'd have to know a bit more about use cases where the ordering of "source" array isn't sufficient as a means to control how collisions are handled

**Comment by bruno-lucas141** [comment]
I've managed to solve my issue but that required a Figma token refactoring.
Instead if adding the values as new columns under the same variable i've grouped them.

Before:
![image](https://github.com/amzn/style-dictionary/assets/143031257/81e259fa-d095-430f-a9e2-4fe92b53e031)


After:
![image](https://github.com/amzn/style-dictionary/assets/143031257/302a0181-a0c0-444a-aef4-8a35577c5b3b)


By using the refactored structure style-dictionary created a single scss/css variable for each parameter with no collisions.
![image](https://github.com/amzn/style-dictionary/assets/143031257/558e216d-2180-45d8-9b7e-8cb1e93ee34f)

To create Figma groups just use ```/``` in the name when creating a variable like so: ```brands/Brand3/Primary```
