### ISSUE TITLE
Tests for the generated output files/formats (Jest) 

### ISSUE THREAD

**Issue by didoo** [amzn/style-dictionary#125]
In the last week or so I have submitted a couple of PRs, and in both cases (especially in https://github.com/amzn/style-dictionary/pull/121) I was afraid to have broken something without knowing. Of course, there are some tests, but if you look at this code for example:
https://github.com/amzn/style-dictionary/blob/1bdd60b332aadb487df3d176292951a58627150a/test/buildPlatform.js#L127-L131
it's testing that the JSON in input and the resulting object in output have the same properties. 
But what happens if during the refactoring I am introducing changes after in the pipeline, in the function that generates the output or in the template files? and this results in the generated files being different than expected? My suspect is that we don't know and we don't have tests in place to make us feel confident that the changes are not introducing regressions (at least this was my impression while working on the PRs).

Any ideas, thoughts, suggestions (or alternatives) about trying Jest (and its [snapshots capabilities](https://jestjs.io/docs/en/snapshot-testing)) to cover also the output/generated files?

**Comment by chazzmoney** [comment]
We could solve this by adding format/template tests that would ensure that the formats / templates are being generated as expected. That should give us end-to-end testing as per your suggestion.

Additionally, I like the idea of having one set of tests for generating the properties and another section of tests for generating output from those properties.

**Comment by chazzmoney** [comment]
We now have a usable structure in place for this. Just need to get all the tests set up the way we want.

**Comment by didoo** [comment]
Maybe we can close this one now?

**Comment by chazzmoney** [comment]
@didoo I was trying to decide if that was right. Is this done? Or is it only done once we have tests in place for every format?

**Comment by didoo** [comment]
In my initial comment, I was mainly referring to snapshot testing (which, for me, is the most important part, since SD is made to **generate** output files :) ). AFAIK we are covering all the formats with snapshots testing via `__tests__/fomats/all.tests.js`, no?

BTW in that file this test should be split: https://github.com/amzn/style-dictionary/blob/eba4970065941aab4403b4f544a805ae3846fcd9/__tests__/formats/all.test.js#L76
this test is for _"should return [test] as a string"_, there should be another declaration for the snapshot ones (https://github.com/amzn/style-dictionary/blob/eba4970065941aab4403b4f544a805ae3846fcd9/__tests__/formats/all.test.js#L80). Is it OK if I do a PR tomorrow? Or it causes too many conflicts in the resulting tests with the open branches?

**Comment by chazzmoney** [comment]
You can make the branch and PR whenever. If you do it before we merge the sass map and example branches, you'll just have to do a pull / merge somewhere. Up to you whether you want to wait or do it now.

**Comment by didoo** [comment]
OK, I'll add it in my todo list then.

**Comment by chazzmoney** [comment]
Complete as of v2.7.0
