### ISSUE TITLE
allTokens is an empty array but tokens is set

### ISSUE THREAD

**Issue by lukasoppermann** [amzn/style-dictionary#1283]
Hey,

I am trying to upgrade to v4. However I am running into an issue where `.allTokens` is `[]` but `.tokens` is set.

I used `allTokens` in formats and other custom code. Is this not supposed to be used anymore? Am I doing something wrong here?

Please let me know how I can provide more info to help solve this.

Just FYI, this is happening in two different repos.

**Comment by jorenbroekema** [comment]
[It's still supposed to work](https://configurator.tokens.studio/#project=zVjZbuM2FP0Vwi2QBEhkS17ieNCiyyDtU1s0A7RFHRSUSFmckUiBlJJ4DP97SUmWKJqinUGA1g8JRN5zec/duOxGoigRYd5HwehoNdqtKQDrUcRSxsV6tALVgBr6utjmWI00s+vR9WEqTGH0SROuxJ9gWjbyX02q33pUT+9b4HNCCuwCxtXvGMg4pBsT6asltBGbNhi3ZnT6lGBwEoxxGC3t4OlJcIimS2QHz06CFxDN53bw/BQYo+XddGEHL06BEVqEwYDDbk+Bo8l8Efh28PIU+C6aBUPgu1Pg23A687EGbtJH/asVrUeIZJgKwmg/yyeObJzkL8eZ6DsAMxsgcACWNsDUAfADG2LmQixsiLkDEVh5L1wIK/FbF8LKfOlATK3M71wIK3PfFfGZPeTOmFu5+66oz6zkfVfc51b2vivwczt9V+QXVvraRtAWkbYZZPDFofJO/jSlekUW+KXo1WLMaCFMXd3iavoeZiTdtqsrCYE5iZ394YO0WoBf8DP4nWWQXoMGYus1AlLhVPZrjil4kFJSjfx7Y+o62vIw2SSnaP1RCfVopfWIw5IiIdROguNNmULuRLcyNgUhS5ETLUPH4U0tNkg9JRT/fIo+LbMQ8x51yngGU8f6vhfYrJZ0jDOCCVsO2ioNYhsO82Q7bKouoy2bYIgI3TgW1oaBkchK705Vgldlv6dyaq+p7xCHHOkQTWp5Kgx2zAP53Ni+6/Y/7/ZYuAuVvoAWQK9y7r6LdutDM3PQ9o08oQrrta5osvo13ph9iTfqFB1wh63XyfOrIMXR8UPPrlZEa644yxMoiBjssD0/o5LDWkFtdbeod5gSXoYRKbM+aQnFKdw6cYSKAtLCBBYkk8l/X9JoYGUs7e8EhAejCKdYatWz6ageY4jwG5JOGd38d5QRPoeygRruQ1EZkugH/JkYfbPzrKMC/9ZTfeLNe6k/6X35/a/u49FW+R3Js1d3rG1aZl3d9GAbuWHfddmimd7E2bnjTTIxcGJIGHdD5T11CFwXoxM9HUarrHZiFwbW0plCxhEevvrX01pHkrvd0/a8ymyeDaryqB8YvOrlwKynZ4KK5Lgx+6acKLbpoYE3ZnvVmPzHUoJcxfVMOI45zPAXm14/QXjSpWfaH7zCfgRFgp0EasHhxBYFZ5/wQ72Enp7KM84kaSSsNV2Zdf5+ruS/57xuq71ar+7a3pzjzNht64mgntEnHi2b8o8wb06vrKTo7N1XJBCx58Ecr6e1HBfZ2yY4i2OBiz+PU2Ril/zrjGII05Ifi01dKZRu/ne0gvNozfYDTWxN96NrdZchosD84X23534U8nWTZLlszqCqivekmoF8C2LOMnBRVdQNaocv3q1pA9iBg0qwb6S/K2R5qfte9Xw6Fuim2vFjeRAUCrmmxireQcW9OisWl5WLqexAK3ARM3ZR0Y6ruRW43AGYph+qJa5BZxPYX4Fvvj2EJ5LEWIrlaWZz2YpfHc91eM8U47goOa0teHdw4ZUyfzwGPVLXIKAI5FA1TeUIOQhYXjkXRJCCEAOIkOwOCvmAMUAsEiuQFEUuVuPxhhRJGXoRy8YOz63pwUuXhvuupHUytJJWTDbGa7VgJY/088Raf9WuU+Wxqf2c45yzCAvRPHC3kJ5ZBiiFRW2f3jIiYfbflshPsiE1rclQq9+NSpKi3+Bhr6g+x1LpuCcVk6bPa/3TbLNYFIRqp95/niAnMFQ7SWXk0eVHZdnhuYFZ++ajWVb7fwE=)

**Comment by lukasoppermann** [comment]
Okay, I think the issue has to do with my parser. It outputs `value` instead of `$value` (I wanted to deal with this later, as it means I have to adjust all transformers) and I think because of this, there is nothing in the allTokens, but somehow stuff is in tokens.
