### ISSUE TITLE
Style Dictionary used to tell me about missing references

### ISSUE THREAD

**Issue by wzamites** [amzn/style-dictionary#1288]
In Style Dictionary 3, I used to get a list in the console about which references were not found. Since updating to 4, I just get this error:
```
Error: 
Reference Errors:
Some token references (6) could not be found.
Use log.verbosity "verbose" or use CLI option --verbose for more details.
```
How can I find out which exact 6 token references are not found?

**Comment by jorenbroekema** [comment]
I think the last sentence in that error should give you a hint how to make the error show you more details right?
Refer to https://styledictionary.com/reference/logging/ and set `log.verbosity` in your global or platform config to `'verbose'`
