### ISSUE TITLE
Don't add prefix for includes

### ISSUE THREAD

**Issue by lukasoppermann** [amzn/style-dictionary#1327]
Hey, 

we are using base tokens (`include`) that do NOT use a prefix and the `source` tokens do.

However, in the output for the functional tokens we do get the prefix in the reference.

```css
--PREFIX-padding-sm: var(--PREFIX-size-4);
```

What I want to get is:
```css
--PREFIX-padding-sm: var(--size-4);
```

Is this at all possible?

**Comment by lukasoppermann** [comment]
Okay, thanks. So would I use the transformer to ADD or REMOVE the prefix? 

Where in the process is the prefix added? I didn't quite find it. Is it in the format? As part of the formatted variables call?

**Comment by jorenbroekema** [comment]
You have a lot of options, you can do it through a custom transform hook of type "name" similar to the built-in ones e.g. "name/kebab" https://github.com/amzn/style-dictionary/blob/main/lib/common/transforms.js#L323 here yuo can see how the config.prefix prop is included.

However, you only want to do this prefix include conditionally, when `token.isSource` is not `true`.

**Comment by lukasoppermann** [comment]
I am using this transformer now and it works, thank you:

```js
export default {
  name: 'name/pathToKebabCasePrefix',
  type: `name`,
  transformer: (token, platform = {}) => {
    const {prefix} = platform
    const addPrefix = platform.addPrefix ?? (() => true)

    const getPrefix = (token, addPrefix) => addPrefix(token) && prefix

    return (
      [getPrefix(token, addPrefix), ...token.path]
        // remove undefined if exists
        .filter(part => typeof part === 'string' && part !== '@')
        .join('-')
    )
  },
}

```
