### ISSUE TITLE
Make the error returned by the "registerTemplate" function more meaningful

### ISSUE THREAD

**Issue by didoo** [amzn/style-dictionary#134]
Very small issues, easy to fix (I can work on it): when `registerTemplate` throws an error, you don't know which option value was passed at that moment to the function:

<img width="1106" alt="screenshot_1742" src="https://user-images.githubusercontent.com/686239/45705530-bf4d1a80-bb71-11e8-9d33-cd8172e0c040.png">

I think we can pass the `option.name/template` value to the error strings to make more explicit what caused the error.

**Comment by chazzmoney** [comment]
#135 has been merged, thank you @didoo !

I'm leaving the issue open until develop is merged into master for release.

**Comment by chazzmoney** [comment]
This has been merged in 2.5. Thank you @didoo!
