### ISSUE TITLE
Add 'json/flat' format

### ISSUE THREAD

**Issue by dbanksdesign** [amzn/style-dictionary#138]
From the discussion on #58 , we want to add different types of JSON formatting for different purposes. This format should output a JSON string that only has 1 level where the keys are the property name and the value is the property value. For example, this style dictionary JSON:
```json
{
  "size": {
    "font": {
      "small": { "value": "13px" },
      "medium": { "value": "15px" },
      "large": { "value": "17px" },
      "base": { "value": "{size.font.medium.value}" }
    }
  }
}
``` 

Would output this in the 'json/flat' formatter:
```json
{
  "SizeFontSmall": "13px",
  "SizeFontMedium": "15px",
  "SizeFontLarge": "17px",
  "SizeFontBase": "15px"
}
```

You can have a look at how the other [formatters](https://github.com/amzn/style-dictionary/blob/master/lib/common/formats.js) are written to see how to write a formatter and where it should go. 

Make sure to include proper jsdoc comments and unit test!

**Comment by ericbreno** [comment]
Looking into it, interesting!

**Comment by chazzmoney** [comment]
Merged, closing

**Comment by kerryj89** [comment]
When using `json/flat` it keeps the hyphens and I'm assuming other symbols.  Is there a way to easily transform it to not include them so that we can simply import the json and do `tokens.sizeFontSmall` and not `tokens['size-font-small']`?

**Comment by jorenbroekema** [comment]
Yes, by adding a name transform that converts token names to camelCase

E.g.
```js
{
  "source": [
    "tokens.json"
  ],
  "platforms": {
    "json": {
      "transforms": [
        "name/camel"
      ],
      "buildPath": "build/json/",
      "files": [
        {
          "destination": "vars.json",
          "format": "json/flat"
        }
      ]
    }
  }
}
```

[Example](https://configurator.tokens.studio/#project=fVK7bsMwDPwVQktawI6AopO7dAg6F8hYdVAsOVFrS4ZEF0kN/3v1sOPH0EW2jifyyGNPHHZCmf2XM5oUpGcagBGhGqmdMpqRAiIWUKd+ZX51CyygP7zuZMAYeW6vjGRzCG/tGFkkTOEhfPwxkIxYeVYOpT0e3jpdomc5r8erUU1rLMIRb7U8qBjh9gaVNQ3sXEBzcYd3L0yPD3qYUsIwsl/RfHsFeWqXOpGj5dpVxjYuvGSaUlihGTxpAS23vJEhkwfBtFEdlFzDSQIXQor48iglCFO6Ai6IrSsoPSu8dKd9aRr6T2mmJ6UPmy4fvSg/m9LoSp039jjT2TJO9uPuzWxjGvFnlrhtzTGVWlqZeCsfF6LmxCmk/Qho6Y96sm/Kn+KnTtXineMlmR2vNJSgq3WoVC23yfv5Ny6edKg0x3H1wnZZN3aVralBKsfEirWqOlxn0nCXul254Q8=)
