### ISSUE TITLE
Add 'json/nested' format

### ISSUE THREAD

**Issue by dbanksdesign** [amzn/style-dictionary#139]
From the discussion on #58 , we want to add different types of JSON formatting for different purposes. This format should output a JSON string that maintains the structure of the style dictionary JSON, but only includes the values and nothing else. For example, this style dictionary JSON:
```json
{
  "size": {
    "font": {
      "small": { "value": "13px" },
      "medium": { "value": "15px" },
      "large": { "value": "17px" },
      "base": { "value": "{size.font.medium.value}" }
    }
  }
}
```

Would output this in the 'json/flat' formatter:
```json
{
  "size": {
    "font": {
      "small": "13px",
      "medium": "15px",
      "large": "17px",
      "base": "15px"
    }
  }
}
```
You can have a look at how the other formatters are written to see how to write a formatter and where it should go.

Make sure to include proper jsdoc comments and unit test!

**Comment by davixyz** [comment]
Added this format but i'm not sure, to which branch do I issue the PR? I issued it to develop for now but I can change it if needed
