### ISSUE TITLE
ESLint Airbnb

### ISSUE THREAD

**Issue by davixyz** [amzn/style-dictionary#154]
This might be a little controversial but:
As we move into ES6 world it would be good to also update the linter to a harder one
Here's my suggestion:
https://github.com/airbnb/javascript
Using:
https://www.npmjs.com/package/eslint-config-airbnb-base

If we don't go the ES6 path there's also a legacy ES5 airbnb linter

**Comment by vvscode** [comment]
And this one I'm also ready to take

**Comment by chazzmoney** [comment]
Might consider doing this in conjunction with #153 

Actually, maybe we should wait on both of these until we merge #169

**Comment by vvscode** [comment]
@davixyz  what about closing?

**Comment by dbanksdesign** [comment]
Sorry about that! Done! Thanks again for the contribution!
