### ISSUE TITLE
Prettier integrated as part of the workflow

### ISSUE THREAD

**Issue by davixyz** [amzn/style-dictionary#155]
Since nobody likes to argue about code style, we could integrate prettier as a git hook to automatically format code based on our own spec

https://prettier.io/

**Comment by vvscode** [comment]
@chazzmoney  I'm ready to do it - to which branch should be PR?

**Comment by vvscode** [comment]
propose both:
- [ ] - pre commit hook
- [ ] - checking on travis

**Comment by chazzmoney** [comment]
Created a new branch. Use:

develop-3.0

**Comment by chazzmoney** [comment]
Since this was marked milestone 3.0, and #168 has been merged into the develop-3.0 branch, I'm marking this as completed.

Nice work @vvscode!
