### ISSUE TITLE
Write documentation on modifications via JS property files

### ISSUE THREAD

**Issue by chazzmoney** [amzn/style-dictionary#159]
People seem to want this still, so we should either build it in or write up some very clear documentation on how to go about using JS property files to do this.

#59, #120 both were related to this.

**Comment by chazzmoney** [comment]
We have an example here:
https://github.com/amzn/style-dictionary/tree/master/examples/advanced/node-modules-as-config-and-properties

**Comment by chazzmoney** [comment]
Still need to write documentation on this though...

**Comment by dbanksdesign** [comment]
This is fixer in 3.0!
