### ISSUE TITLE
Add JSON5 property file support

### ISSUE THREAD

**Issue by chazzmoney** [amzn/style-dictionary#160]
Pull in properties from files written in JSON5.

**Comment by vvscode** [comment]
I'm taking it

**Comment by chazzmoney** [comment]
The actual import of the file data is done for both JS and JSON here:

https://github.com/amzn/style-dictionary/blob/master/lib/utils/combineJSON.js#L43

You may need to parse through things a bit to see how it all ties in. Let us know if you have questions.

**Comment by chazzmoney** [comment]
Oh, and you should work against the develop branch.

**Comment by vvscode** [comment]
https://github.com/amzn/style-dictionary/pull/165
