### ISSUE TITLE
Add documentation on using watchers to auto-rebuild style-dictionary

### ISSUE THREAD

**Issue by chazzmoney** [amzn/style-dictionary#170]
Specifically in regards to #106

**Comment by didoo** [comment]
Maybe just a quick reference to the example `auto-rebuild-watcher` in #164, where is well explained? ([see the Readme for that example](https://github.com/didoo/style-dictionary/tree/better_examples/examples/advanced/auto-rebuild-watcher))

**Comment by didoo** [comment]
Do you think we can close this one, at this point?

**Comment by dbanksdesign** [comment]
Yup, good work!
