### ISSUE TITLE
webpage has bug

### ISSUE THREAD

**Issue by lengyue1024** [amzn/style-dictionary#175]
The product is great, but the instructions page:<https://amzn.github.io/style-dictionary> ,I think there are some bugs, that is, when you **use a mobile device** , there will be a mess of styles, you can see the red part of the image I've labeled below.
![img](https://ws1.sinaimg.cn/large/006DGX4tly1fwfveq2180j30u01fugpt.jpg)
The navigation bar will not show up. You can see the chart below. 
![img](https://ws1.sinaimg.cn/large/006DGX4tly1fwfuskgfrqj30u01gujsb.jpg)

**Comment by didoo** [comment]
@lengyue1024 I have fixed the overlapping between buttons and logo in #176, for the navigation is not so easy so I have created a new specific ticket #177.

@dbanksdesign probably this can be closed once #176 is merged, wdyt?

**Comment by lengyue1024** [comment]
ok，i think u are right.close it.

**Comment by lengyue1024** [comment]
First of all, thank you for helping me, but I think now that you have fork for this project, I would like to ask you to re-optimize this page, and merge it into the warehouse, so that others can use it directly. I may be rude to ask you to do this, but I personally can not css, js. 

发送自 Windows 10 版邮件应用

发件人: Cristiano Rastelli
发送时间: 2018年10月21日 19:47
收件人: amzn/style-dictionary
抄送: 冰羽; Mention
主题: Re: [amzn/style-dictionary] webpage has bug (#175)

@lengyue1024 I have fixed the overlapping between buttons and logo in #176, for the navigation is not so easy so I have created a new specific ticket #177.
@dbanksdesign probably this can be closed once #176 is merged, wdyt?

**Comment by dbanksdesign** [comment]
Just approved and merged #176. There is the larger point that our documentation site needs some love, especially for smaller screens (that is on me for not doing that already). Maybe with the 3.0 release we could clean up the design of the docs a bit as well.

**Comment by didoo** [comment]
@dbanksdesign re. the documentation, there is already a lot in that milestone, probably I would think about it later (for now this issue it's important but not blocking, so we can live with that for a little bit).

@lengyue1024 the fix has been merged in master, so it's already available in this repo.

**Comment by lengyue1024** [comment]
@didoo  Thank you for your contribution, but navigation is still problem , I think this is also an urgent need to solve the problem, after all, to give users the best experience is perfect.

**Comment by chazzmoney** [comment]
This has been fixed with the merge of #176 and #179.

Please open additional issues if you find other problems.

Thanks!
