### ISSUE TITLE
Navigation for the website should be responsive

### ISSUE THREAD

**Issue by didoo** [amzn/style-dictionary#177]
As reported in #175 the website navigation is not working on small viewports. We need to figure out what is happening (there are some overrides of the _vue.css_, I think, which work only for large viewports).

**Comment by dbanksdesign** [comment]
I opened a PR to fix this, if someone wants to take a look I can merge it today to get this fixed!

**Comment by didoo** [comment]
@dbanksdesign apart from a couple of comments, code looks ok to me.
