### ISSUE TITLE
Clean action

### ISSUE THREAD

**Issue by dbanksdesign** [amzn/style-dictionary#18]
There should be a better way to clean build artifacts. Because you can generate files in any place, if you change paths around there might be zombie artifacts littered around.

**Comment by chazzmoney** [comment]
Are you saying it should delete all the files it knows it is generating?  or something else?

**Comment by dbanksdesign** [comment]
Yes exactly. 

One thing I've noticed while I use the build system is sometimes I'll change the path of build artifacts and forget to delete them. Then I have these zombie files laying around. But maybe this is not a huge problem or one that this framework needs to solve. 

Another solution is to suggest that people put all the generated files in 1 directory so random files don't pollute a project.

**Comment by chazzmoney** [comment]
I've started a branch for this titled 'adding-clean-action', including tests.  I need to add in tests to ensure it deletes directories that are created.  Actually... I'm not sure I'm doing that safely.  I'm recursively chopping the dirname var and testing to see if it is an empty directory (see cleanFile.js).  Let me know if you have a better solution.

Also, I don't have a good idea on how to clean actions defined in the config.  Right now the tests fail for that piece.  I created a cleanActions.js, which calls the action with a third argument of 'clean'.  Thats probably not the right way to go either.

**Comment by dbanksdesign** [comment]
The directories thing is interesting, I hadn't really thought about the directories that get created when things get built. I actually think how you are doing it looks good, the code could maybe be more clean but the logic is sound (at least I think....).

My thought for the clean actions thing, is that actions should now have 2 functions, a action function and a clean function, or do and undo basically. Then when we do the clean we just call the clean function. I can code this up if it doesn't make sense. 

Another note looking at the code, I think for the cleanFile functions we might not need the extra dictionary/config stuff. But I guess what is the harm in keeping it there? I don't know.

**Comment by dbanksdesign** [comment]
Pushed a commit to the branch for the clean actions thing to the branch.

**Comment by chazzmoney** [comment]
Looking over your commit, some thoughts:

- I like how you've built an action definition to have two parts
- action.action seems weird.  Maybe action.do and action.undo?  Or action.perform action.clean? Or... you get the idea
- What do we do about directories that are created?  Like via copySync?

Lastly, regarding your comments about the dictionary/config stuff being in the cleanFile functions... I had the thought of removing them.  I can't think of how we might need information in them to perform a clean... but... if later, there _is_ something we need in them, then we would have to add them back in, and then we would have a different function signature to buildFile.  So I was aiming for future symmetry to buildFile if something came up later.  Maybe the solution is to remove them and convert buildFile to have symmetrical arguments? 

Let me know your thoughts.  I want to nail this down so we can have this in the pipeline to merge in the next couple weeks.

**Comment by dbanksdesign** [comment]
Makes sense about the cleanFile stuff, keep it in for now.

Yea action.action is weird. I like action.do, and action.undo. For directories that are created in the action, it will the the action.undo method to handle 'undoing' that. That gives the flexibility so that the action itself defines how to clean up itself. An action might not even write any new files for instance.

**Comment by chazzmoney** [comment]
What did you think of my suggested solution to the arguments situation?

"So I was aiming for future symmetry to buildFile if something came up later. Maybe the solution is to remove them and convert buildFile to have symmetrical arguments?"

Options:

1. Leave it as built so we have symmetrical arguments (and currently useless ones for clean)
2. Remove unnecessary arguments from clean, breaking symmetry
3. Remove unnecessary arguments from clean and change signature of build functions to an order where the "unnecessary" arguments from clean are at the end of build.

I lean either 1 or 3

**Comment by dbanksdesign** [comment]
Yea lets keep it for symmetry for now, we can always cut it out later.

**Comment by chazzmoney** [comment]
PR merged.
