### ISSUE TITLE
There are problems with web pages.

### ISSUE THREAD

**Issue by lengyue1024** [amzn/style-dictionary#185]
@didoo This option is problematic. It can be seen from the red line in my picture.
![img](https://ws1.sinaimg.cn/large/006DGX4tly1fwsx17x48sj311m0gj0ub.jpg)

**Comment by dbanksdesign** [comment]
Opened a PR to fix it, docsify released a new version that had a bug. I filed a bug on their repo for this as well: https://github.com/docsifyjs/docsify/issues/677

**Comment by dbanksdesign** [comment]
Ok try it now, I just merged the change. Also, thank you again for catching all these documentation site bugs!

**Comment by chazzmoney** [comment]
@lengyue1024 Thanks for finding this! Solved w/ #186
