### ISSUE TITLE
Update docs to better explain referencing

### ISSUE THREAD

**Issue by dbanksdesign** [amzn/style-dictionary#189]
Our docs don't really explain referencing/aliasing design tokens very well and how that works. The only place I could fine is https://amzn.github.io/style-dictionary/#/README?id=the-basics and https://amzn.github.io/style-dictionary/#/quick_start?id=creating-a-new-project

Doing generic aliasing across files, and for any attribute is a good selling point of Style Dictionary that can get lost a bit. I've had multiple people ask me about it. I don't have a specific fix in mind, just want to start the conversation.

**Comment by chazzmoney** [comment]
And maybe add an example or two in #136 / #164

**Comment by didoo** [comment]
@chazzmoney the example of aliasing is in the "basic" example:
https://github.com/didoo/style-dictionary/blob/better_examples/examples/basic/properties/color/font.json
(it is already there in the current example)

Do you think we should do more? I would not put it in the "advanced" section :)

**Comment by chazzmoney** [comment]
@didoo I think that definitely covers the basic use. The other three I was thinking about were:

1. Alias chaining (e.g.g. alias refers to alias referes to alias ... refers to value)
2. Multiple references in a single property (similar to what you had)
3. Aliasing a higher level object (not a property)

**Comment by dbanksdesign** [comment]
There a few things going on here that aren't explained very well:

1. The aliasing/reference replacement stuff, you can reference _anything_ in any part of a dictionary file. You can reference whole objects if you wanted. This is why the examples it is "{size.padding.base.value}" because we want that specific part of the object.
2. The reference resolution step of the build process happens _after_ transforms happen. This was a questionable decision made by me early on before knowing the full scope of that decision. So transforms get applied to the whole object, and then all the references are resolved afterwards.
3. "value" key is special. Style Dictionary is built around the fact that "value" is a special object key, when Style Dictionary sees a "value" that is how it knows that part of the object is a design token. You can have whatever you want in your JSON files, but only objects with "value" are design tokens. Transforms are only performed on design tokens, and because transforms happen before references are resolved, no transforms will apply to `color.base.white.val` in you example. 
4. The whole CTI structure thing is more personal preference, although all the built-in transforms and formats are predicated on that structure. So the color transforms are applied to anything under the 'color' top level namespace. You could do it another way, which I want to have some examples showing other structures than the one I use. 

Hopefully this helps more than it confuses things.

**Comment by didoo** [comment]
@chazzmoney I'll add your suggested examples in #164

**Comment by chazzmoney** [comment]
@didoo Wowza - thats great! I'll try to add some documentation referring to your examples after the merge.

**Comment by didoo** [comment]
@dbanksdesign @chazzmoney I have pushed an example about the referencing/aliasing:
https://github.com/amzn/style-dictionary/pull/164/commits/f5873cd337a1206d64e1d373c2096f8160a7bf18

I am not sure I am covering all the cases you mentioned above, in particular the _"Aliasing a higher level object (not a property)"_ / _"You can reference whole objects if you wanted."_
(I am not even sure myself how this work, I tried something but didn't work as expected 😬)

Do you want to amend/add something to that example? In any case, I think this will require an update to the documentation itself too, not just an example.

**Comment by dbanksdesign** [comment]
@didoo that example is great! For aliasing a whole object, something like this works:

```json
{
  "color": {
    "red": {
      "value": {"r": 255, "b":0, "g":0}
    },
    "font": {
      "base": {
        "value": "{color.red.value}"
      }
    }
  }
}
```

Do you think that would be a good example to include?

**Comment by didoo** [comment]
@dbanksdesign I have added it as an example: https://github.com/amzn/style-dictionary/pull/164/commits/113d2663886e29ed50bbcb589ff4cc26a6f5ef9c. 

PS: now I realize what you meant. In my mind, I was thinking something like:

```
// size/font.json
{
  "size": {
    "font": {
      "small" : { "value": "12" },
      "medium": { "value": "16" },
      "large" : { "value": "18" }
    }
  }
}

// button/button.json
{
  "button": {
    "text": {
      "size": "{size.font}"
    }
  }
}
```
which doesn't work (maybe is worth to mention it, when we update the documentation about aliasing/referencing, and explain why it doesn't work: at the beginning, I was surprised by it).

**Comment by dbanksdesign** [comment]
Ah yes. Your commit looks good. And yea, your example works in a way that is unexpected.. Because of how the build process works, we do all the transforms first, then replace all the references. So depending on your transforms, you might get something like this:

```json
{
  "button": {
    "text": {
      "size": {
        "small": {
          "value": "12px",
          "original": {
            "value": "12"
          },
          "name": "size-font-small",
          "attributes": {
            "category": "size",
            "type": "font",
            "item": "small"
          },
          "path": [
            "size",
            "font",
            "small"
          ]
        },
        "medium": {
          "value": "16px",
          "original": {
            "value": "16"
          },
          "name": "size-font-medium",
          "attributes": {
            "category": "size",
            "type": "font",
            "item": "medium"
          },
          "path": [
            "size",
            "font",
            "medium"
          ]
        },
        "large": {
          "value": "18px",
          "original": {
            "value": "18"
          },
          "name": "size-font-large",
          "attributes": {
            "category": "size",
            "type": "font",
            "item": "large"
          },
          "path": [
            "size",
            "font",
            "large"
          ]
        }
      }
    }
  }
}
```

Because we would transform size.font.small, size.font.medium, and size.font.large, than then replace button.text.size with the whole transformed size.font object. Which is a bit weird and not what people would expect... A weird side-effect of how it was built. 

Great work on the examples!

**Comment by chazzmoney** [comment]
My bad on not getting this done sooner. We can close this after #272 is merged.
