### ISSUE TITLE
YML, JSON5, and HJSON support

### ISSUE THREAD

**Issue by dbanksdesign** [amzn/style-dictionary#19]
These formats are a bit better suited than raw JSON because they have nicer formatting and allow comments.

**Comment by dbanksdesign** [comment]
To start, document the ways people can use YML, JSON5, and HJSON already.

**Comment by dbanksdesign** [comment]
Made a yaml example: https://github.com/amzn/style-dictionary/tree/yaml/example/yaml

**Comment by custa1200** [comment]
I also would love to see JSON5 support

**Comment by chazzmoney** [comment]
JSON5 support was added in #165.

HJSON and YML are not yet supported
