### ISSUE TITLE
Create new method 'registerFilter' to enable custom filtering

### ISSUE THREAD

**Issue by chazzmoney** [amzn/style-dictionary#207]
From #199:

Define a new registerFilter method in Style Dictionary (similar to what we have with registerFormat, registerTemplate, registerAction) so that we can do:

"filter": "name_of_the_filter"
(in the same way as we do "template": "name_of_template" or "format": "name_of_format").

Then in the filterProperties function declaration we can easily detect if the filter is a "custom" filter by the fact that is a string.

This creates consistency across how we define our configuration (and customizations of it).

**Comment by didoo** [comment]
FYI I have started to work on this one.

**Comment by chazzmoney** [comment]
Added in v2.7.0

Thanks @didoo !
