### ISSUE TITLE
Process references first / at the same time as transforms

### ISSUE THREAD

**Issue by chazzmoney** [amzn/style-dictionary#208]
https://github.com/amzn/style-dictionary/pull/198#issuecomment-441364947
https://github.com/amzn/style-dictionary/issues/120#issuecomment-418522257

We've had a couple issues come up in regard to handling references/aliases before transforms (or at the same time). We also are looking at #205, which would require this change (depending on what we choose to do).

**Comment by chazzmoney** [comment]
Adding to 3.0 as this could be considered a breaking change.

**Comment by lancetharper** [comment]
I have found this somewhat counter-intuitive when first starting out with SD. It would go a long way toward increasing flexibility of token creation if you don't follow strict CTI (me! 😄).

Loving SD but this is my biggest sticking point so far. Hope to see this land soon!

**Comment by lancetharper** [comment]
@didoo Yes! I've read your article and haven't had a problem ignoring the CTI structure; I've just re-wired it to abstract it out of naming.

I just want to be able to do transforms on referenced/aliased tokens

**Comment by mhewson** [comment]
as an example, It would be great maintain alpha channel values separate from foundational color tokens and combine these underlaying values into tokens

**Comment by shaunbent** [comment]
I have just ran into this problem by trying to exactly what @mhewson is describing above.

Do you have a clear plan of what you intend to implement @chazzmoney? I'd be happy to try and help out with this if I can find sometime.

**Comment by chazzmoney** [comment]
@shaunbent thanks for bringing this back up, I think this is actually something we need to think about soon.

I don't have a clear plan. [The way SD works is pretty step by step currently](https://amzn.github.io/style-dictionary/#/build_process); I think there would be some heavy changes involved (and likely breaking) to get everything to run in a new order or all at the same time.

If you find some time, i would _LOVE_ to see someone outside take a stab at it (diversity of thinking results in better solutions). I'm happy to answer any questions as they come up!

**Comment by mfal** [comment]
I really like the idea of creating new tokens from other tokens by transforms (like color transformation e.g. with polished).

#371 enabels this feature and now is ready to be reviewed!

**Comment by chazzmoney** [comment]
Just wanted to put a huge acknowledgment of @mfal

Your diverse thinking and hard work created a more flexible (and better) solution. Your contribution solved a variety of issues people were running into trying to have SD work for their use cases. You moved SD forward in a really significant way that will impact the ease of managing styles in code.

THANK YOU!
