### ISSUE TITLE
Renaming "sass" and "scss" more accurately

### ISSUE THREAD

**Issue by TheJaredWilcurt** [amzn/style-dictionary#213]
The language Sass has two syntaxes (and filetypes to denote which is used):

* `.sass` - Syntactically Awesome Stylesheets - Whitespace dependent, strict, built in linting, shorthand, enforced consistency across all files, removes curly braces (`{}`) and semi-colons (`;`) in favor of indentation and end-of-line characters. Good for writing CSS Rules, nested rules, mixins, and functions.
* `.scss` - Sassy Cascading Stylesheets - All valid `.css` files are valid `.scss` files, more familiar for beginners, complete control over formatting and white space. Good for writing single-line table-like rules, and long or deeply nested lists/maps.

* * *

Style-Dictionary has many format output options. These are the ones related to the Sass language:

* `scss/variables`
* `scss/icons`
* `sass/map-flat`
* `sass/map-deep`

The naming of these is confusing as all of them output to the `scss` syntax and `.scss` files.

To avoid confusion these should be renamed to:

* `scss/variables`
* `scss/icons`
* `scss/map-flat`
* `scss/map-deep`

Also, documentation says things like `Creates a Sass file`, which is technically true if using "Sass" to refer to the language, but it is confusing as the actual file produced ends with `.scss`. People may misunderstand "Creates a Sass file" for "Creates a .sass file". It would be less ambiguous to say "Creates a .scss file".

* * *

This change does the following:

* Avoids confusion
* Sets proper expectations
* Makes naming consistent and predictable
* Frees up the name space to allow expanding to `sass` syntax in the future
  * Ideally to the point that all `scss/*` items will have a `sass/*` alternative that outputs the same format but with the indented syntax. However, that work can't really begin if the existing formats are using the wrong name.

* * *

* * *

On the same topic, `scss` is the name used for the "platform" and "transformGroup". Platform doesn't make sense as `scss` is just a syntax, and not a platform. The Sass language should be considered the platform, since `.sass` and `.scss` files can interact with each other in the same project. I'm new to Style-Dictionary, so I'm not certain what value `"transformGroup"` holds, but the same logic should be applied there.

As it stands currently, without spending a bunch of time in the docs, the following is very confusing and unintuitive to those familiar with Sass. When I saw `scss` as the platform I assumed that I could rename it to `sass` to get `.sass` syntax.

```json
{
  "platforms": {
    "scss": {
      "transformGroup": "scss",
      "buildPath": "build/scss/",
      "files": [{
        "destination": "_variables.scss",
        "format": "sass/map-flat"
      }]
    }
  }
}
```

The first thing I tried was renaming everything to `sass` to see if I could get `.sass` output:

```json
{
  "platforms": {
    "sass": {
      "transformGroup": "sass",
      "buildPath": "build/sass/",
      "files": [{
        "destination": "_variables.sass",
        "format": "sass/variables"
      }]
    }
  }
}
```
I think that's a fairly natural thing to try, before going to the docs.

**Comment by dbanksdesign** [comment]
Thank you for your detailed description, it is very helpful. 

I agree some of our documentation and naming can be cleaned up a bit. Would it make sense in the examples to use "web" as the transformGroup and "web" as the platform name? "Platforms" in a Style Dictionary config are just a way to group build configuration (transforms, files to be built, build path, etc.). A platform could be named anything like "web", "android", or even things like "sketch" or "NPM", it is up to the user to create and name their platforms. The name of the platform has no effect on the output. 

A transformGroup is a group of transforms to make it easier to re-use, Style Dictionary provides some built in [transforms](https://amzn.github.io/style-dictionary/#/transforms) and [transformGroups](https://amzn.github.io/style-dictionary/#/transform_groups). If there isn't one that is already built in, you can write you own.

I did some digging, and I honestly cannot find how to write a "sass" map (not "scss"), I can't find it in any of the documentation. Could you help out with writing sass map formats?

**Comment by TheJaredWilcurt** [comment]
For `.sass` / `.scss` the easiest thing to do is use https://SassMeister.com to convert from one to the other. Though the auto conversion isn't always as pretty as what someone would write by hand.

* * *

Would be nice to have an "anatomy of config" or something like this:

```js
{
  // The source dictionary files. This would find all JSON files in any subdirectory of properties
  "source": ["properties/**/*.json"],
  // The platforms you want to target
  "platforms": {
    // Name of your platform can be anything you want. Common names: android, ios, web, desktop, sass
    "web": {
      // Check documentation for list of pre-defined transformGroups (css, js, scss, android, etc.)
      "transformGroup": "scss",
      // The output directory for this platform, any location you want
      "buildPath": "build/scss/",
      // You can output multiple files, each with their own format/settings
      "files": [{
         // This destination file will be placed in this platform's buildPath
        "destination": "_variables.scss",
        // Check documentation for list of pre-defined formats (scss/variables, javascript/module, etc.)
        "format": "scss/variables"
      }]
    }
  }
}
```

But prettier (not as grayed out comments since the explanation is the important part), and place it at the top of the Quick Start page after the `init basic`.  The Quick Start page is way too long and covers tons of information I don't care about. It needs to be slimmed down to smaller chunks of just the most important key information you need to know when first trying it out.

* * *

1. Make a new folder and navigate to it in a command prompt/terminal
1. `npm init -y`
   * You should now have a `package.json` file in the folder
1. `npm install --save-dev style-dictionary`
   * This will install style-dictionary locally in this project as a devDependency
1. `npx style-dictionary init basic`
   * This will copy files to the root of your project.
   * `npx` comes with newer versions of `npm`, if you don't have `npx`, run `npm install -g npx`, then rerun the above command
1. `npx style-dictionary build`
   * This will run the build command based on the settings in `config.json`
   * You can create an npm script for it, like `"build": "style-dictionary build"` so you can do `npm run build`
   * You can also do `npx style-dictionary clean` to delete the built files
1. There is a `config.json` and a `properties` folder with source files for you to play with. Here is how the config file is structured:
   * put the above code block with comment explanations here
1. The structure of the files in the `properties` folder is ...........

Links to sections you should checkout next:

* all
* the
* crap
* on
* quick
* start
* currently
* but
* on
* a
* new
* page

**Comment by TheJaredWilcurt** [comment]
To reiterate, what you have on the Quick Start guide is good for beginners who are new to development.  It's very detailed and covers everything so they can't get lost. What I want is more of the TLDR version (seen as the short 7 steps). I think most devs would prefer this, because if you are setting up a cross-platform shared styles architecture in your project, you are probably not a beginner, and would prefer the quicker steps and to only see the details that are relevant to you by clicking on that section from the links at the bottom.

**Comment by didoo** [comment]
@TheJaredWilcurt I understand your concerns about the double sass/scss reference in the codebase (and probably documentation). I was the one that [added the `sass/map-xxx` formats](https://github.com/amzn/style-dictionary/pull/193), so totally my fault. I'll create a PR to rename them correctly, if @dbanksdesign is OK with using `scss/map-xxx` for them.

That said, we should also consider that the "indented" syntax is considered "old" even by the official Sass documentation:

> There are two syntaxes available for Sass. The first, known as SCSS (Sassy CSS) and **used throughout this reference**, is an extension of the syntax of CSS. [...] Files using this syntax have the .scss extension.
> The second and **older** syntax, known as the indented syntax (or sometimes just "Sass"), provides a more concise way of writing CSS. [...] Files using this syntax have the .sass extension.

I think nowadays has become quite common to refer to Sass as the way to write .scss files. So I think it would be better to keep this formats, and leave the "old sass" syntax to the developers to implement, if needed, as custom formats.

**Comment by dbanksdesign** [comment]
Thank you for your feedback @TheJaredWilcurt on the quick start guide. I'll see how I can incorporate that feedback into the documentation. 

@didoo I Agree, I have not worked on a project in the past 5 or so years that used the older Sass syntax. To be honest, I tried really quick to write a map in the old Sass syntax and could not figure out how to do it reading through the Sass docs. :/

**Comment by TheJaredWilcurt** [comment]
I think you are misunderstanding something *existing longer* as being *outdated*. The `.sass` syntax was first, and has been kept up-to-date with every single release. There is complete parity with it, and it's less powerful offshoot `.scss`.

* https://github.com/TheJaredWilcurt/tjw-sasslint-rules#proscons-of-sass-vs-scss-vs-css

I've been using `.sass` syntax on most of the projects I've worked on in the last 5 years (including at jobs). I've yet to find anyone that tried it for 2 weeks and didn't find it better than `.scss`. SCSS is great when you are first learning, but `.sass` is just better for the stuff you spend 90% of your time doing in the language. There are some rare cases where `.scss` is better, but you can create one-off files for those scenarios.

`.sass` usage is actually on the rise, we're seeing improvements to it's usability being added to tools like JSFiddle (recently added it due to high demand), CodeSandbox, VSCode, etc.

If you are already familiar with SCSS and would like to upgrade your skills, then the easiest route is to use [SassMeister.com](https://sassmeister.com). The drop down can switch between the syntax's and will auto-convert for you.

>I think nowadays has become quite common to refer to Sass as the way to write .scss files

I don't think purposefully misusing words will improve clarity.

**Comment by dbanksdesign** [comment]
Apologies for the delay on this, the PR to fix the issues should be ready to go, and will go out in the next release.
