### ISSUE TITLE
config's "Include" and "source" properties behave differently.

### ISSUE THREAD

**Issue by rjoaopereira** [amzn/style-dictionary#215]
Not sure if this is intended but it leads to confusion.

`include` expects an array of paths but which cannot be globs.
https://github.com/amzn/style-dictionary/blob/master/lib/extend.js#L106

`source` expects an array of paths which can be globs.
https://github.com/amzn/style-dictionary/blob/master/lib/extend.js#L119

I believe it would be benificial to have the same behaviour. I came across this when promoting some properties to be base properties under include.

**Comment by dbanksdesign** [comment]
You are totally right... I wrote that code and I don't know what I was thinking. I honestly thought before looking at the code just now that they did behave the same, but I guess I am wrong. I'll work on a PR later today to get that fixed.

**Comment by rjoaopereira** [comment]
Thank you for your quick reply and for your work.

**Comment by rjoaopereira** [comment]
No worries, this is not an impediment at all. Just opened the issue for consistency.
I'm the one who is thankful 😄

**Comment by dbanksdesign** [comment]
Quick question, because you opened the conventional commits, do you think this is a bug or a feature?

**Comment by rjoaopereira** [comment]
I can't find anywhere in the docs or README that include can be used with globs. Only `An array of paths to Style Dictionary property files that contain default styles`. I would go with feature.

**Comment by rjoaopereira** [comment]
`source` on the other hand, and although not a strict reference, has `"source": ["properties/**/*.json"],` in the docs.

**Comment by dbanksdesign** [comment]
I figured it out: #227

**Comment by rjoaopereira** [comment]
Awesome, thanks!

**Comment by chazzmoney** [comment]
Fixed in v2.7.0
