### ISSUE TITLE
Link to examples in the Readme is 404

### ISSUE THREAD

**Issue by custa1200** [amzn/style-dictionary#220]
When I click to view the examples from the projects GitHub readme I get a 404

**Comment by didoo** [comment]
Thank you @custa1200 for catching it, a silly error by me (I renamed the folder in a previous ticket).
Here is the PR: https://github.com/amzn/style-dictionary/pull/221

**Comment by dbanksdesign** [comment]
I just merged this into master, the docs should be updated now. Thank you for your help!
