### ISSUE TITLE
No Changelog

### ISSUE THREAD

**Issue by rjoaopereira** [amzn/style-dictionary#224]
Thank for this library. I would like to make a request for a `CHANGELOG`. The file exists but it is empty.

A way to achieve this without too much hassle is by using [conventional commits](https://www.conventionalcommits.org/en/v1.0.0-beta.2/) and [conventional changelog](https://github.com/conventional-changelog/standard-version) but this is just a suggestion.

**Comment by dbanksdesign** [comment]
YES! This has been on the back of my mind for a while but never got around to doing it. Auto-generating and releasing versions has been a sore spot. How does conventional commits work with branching? Right now we have a develop branch and then merge into master, honestly a bit ad hoc, whenever we want to do a minor/major release. We commit directly to master if it is changing docs or patch commits. Would we instead change to getting rid of develop and always committing on master? Are there any good articles to read on this subject?

**Comment by rjoaopereira** [comment]
`How does conventional commits work with branching?`

Doesn't change it but I would recommend checking [git flow](https://datasift.github.io/gitflow/IntroducingGitFlow.html) and having 1 commit per PR (use rebase with squash + fixup)

[A quick search on the subject](http://devboosts.com/2017/03/28/conventional-commits/)

**Comment by chazzmoney** [comment]
Added via #225 , thanks @rjoaopereira !
