### ISSUE TITLE
Build tokens from an array in a json file

### ISSUE THREAD

**Issue by luisjmontoro** [amzn/style-dictionary#229]
Hello!! We are a team of designers and we are delighted by this tool :) 

We are trying to build our DS and we have come to the idea of using arrays when defining our values in the properties. The thing is that the build fails and I'm wondering if there's any possibility to do this... 

This is an example of it:

```
{
  "color": [{
      "brand": [{
        "primary": [{
          "base": { "value": "#DA291B" }
        }, {
          "darken": { "value": "#B8271E" }
        }, {
          "lighten": { "value": "#F9423A" }
        }]
      }, {
        "secondary": [{
          "base": { "value": "#747D8C" }
        }, {
          "darken": { "value": "#2F3542" }
        }, {
          "lighten": { "value": "#A4B0BE" }
        }]
      }, {
        "tertiary": [{
          "base": { "value": "#F39C11" }
        }, {
          "darken": { "value": "#E67E22" }
        }, {
          "lighten": { "value": "#F1C30F" }
        }]
      }, {
        "quaternary": [{
          "base": { "value": "#53565A" }
        }, {
          "darken": { "value": "#3D3F42" }
        }, {
          "lighten": { "value": "#D0D0CE" }
        }]
      }]
    }
}
```

The idea behind this thought is to have the possibility to add new values and keep using our automation process to generate styles and also Sketch files from the properties.

Thank you so much!

**Comment by didoo** [comment]
Hi @luisjmontoro 
I'm not sure what you're trying to achieve. What is the expected output in this case? For example, if you need to generate Scss files, what do you want to see once processed the JSON above? It's not clear for me the difference (and benefits) between:

```
{
  "color": [{
      "brand": [{
        "primary": [{
          "base": { "value": "#DA291B" }
        }, {
          "darken": { "value": "#B8271E" }
        }, {
          "lighten": { "value": "#F9423A" }
        }]
      },
```

and

```
{
  "color": {
      "brand": {
        "primary": {
          "base": { "value": "#DA291B" }
        }, {
          "darken": { "value": "#B8271E" }
        }, {
          "lighten": { "value": "#F9423A" }
        }
      },
```
Thank you

**Comment by luisjmontoro** [comment]
Thank you for the answer @chazzmoney ! 
I will let you now as soon as we try it!

:)

**Comment by chazzmoney** [comment]
Closing this for now, let me know if you need more help.

**Comment by vjandrei** [comment]
I had similar question about can I use array
`"typography": {
        "h1": {
            "font-size": {
                "value": 14
            },
            "weight": {
                "value": 8
            },
            "letter-spacing": {
                "value": null
            },
            "line-height": {
                "value": 16
            }
        },
        "h2": {
            "font-size": {
                "value": 20
            },
            "weight": {
                "value": 8
            },
            "letter-spacing": {
                "value": null
            },
            "line-height": {
                "value": 24
            }
        },`

What I liked to achieve is loop that makes each heading element multiple property values like 

`<h1 style="font-size:14px; font-weight:8px"></h1> <h2 style="....">`
