### ISSUE TITLE
"name" is a reserved property.

### ISSUE THREAD

**Issue by rjoaopereira** [amzn/style-dictionary#230]
While trying to add a "meta" property parallel to `value` named `name` I was greeted to the full name of the token and not the value I placed there.

e.g.
```json
{
    "a": {
        "b": {
            "c": {
                "value": "1",
                "name": "ds"
            }
        }
    },
    "d": {
        "e": {
            "f": {
                "value": "{a.b.c.name}"
            }
        }
    }
}

```
tokens:
```{
    "a-b-c": "1",
    "d-e-f": "a-b-c"
}
```

My use case:

declaration 
```js
const path = require("path");
module.exports = {
    asset: {
        font: {
            "primary": {
                value: path.resolve(
                    __dirname,
                    "path/to/font"
                ),
                name: "Font-name",
                "content-type": "application/x-font-woff",
                charset: "utf-8",
                format: "woff"
            }
        }
    }
};
```
referencing
```js
module.exports = {
    font: {
        family: {
            primary: { value: '{asset.font.primary.name}, sans-serif' }
        }
    }
}
```
replacing `name`with something else works.

**Comment by dbanksdesign** [comment]
What transforms are you using?

`name` is a special key, just like `value`. Transforms can modify the `name` attribute as well as the `value` and `attributes`. If you are using a name transform it will override whatever you include as the name. If you provide a name like you are doing above it should remain there if you aren't using any name transforms.

**Comment by rjoaopereira** [comment]
Thanks for clarifying 👍 . I am using `name/cti/kebab`.
I would like to suggest though, maube for 3.0, to make usage of `Symbols` to store the transformed data.

[This](https://www.keithcirkel.co.uk/metaprogramming-in-es6-symbols/) is a pretty good post on how and why to use them.

**Comment by dbanksdesign** [comment]
Woah I have never heard of Symbols. That is really interesting. So in general terms, we never mutate the actual values of `value` and `name`, and instead create new keys on the object with `Symbol('name')` and `Symbol('value')` and then reference those in the formats? That would be pretty nice. One thing I forgot to mention also, is before any transforms are applied, Style Dictionary clones the whole property object into an object with `original` as the key. H[ere is the code that does that](https://github.com/amzn/style-dictionary/blob/master/lib/transform/propertySetup.js). So if you supply a name, it will also always be in `original`. I guess using Symbols would negate the need for that.

**Comment by rjoaopereira** [comment]
`in general terms, we never mutate the actual values of value and name, and instead create new keys on the object with Symbol('name') and Symbol('value') and then reference those in the formats?`

That would be the idea.

`So if you supply a name, it will also always be in original`

It's good to know but I prefer to use another key. You never know when the inner workings will change.

` I guess using Symbols would negate the need for that.`

I believe so.
