### ISSUE TITLE
Architecture: transforms' matchers assume specific CTI 

### ISSUE THREAD

**Issue by rjoaopereira** [amzn/style-dictionary#231]
I believe it benefitial to separate matchers from transformers.

```js
  'asset/base64': {
    type: 'value',
    matcher: function(prop) {
      return prop.attributes.category === 'asset';
    },
    transformer: function(prop) {
      return convertToBase64(prop.value);
    }
  },
```

using this transform assumes we are using a structure like

```json
{
   "category": {
        "property": {
            "value": "convert me"
        }
   }
}
```

providing the matcher would make the transform more generic

**Comment by dbanksdesign** [comment]
I see your point. My concern would be adding complexity to users. A transform can only work if it has both a matcher to know which properties to transform, and a transformer to do the transforming. If we split the transformer and matcher, the user would then have to merge the 2 somehow to get a finished transform. 

What is possible if you want to use the transformer function with a different matcher function, is in JS you can access it and use it however you like. All transforms, transformGroups, and formats are easily accessible in the StyleDictionary object through the keys, `transform`, `transformGroup`, and `format` respectively.

```javascript
const StyleDictionary = require('style-dictionary');
const myStyleDictionary = StyleDictionary.extend( /* config */ );

// This will override the 'asset/base64' transform with a custom
// matcher function, but the original transformer function
myStyleDictionary.registerTransform({
  name: 'asset/base64',
  type: 'value',
  matcher: (prop) => /* custom matcher */
  transformer: StyleDictionary.transform['asset/base64'].transformer
});
```

Does that help? Also, I have a PR open to add a more advanced node example( #228 ). In it you can see more powerful ways to extend/add transforms and formats that allow someone to write "plugins" for Style Dictionary that add transforms and formats or modify built-in ones.

**Comment by rjoaopereira** [comment]
This makes it much easier! I've already checked a little of the PR and will see some more tomorrow.
As always, thank you for your work and time 👍
