### ISSUE TITLE
Unclear doc about javascript configuration with CLI tool

### ISSUE THREAD

**Issue by gael-boyenval** [amzn/style-dictionary#238]
The doc is a bit unclear about the ability to use javascript file instead of JSON with CLI tool. 

> By default, Style Dictionary looks for a config.json file in the root of your package. You can also specify a custom location when you use the CLI. If you want a custom build system using the npm module, you can specify a custom location for a configuration file or use a plain Javascript object.

reading the doc, it imply that we may only use JS config with the nom module.
but in fact, using JS file seem to work properly using cli tool as well. Here my CLI command :

```
npx style-dictionary build --config ./src/tokens/config.js
```

**Comment by dbanksdesign** [comment]
Good catch. We added javascript module support for config files and didn't update all of the documentation. If you would like, feel free to open a PR to update the documentation.

P.S. Nice use of npx!

**Comment by gael-boyenval** [comment]
@dbanksdesign, I would like to, but I need some context : 

By default, will style-dictionary look for either a config.js or config.json file ?
Support for the plain javascript object file path is supported by either CLI arg and NPM ?

I would love to update the doc, but I don't want to dive too deep into the code right now. I have limited available time. :)

**Comment by dbanksdesign** [comment]
No worries! I can also update the documentation if I get some time this week. By default the style dictionary CLI will only look for config.json:
https://github.com/amzn/style-dictionary/blob/master/bin/style-dictionary#L62

Although, I feel like it would make sense to look for both config.js and config.json by default, so maybe we should change that...

And javascript object is supported by both CLI and NPM. Really the CLI is a pretty basic wrapper around the NPM module. The NPM module accepts a string, which can be a path to anything that `require` understands like a javascript file with `module.exports = {}` or a plain JSON file. The NPM module can also accept a plain object as well:

```javascript
const StyleDictionary = require('style-dictionary').extend({
  source: ['properties/*.json'],
  platforms: {
    scss: {
      transformGroup: 'scss',
      buildPath: 'build/',
      files: [{
        destination: 'variables.scss',
        format: 'scss/variables'
      }]
    }
    // ...
  }
});
```

**Comment by gael-boyenval** [comment]
@dbanksdesign thank's

**Comment by chazzmoney** [comment]
Created a PR, #247
