### ISSUE TITLE
Add an advanced example with the gist shared by Dbanksdesign about CTI structure

### ISSUE THREAD

**Issue by didoo** [amzn/style-dictionary#246]
In a thread on Slack @dbanksdesign shared this gist:
https://gist.github.com/dbanksdesign/dd67b7c265b75089c03d969dceaa41f1

It may be an interesting example to add to the "advanced" examples. What do you think?

**Comment by davixyz** [comment]
I would love to do this; It's actually what I'm using at work thanks to @dbanksdesign.
Here's my project:
https://github.com/davixyz/design-tokens

I might be adding something similar to this

**Comment by chazzmoney** [comment]
In progress, #267 by @dbanksdesign 

Will close this once merged.
