### ISSUE TITLE
Sketch named colours

### ISSUE THREAD

**Issue by custa1200** [amzn/style-dictionary#254]
As of Sketch 53 we can now name colours. Would be cool to be able to name them in SD and the naming output and consumed by Sketch in the Sketch palette.

**Comment by dbanksdesign** [comment]
This would be awesome! Can you send any documentation on this?

**Comment by custa1200** [comment]
https://github.com/BohemianCoding/SketchAPI/issues/397

**Comment by custa1200** [comment]
I can't see anything in their API at first glance @dbanksdesign so I have reached out to them for clarification.

**Comment by custa1200** [comment]
actually they answered on that ticket they closed. :)

**Comment by didoo** [comment]
I has started to look into it a few days ago. If you want I can take this.

**Comment by custa1200** [comment]
I actually tried to use the palettes generated by SD (this made me so exited this week generating them) using the following plugin in Sketch v53 and It didn't seem to import them. :(

https://github.com/andrewfiorillo/sketch-palettes

**Comment by chazzmoney** [comment]
Stealing the [comment from them](https://github.com/BohemianCoding/SketchAPI/issues/397#issuecomment-468669148) just in case:

In Sketch 53.1, there are a `document.colors` and `document.gradients` properties: https://github.com/BohemianCoding/SketchAPI/blob/develop/docs/api/Document.md

And in Sketch 54, there will be `sketch.globaleAssets.colors` and `sketch.globalAssets.gradients`.

**Comment by dbanksdesign** [comment]
@custa1200 take a look at #287 for fixing the sketch palette format.

**Comment by dbanksdesign** [comment]
Fixed this in #287
