### ISSUE TITLE
Use javascript object input for "source" field

### ISSUE THREAD

**Issue by goldhand** [amzn/style-dictionary#259]
I would like to use a javascript object for properties input.

### Reason
I'm want to return this object in a service and allow other consumers to process it further using this library.

### Example API
```js
const styles = { "color": { "base": { "gray": { "light": { "value": "#cccccc", "original": { "value": "#CCCCCC" } } } } } };

const processedStyles = require('style-dictionary').extend({
  source: [styles],
  platforms: {
    // ...
  }
}).exportPlatform('web');

processedStyles.color.base.gray.light.value === styles.color.base.gray.light.value;
// > true

```

**Comment by dbanksdesign** [comment]
You definitely can! What you can do is pass in the object in a `properties` attribute:

```javascript
const styles = { "color": { "base": { "gray": { "light": { "value": "#cccccc", "original": { "value": "#CCCCCC" } } } } } };

const processedStyles = require('style-dictionary').extend({
  properties: styles,
  platforms: {
    // ...
  }
}).exportPlatform('web');
processedStyles.color.base.gray.light.value === styles.color.base.gray.light.value;
// > true
```

Also, if you want to pass your style dictionary to other consumers to use you can pass the return of the `.extend()` method. The reason the above works and you can pass `processedStyles` is that the [extend method](https://github.com/amzn/style-dictionary/blob/master/lib/extend.js#L99) merges the object passed to it on itself and returns it. The `properties` attribute is used internally where it puts the object structure of the merged files in `source` and `include`. This way you can have a base style dictionary which you can pass to other consumers who can then add their own properties, transforms, config, etc.

**Comment by dbanksdesign** [comment]
One gotcha: remove the `original` object in your styles object. Style Dictionary adds that internally when it goes over the properties object and transforms the tokens, if it sees an `original` object it skips it.

**Comment by goldhand** [comment]
Thanks @dbanksdesign :)

I must have missed that in the docs, my mistake.
