### ISSUE TITLE
404 on amzn.github.io/style-dictionary/#/README

### ISSUE THREAD

**Issue by ventrebleu** [amzn/style-dictionary#263]
Hi there!

When browsing the doc site, when you click back to Overview on the left panel, you get a 404.
<img width="670" alt="Screen Shot 2019-04-18 at 10 11 00 AM" src="https://user-images.githubusercontent.com/2122637/56378753-d36a0080-61c2-11e9-9f77-14f7dec3d11a.png">

**Comment by dbanksdesign** [comment]
Super weird, might be an issue with the doc site library we are using, docsify. If you get that 404 and just refresh, the page loads.. I'll poke around a bit

**Comment by chazzmoney** [comment]
I've been playing with this some. It seems like the UI reports 404 but the only 404 occurring in the browser is for the code-coverage badge:

https://img.shields.io/codeclimate/github/amzn/s tyle-dictionary.svg?style=flat-square

I went to code climate to try to fix this but it says I don't have permissions on the account. Might be a good place to start.

**Comment by chazzmoney** [comment]
On further research, it seems like clicking around on any of the top-level items in the "Getting Started" section can end up giving you that 404 screen. I do not see a way to reproduce besides just click. Does not seem related to the 404 for the badge.

**Comment by chazzmoney** [comment]
More research. The 404 view is generated by [docsify directly](https://github.com/docsifyjs/docsify/blob/develop/src/core/render/index.js#L44). It corresponds to docsify.min.js:formatted line 2052.

Am attempting to traceback the call stack to see where it is failing to generate the html.

**Comment by chazzmoney** [comment]
Some of the behavior changed after fixing the HTTP 404 on badges, so it is more solid now. The error still occurs however - but the minor behavior change enabled me to find a solid method to recreate. On the 3rd load of any top level link it shows the Docsify 404 page.

When you load the page, overview loads for the first time. Click to any other page (e.g. Examples). Click back on 'Overview' - loads fine for the 2nd time. Click to any other page again - loads fine. Click back on 'Overview' for the 3rd time - Docsify 404.

This happens on any 3rd load of any top level page.

**Comment by chazzmoney** [comment]
This is still the current state.

With #309 on the way, is this worth fixing? I think no - lets close.
