### ISSUE TITLE
Badges

### ISSUE THREAD

**Issue by chazzmoney** [amzn/style-dictionary#265]
We should consider adding some new badges maybe?

[![downloads](https://img.shields.io/npm/dm/style-dictionary.svg)](https://www.npmjs.com/package/style-dictionary)
[![PRs welcome](https://img.shields.io/badge/PRs-welcome-brightgreen.svg?style=flat-square)](https://github.com/amzn/style-dictionary/blob/master/CONTRIBUTING.md#submitting-pull-requests)

**Comment by chazzmoney** [comment]
The code coverage badge is 404 currently. We are using:

https://img.shields.io/codeclimate/github/amzn/style-dictionary.svg?style=flat-square

I think the badge url is now supposed to be:

https://img.shields.io/codeclimate/coverage/amzn/style-dictionary.svg

I think that code climate is not currently working. I tried to fix this but it says I don't have permissions on the account.

**Comment by dbanksdesign** [comment]
Let's do it!
