### ISSUE TITLE
Javascript Themable Format

### ISSUE THREAD

**Issue by thiagofelix** [amzn/style-dictionary#278]
What do you think about the idea of a custom format that gives you one javascript function that takes some overrides properties as arguments and return the full parameters set updated?

Simple example:

**properties/default.json**
```
{
  "color": {
    "base": {
      "product": {
        "normal": { "value": "#00a991" }
      }
    },
    "background": {
      "button": {
        "primary": { "value": "{color.base.product.normal.value}" }
      }
    }
  }
}
```

**config.json**
```
{
  "source": [
    "properties/default.json"
  ],
  "platforms": {
    "themable": {
      "transformGroup": "js",
      "transforms": [
        "name/cti/camel"
      ],
      "files": [
        {
          "destination": `build/getTokens.js`,
          "format": "javascript/themable"
        }        
      ]
    }
  }
}
```

**generated build/getTokens.js**
```
export default function getTokens(tokens = {}) {
  return {
    colorBaseProductNormal: tokens.colorBaseProductNormal || defaultTheme.colorBaseProductNormal,
    colorBackgroundButtonPrimary: tokens.colorBackgroundButtonPrimary || tokens.colorBaseProductNormal || defaultTheme.colorBackgroundButtonPrimary,
  }
}
```

In this example the function `getTokens` receive set of new tokens overrides which will update the properties of the resulting value. The references from properties are kept as they should, so if one sends new value `colorBaseProductNormal` property, it would also change the `colorBackgroundButtonPrimary` which references it.

The end goal of this function is to be able to toggle the tokens at runtime.

I am curious to hear if you find this a valid use case.

Tks

**Comment by chazzmoney** [comment]
Hi @thiagofelix!

This sounds like a valid use case for you. A lot of people are looking for functionality related to theming for sure.

There is also interest in outputting the variable references themselves (#17), which I think might solve your problem if implemented.

The hard part is to define the line between what should be built as a part of the core library and what should be created as a custom format...

Take a look at #17 and the [issues associated with themes](https://github.com/amzn/style-dictionary/issues?q=is%3Aissue+theme+is%3Aopen) us know your thoughts!

**Comment by thiagofelix** [comment]
Tks @chazzmoney, I agree with you, it is not something that should be part of the library surely. I guess I was looking for validation if that is a valid usage of custom formats. 

After some time playing with style-dictionary and design-tokens in general I understand there is no much of right/wrong, given tokens are quite generic and platform agnostic each team can decide what/how they want to use then, right?

Still on the custom formats topic, but slight different idea, do you think using the CTI pattern to generate some higher level assets are worth doing? My idea was to create a [Sketch Library](https://www.sketch.com/docs/libraries/) with all background/border color and sizes permutations based on CTI pattern. 

So essentially everyone following CTI on the tokens would get this for free, still something not part of the library but perhaps more generic/usable for others too.
