### ISSUE TITLE
Update JSDoc param names to match argument names

### ISSUE THREAD

**Issue by dbanksdesign** [amzn/style-dictionary#281]
In most of our documented functions the argument name(s) don't match the JSDoc param name(s). For example:

https://github.com/amzn/style-dictionary/blob/master/lib/extend.js#L63

JSDoc param name: 'config'
Argument name: 'opts'

**Comment by chazzmoney** [comment]
🤣 I love that we haven't noticed this until now. 🙄

**Comment by jamieshark** [comment]
@dbanksdesign - I can try to handle this!

**Comment by dbanksdesign** [comment]
I would say `action` param because it is unique and specific to the method. Using general names like `options` or `args` is not very semantic. But I'm open to opinions!
