### ISSUE TITLE
Sketch color palette

### ISSUE THREAD

**Issue by MarjorieSIX** [amzn/style-dictionary#285]
Hello,
I don't think I have an issue per say, but I'm having a hard time creating the sketch color palette via the transform function sketch/palette.
My scss works fine, Android and IOS too.
But as for the sketch palette, it creates an empty file with just
```
{
  "compatibleVersion": "1.0",
  "pluginVersion": "1.1",
  "colors": []
}
```
If there's another place I can ask, please forward me :-D

Thanks for your help,
M.

**Comment by dbanksdesign** [comment]
The 'sketch/palette' format filters tokens that have

```json
{
  attribute: {
    category: 'color',
    type: 'base'
  }
}
```

Here is the source: https://github.com/amzn/style-dictionary/blob/master/lib/common/formats.js#L710

We recently-ish added 'filters' for you to filter your tokens before formatting them, so we should remove that filter in the format itself. In the meantime, if your tokens have those attributes (category === 'color' and type === 'base') it will work then. You can do this either by adding an attribute object on your tokens directly with those properties, or set up your tokens to be like this:

```json
{
  "color": {
    "base": {
      "white": {
        //...
```

So the fix would be to remove the `.filter` code in the 'sketch/palette` format, and that is actually it. Once we do that, you will need to make sure to add a 'filter' in your file config to filter only the color tokens or you might get some weirdness.

**Comment by dbanksdesign** [comment]
A bit of a bigger issue, when trying out sketch palettes, I had an old version of the plugin so I needed to update it. The plugin is now a major version above (2.2 vs. 1.1), which has an impact on the format because now the .sketchpalette file takes a slightly different form.
