### ISSUE TITLE
Update docs to include filters

### ISSUE THREAD

**Issue by dbanksdesign** [amzn/style-dictionary#286]
The `.registerFilter` function is documented in the API, but we don't really explain the concept of filtering in the docs very well.

**Comment by gearsandcode** [comment]
I've been trying to get this to work for an hour or so now. I'm not sure how to use it based on the docs.

Is it:
```
"platforms": {
    "web/scss": {
            "transformGroup": "tokens-scss",
            "buildPath": `dist/${brand}/web/`,
            **"filter": "filter-here",**
            "prefix": "",
            "files": [
                {
                    "destination": `scss/${category}-tokens.scss`,
                    "format": "scss/variables",
                    **"filter": "or-filter-here"**
                }
            ]
        }
}...

StyleDictionaryPackage.registerFilter({
    name: 'filter-alias',
    matcher: function(prop) {
        return prop.attributes.type !== 'alias';
    }
})
```

**Comment by dbanksdesign** [comment]
It is the second one. Also super cool use of interpolated strings in your config!

**Comment by gearsandcode** [comment]
I couldn’t get this to work. I had to use the original syntax before registerFilter was introduced. That syntax doesn’t allow for a negative match, so I ended up having to add a value for inclusion vs. exclusion. That’s not really ideal.

I also couldn’t get “scss/icons” to work. I’m not sure what my token file needs to look like. I tried “F101”, “/F101”, “//F101” and the html escaped version like I found in a token file in one of the examples, but it didn’t work. If you’d like I can open new tickets for both of these and once I get them resolved I can tackle the updated docs ticket that is open with a PR. I just need some help getting things working first. Thanks for the quick response!

**Comment by dbanksdesign** [comment]
Yea that would be great if you could open 2 issues. In the filter one can you post your full code for that file, and any errors you are getting? Thanks!

**Comment by chazzmoney** [comment]
@gearsandcode Just checking in - if you could open tickets for these that would be super useful for us to start investigation and commentary on them. No PRs required! :-D

I can open them as well, but would prefer if you did it as you will represent your issues better.

**Comment by dbanksdesign** [comment]
Closing this as we have 2 new issues tracking this.
