### ISSUE TITLE
How can we add Flutter support

### ISSUE THREAD

**Issue by valiksb** [amzn/style-dictionary#288]
We are developing in Flutter and our designer works in Sketch and started using style-dictionary but we dont see a Flutter transformer.

We were wondering if there is enough interesting for a Flutter transformer and what are the required steps

**Comment by dbanksdesign** [comment]
I think Flutter would be great to have! You can take a look at [this pull request](https://github.com/amzn/style-dictionary/pull/255) about adding Swift support for inspiration on how to build in flutter support.

**Comment by MDemetrio** [comment]
I added flutter support on our internal tool that uses style-dictionary's npm module, it was based on swift implementation.

Can I try to send a PR?

**Comment by dbanksdesign** [comment]
@MDemetrio absolutely!

**Comment by chazzmoney** [comment]
Let us know if you need help pulling the PR together - we would love to have your contribution!
