### ISSUE TITLE
Create demo video

### ISSUE THREAD

**Issue by dbanksdesign** [amzn/style-dictionary#3]
Quick timeline (2 minutes max):

* "Hi, I'm Danny, let me show you what style dictionary does for you"
* "here we can see the app I've built. here it is in iOS. And Android. And here is our style documentation."
* "Okay, now you've seen the app. Say that I've now decided that I want to change the default text to 16 point for readability." (make the change)
* "we've also decided to go with an orange theme instead of blue." (make the change)
* "I'm also adding a new font type for validation errors in forms" (add it)
* "Now I save the style dictionary. Everything rebuilds."
* "Lets go look at our app. here is iOS. Here is android. And here is our style documentation."

**Comment by chazzmoney** [comment]
Working on getting a video specialist person...

**Comment by chazzmoney** [comment]
Meeting with internal video production folks on June 1st.  Do we need to add a video before then?

**Comment by chazzmoney** [comment]
Call w/ Justin on July 5th.

**Comment by dbanksdesign** [comment]
Video is up: https://www.youtube.com/watch?v=1HREvonfqhY
