### ISSUE TITLE
Set up github pages for this repo

### ISSUE THREAD

**Issue by chazzmoney** [amzn/style-dictionary#30]
So we have a place for people to land besides "here are the files"

**Comment by chazzmoney** [comment]
Maybe move the stuff from the wiki?

**Comment by dbanksdesign** [comment]
Researching some things to make pretty docs:
https://docsify.js.org

**Comment by chazzmoney** [comment]
Have a basic setup running now.  Maybe we should consider doing the docpress implementation?  Seems the most clear.

**Comment by chazzmoney** [comment]
So should we aim to add in one of those or just leave it as is for now?

**Comment by dbanksdesign** [comment]
Closing this with the latest merge, documentation is live!

https://amzn.github.io/style-dictionary/#/
