### ISSUE TITLE
Convert Lodash to ES6 / custom utility classes?

### ISSUE THREAD

**Issue by chazzmoney** [amzn/style-dictionary#302]
We use lodash for a lot of _.map and _.each kinda stuff that we could replace with ES6 classes. Also, facing issue right now using the _.kebabCase; we might want to write our own utility classes to replace these.

Removing lodash as a dependency may have other impacts, both positive and negative. Starting the conversation.

**Comment by dbanksdesign** [comment]
The things we use lodash for right now:
* Things ES6 can do like array mapping/filtering
* Templates, which we use internally to create formats. 
* String manipulation for name transforms, like `_.kebabCase`

The ES6 stuff is easy to change and would have no customer impact. Templates might have some customer impact if people are using lodash templates to create custom formats, but not including 'lodash' in their package.json dependencies directly (I am guilty of this sometimes). Replacing our template code would be a larger undertaking and I don't know if it would be worth it. String manipulation would have a positive customer impact at least to solve #300, but would need some rigorous testing to make sure there are no regressions.

**Comment by pnkapadia64** [comment]
@dbanksdesign @mexitek Is there a usage of lodash utils that still remains to be removed? I could pick something up.

**Comment by mexitek** [comment]
> @dbanksdesign @mexitek Is there a usage of lodash utils that still remains to be removed? I could pick something up.

There are still a few. You can do a quick search for `_.` to find all usages of lodash. With that said, `_.template(...)` is the most complex to get rid of. Lets aim to remove all other usages before `_.template(...)`.

**Comment by chazzmoney** [comment]
This is in 3.0, with the exception of _.template, which will be tracked in a new issue
