### ISSUE TITLE
JS module format issue 

### ISSUE THREAD

**Issue by cailborg** [amzn/style-dictionary#310]
Hi there, would love to get some help with a specific problem, i'm sure i'm misunderstanding something.

Basically I want to output a list of tokens in a javascript/module format but have the structure appear flat with none of the extra properties (value, original, name, attributes, path)

Ideally it would look similar to the json/nested output of colorName: ColorValue

Is this something that can be achieved out of the box or do I need a custom format?

What I have:
```
module.exports = {
  "color": {
    "amethyst": {
      "base": {
        "value": "#5d45cd",
        "original": {
          "value": "#5D45CD"
        },
        "name": "amethystBase",
        "attributes": {
          "category": "color",
          "type": "amethyst",
          "item": "base"
        },
        "path": [
          "color",
          "amethyst",
          "base"
        ]
      }
    }
  }
};
```

What I want:
```
module.exports = {
  "color": {
    "amethyst": {
      "base": "#5d45cd"
        }
     }
};
```

**Comment by dbanksdesign** [comment]
Unfortunately there is no built-in format that does what you are looking for exactly. However, you could use the [json/nested](https://amzn.github.io/style-dictionary/#/formats?id=jsonnested) format, and any json file can be imported/required in node/js in the same way as you would a javascript module. So maybe that could work?

**Comment by cailborg** [comment]
That's super helpful, thanks!
