### ISSUE TITLE
Question: Default value when reference doesn't exist?

### ISSUE THREAD

**Issue by jimmymorris** [amzn/style-dictionary#318]
To expand on my problem a little bit. This is basing off the multiple-brands-multiple-platform example, which is awesome. Say I have a bunch of brands and a master properties file, I may have dozens of properties in a brand, in the build, however, I would like to say, if this value doesn't exist in the brand file, use this default value from this file instead.

Is this possible?

**Comment by chazzmoney** [comment]
@jimmymorris Did you need anything else or is it ok to close this?

**Comment by jimmymorris** [comment]
Worked well, closing
