### ISSUE TITLE
Remove bad words from documentation

### ISSUE THREAD

**Issue by dbanksdesign** [amzn/style-dictionary#328]
Based on [this CSS-Tricks article](https://css-tricks.com/advice-for-technical-writing/#article-header-id-8) lets remove bad words from the documentation. Words/phrases to remove:
* just
* simply
* clearly
* of course
* easy
* so
* basically
* technically
* very
* in order to
* everyone knows

One thing to note, some markdown files are generated by a script and handlebars, but those have a comment at the top of the file that they are being generated.

**Comment by manisacharya** [comment]
Hello, @dbanksdesign. I want to give a try on this.

**Comment by Iqlaas** [comment]
Hi @dbanksdesign, which documentation are you referring to?

**Comment by dbanksdesign** [comment]
Everything on https://amzn.github.io/style-dictionary/#/ which is built by the markdown files in the docs/ folder (see note in the issue). Also README files in the examples/ folder, and any JSDoc comments in the code.

**Comment by dbanksdesign** [comment]
I think we have enough PRs for this issue for now, we are still going through them. Thank you everyone for your contributions!
