### ISSUE TITLE
How to include comments in build files

### ISSUE THREAD

**Issue by davidrpoliti** [amzn/style-dictionary#344]
I'm using storybook to ingest the tokens built by style-dictionary. I need to include a commented-out header that gets added to the built scss. 

Is there a way to add the header in my config, or base.json, so that the output build file looks like this?
<img width="356" alt="Screen Shot 2019-10-16 at 5 44 55 PM" src="https://user-images.githubusercontent.com/4054043/66969034-b82a6180-f03c-11e9-8cef-1a961b3898f2.png">

**Comment by dbanksdesign** [comment]
Yes, but you will need to create a custom format. Here is something I threw together quickly, let me know if it makes sense: 

```js
const StyleDictionary = require('style-dictionary');

StyleDictionary.registerFormat({
  name: 'scss/variables',
  formatter: function(dictionary, config) {
    const header = `/**\n` +
      this.header.split('\n').map((line) => ` * ${line}`).join('\n') +
      `\n */\n`;
      
    return header +
      dictionary.allProperties.map((prop) => `$${prop.name}: ${prop.value};`).join('\n');
  }
});

module.exports = {
  "source": ["properties/**/*.json"],
  "platforms": {
    "scss": {
      "transformGroup": "scss",
      "buildPath": "build/scss/",
      "files": [{
        "header": `@tokens Colors
@presenter Color`,
        "destination": "_variables.scss",
        "format": "scss/variables"
      }]
    },
  }
}

```

**Comment by dbanksdesign** [comment]
`this` inside a custom format is bound to the file object performing the format. You can add any arbitrary data in the file object and access it in the format.

**Comment by dbanksdesign** [comment]
@davidrpoliti do you still need help with this?

**Comment by davidrpoliti** [comment]
@dbanksdesign I do! I'm going to try to get this working tomorrow with one of my peers.
(I've been on paternity leave)

Would I just add the commented out portion after `@presenter Color`?

**Comment by dbanksdesign** [comment]
Congrats! 🎉 I am about to do that myself. 

The custom format I created in that example will take what is in the `header` attribute in the file object in the config and put it in a multiline comment. So you will edit the value of `header` with whatever you want the comment to be. Hopefully that makes sense, if not you can send me your codebase and I'll take a look.

**Comment by davidrpoliti** [comment]
@dbanksdesign this makes sense! and congrats to you as well!

I'm pretty new at this, and I can't figure out where that snippet should live. Does it go in my storybook config? Happy to send you a coffee/venmo for helping me out.

**Comment by dbanksdesign** [comment]
@davidrpoliti thanks!

That snippet would live in your style dictionary configuration. If you have a repository you are working on I could take a look at I could tell you exactly where it goes.

**Comment by anupsingh244** [comment]
Hey @dbanksdesign, What if i want multiple headers in single file like for colors, border-radius, line-height, This just create one header at top level.

**Comment by avkvirtru** [comment]
To build on the comments above, I'd love to build a mixed `:root` and multiple-header stylesheet like this: https://github.com/avkvirtru/virtuoso-design-system/blob/d69be98/lib/styles/tokens.css

This plays very nicely with the Storybook Design Token add-on.

**Comment by dbanksdesign** [comment]
@avkvirtru having a storybook design token format would be awesome!

**Comment by nhoizey** [comment]
I think this might answer the need:
[feat(formats): adding custom file headers](2a29502f762c8694dd541dc9c0a0e0aa32e4dec9)

**Comment by chazzmoney** [comment]
This is now part of 3.0 via #572
