### ISSUE TITLE
Remove hard-coded filters from templates

### ISSUE THREAD

**Issue by ricovitch** [amzn/style-dictionary#355]
Some templates like the android templates have hard-coded properties filters.
For example : https://github.com/amzn/style-dictionary/blob/master/lib/common/templates/android/colors.template
* filters props with attributes.category === 'color'

It follows an opinionated way of structuring tokens with the documented CTI approach. But the documentation also leaves the door open for different ways of structuring tokens.
And having hard-coded filters makes it hard. In our case we had to duplicate the android template and remove hard-coded filters to make it work.

I think it makes sense to remove the hard-coded filters and document in the formats part of the documentation how to filter the props manually for each formats. Or even better make it a default instead of hard-coded filters.

Thank you

**EDIT**
We finally removed the duplicated android template in favor of a custom transform that remap the properties attribute to match with the original template hard coded filter.
This is a bit what the documentation suggests here : https://amzn.github.io/style-dictionary/#/transforms?id=pre-defined-transforms
> All the pre-defined transforms included use the CTI structure for the match properties. If you structure your style properties differently you will need to write custom transforms or make sure the property CTIs are on the attributes of your properties.

**Comment by dbanksdesign** [comment]
This definitely makes sense. I think it would be nice to make the current behavior a default, but if the user included a filter to use that instead so we don't break backwards compatibility.

**Comment by dbanksdesign** [comment]
Closing this as we tackled it in 3.0
