### ISSUE TITLE
Add mixin format for scss variables

### ISSUE THREAD

**Issue by surajkc599** [amzn/style-dictionary#360]
Normally we would use scss variables format to get the output in the following way. One of the example could be like below:

FileName: button-light.scss 
$component-button-primary-background-color: #2b3e4b;

Lets imagine if we had to support for multiple themes we would have multiple files of scss variables. Dynamically importing scss variables based on theme is still not possible or not a straight way of doing it. 

If Style-dictionary outputs like below:

@mixin button-light { 
$component-button-primary-background-color: #2b3e4b;
}

we could then at the application side perform below:
:host-context(.light) {
@include button-light;
}

Could you please help me in creating a new formatter specially in my case. I would also think people would also benefit from this?

**Comment by surajkc599** [comment]
It was so easy to solve it myself. In love with style-dictionary :)

![image](https://user-images.githubusercontent.com/8035827/69805278-a366ef00-11e0-11ea-9bba-5bca8a78fe8e.png)

![image](https://user-images.githubusercontent.com/8035827/69805343-bb3e7300-11e0-11ea-818e-0e72e5f59d7c.png)

**Comment by argdesign** [comment]
Wow this is exactly what I need! 

Let's say I need the name of the token in the header. Is it posible to achieve that?

for example:

@mixin component-button-primary-background-color {
$component-button-primary-background-color: #2b3e4b;
}
