### ISSUE TITLE
Example wih Sketch-Constructor

### ISSUE THREAD

**Issue by qimmiq** [amzn/style-dictionary#361]
No Bug,
but i'm really interested in a example combined with amzn/sketch-constructor. 
Sadly my coding skills are very limited, so i didn't got it to work yet. 

Anyway both projects are very interesting to see and follow. 
thanks for that
👌🏻

**Comment by dbanksdesign** [comment]
This has been on my to-do list for a while. If you haven't seen it, the Sketch Constructor repository has an example: https://github.com/amzn/sketch-constructor/tree/master/__examples__/generating-sketch-from-style-dictionary

**Comment by vkoopmans-resoluut** [comment]
I tried the example but no Sketch file is being built, I get no errors in the command line, but no sketchfile in the /dist as well :)
