### ISSUE TITLE
showFileHeader option not working for ios/ios-swift templats

### ISSUE THREAD

**Issue by funyapu** [amzn/style-dictionary#387]
ref #243

**Comment by funyapu** [comment]
Sorry. Have no time to fill. Will fill description and make a PR next week.

**Comment by dbanksdesign** [comment]
Hey @funyapu what specifically isn't working? If you could post some example code that would be great. Thanks!

**Comment by dtc-fnishimura** [comment]
Sorry. I just found wrong configuration in my side, pls ignore.
