### ISSUE TITLE
Values of number zero are always filtered if filter is set

### ISSUE THREAD

**Issue by jreichenberg** [amzn/style-dictionary#406]
Hi,

For a token defined with value zero, for example `opacity: {value: 0}`, and any `filter` function set in config it appears that token is always filtered out.

I believe the cause is https://github.com/amzn/style-dictionary/blob/master/lib/filterProperties.js#L37, which perhaps should be `} else if (typeof value.value !== 'undefined') {`

This line only kicks in if a filter is set in config, as the entire filtering check is bypassed with no filter config.

Thoughts?

**Comment by dbanksdesign** [comment]
Good catch! You are right, we had an issue with that outside of the filters because of a conditional like that.

**Comment by arielwb** [comment]
Hi!
Any chance we get a release (or an alpha) containing this fix?

**Comment by dbanksdesign** [comment]
Sorry about that @arielwb! It should be published now in v2.10.1!
