### ISSUE TITLE
Fix(size transforms) Add a NaN check

### ISSUE THREAD

**Issue by tonyjwalt** [amzn/style-dictionary#408]
There currently aren't any NaN checks on the size transforms.

I'm happy to add them if you like. Let me know and I'll make an MR.

**Comment by dbanksdesign** [comment]
That would be great! Thanks!

**Comment by danilovaz** [comment]
@tonyjwalt anything about this? can I help?

**Comment by tonyjwalt** [comment]
Hi @danilovaz,

This the checks are in build [2.9.0](https://github.com/amzn/style-dictionary/compare/v2.8.3...v2.9.0) that was released on 4/21.

If you want to check out the code you can find it in this [commit](https://github.com/amzn/style-dictionary/commit/d353795) as part of MR [413](https://github.com/amzn/style-dictionary/pull/413).

**Comment by tonyjwalt** [comment]
by the way @danilovaz, thank you for offering to help!

@dbanksdesign, should I close this issue to prevent further confusion, or wait for someone from the team to close it? I'm not familiar with the proper protocol for that.

**Comment by dbanksdesign** [comment]
You can close this out, thank you so much! We messed up the commit message when merging, this issue should have been closed automatically 🙃
