### ISSUE TITLE
Token collisions were found

### ISSUE THREAD

**Issue by The-Code-Monkey** [amzn/style-dictionary#411]
```
⚠️  ./temp/time.json
While building time.json, token collisions were found; output may be unexpected.
    Output name 0 was generated by:
        time.transition.0   0
        time.delay.0   0
        time.duration.0   0
    Output name 1 was generated by:
        time.transition.1   120ms
        time.delay.1   50ms
        time.duration.1   1000ms

```

There really are unwanted is there a way to remove them or just hide them from the console via the config?

**Comment by dbanksdesign** [comment]
Unfortunately not at this time. It is on our backlog to add more robust log levels that would fix this: #367

**Comment by The-Code-Monkey** [comment]
any ideas as to when this will be implemented.

**Comment by chazzmoney** [comment]
Probably in a 3.x release.

If you have time to put together a PR, we could probably get it done sooner.

If you do want to try that route, you can search the repo for `console.log` and `GroupMessages` in the code to see where logging is generated.

**Comment by chazzmoney** [comment]
One more question - you are intentionally creating tokens with multiple values and don't mind if the output is any of them?

**Comment by chazzmoney** [comment]
@The-Code-Monkey just checking in here; I wanted to see if you had further input.

I'd love to understand the use case so I can implement a solution correctly. It sounds like you are generating tokens with the same name on purpose - can you clarify what the intent is?

Thanks!

**Comment by dbanksdesign** [comment]
I think part of this is that for 'nested' style formats like `json/nested`, they don't use the transformed names because they keep the original object structure. The way we test for collisions is to see if all token names are unique, and if the user doesn't use any name transform, token names might not be unique which would be fine in a nested format where the token names don't matter.  A quick fix would be to apply any name transform in the configuration, it won't have any effect on the nested formats, but will get rid of the warnings because all names would be unique. See the discussion here: #489

One quick fix for this that someone suggested was to mark formats as 'nested' or not, and if it is a nested format, don't show name collision warnings.

**Comment by The-Code-Monkey** [comment]
@chazzmoney we aren't actually giving them the same name these values are used being generated for a theme object for our styled-components / styled-system ui library, and we wanted to be able to call them like color.primary.0 which all works fine the only issue we have is that it thinks that time.delay.0 is the same as time.transition.0 their values might be the same but the reason they are different keys is so that they are used in the correct CSS property, and also we might want to change transitions across the board but leave the delays as is.

**Comment by The-Code-Monkey** [comment]
https://styled-system.com/theme-specification this is what we are doing but we have just taken it a step further and added a bit extra, for our internal use, sorry I won't be able to show any code as its all private

**Comment by dbanksdesign** [comment]
@The-Code-Monkey as a quick fix, could you try adding any name transform to the platform configuration you are getting those warnings in? It should not affect nested object structure formats like `json/nested` or `javascript/module`, but it will get rid of those warnings in the meantime.

**Comment by The-Code-Monkey** [comment]
Where in the config would I add those, can you link me to the correct part of the docs?

**Comment by dbanksdesign** [comment]
You would add the transform to the `transforms` array in the platform of the configuration where you are getting those warnings. https://amzn.github.io/style-dictionary/#/config

If you are using a built-in [transformGroup](https://amzn.github.io/style-dictionary/#/transform_groups), you will need to turn that into a transforms array.

```jsonc
{
  "source": ["tokens/**/*.json"],
  "platforms": {
    "js": {
      // here is where you would add a name transform
      "transforms": ["attribute/cti", "name/cti/kebab", /* other transforms */]
```

Does that make sense? If you post your configuration I can also tell you exactly where to put it.

**Comment by dbanksdesign** [comment]
Closing this as it is now fixed in 3.0. Feel free to reopen it if you still have an issue.

**Comment by adamduncan** [comment]
From https://github.com/dbanksdesign/style-dictionary-example-component-scss/issues/1#issuecomment-847423337:

> Style Dictionary will not show a warning if there is a collision between include files and source files because that is what include is intended for.

@dbanksdesign You mention the approach of using `include` and `source` to avoid the warnings (as is [outlined here](https://dbanks.design/blog/dark-mode-with-style-dictionary/#File-extensions) and implemented in the [`multi-file` example branch](https://github.com/dbanksdesign/style-dictionary-dark-mode/blob/multi-file/build.js#L148-L155)).

We're trying to work through this exact use case, allowing for intentional collisions owing to overrides for particular color schemes or themes. Though what we're finding (and what seems to happen in the example repo) we're still seeing warnings no matter the combination of these two configuration options.

<img width="1737" alt="Screenshot 2021-12-07 at 18 32 00" src="https://user-images.githubusercontent.com/2671053/145086352-11a51b28-e08c-40f1-b1a3-a4498a9968e4.png">


Is this something that is avoidable, or might we have to roll with it until logging (https://github.com/amzn/style-dictionary/issues/367) is available? Thanks

**Comment by dbanksdesign** [comment]
That looks like a different warning message than the token collisions one. From the screenshot, that warning message is about using outputReferences and filters giving you a file that uses references not found in the generated file.

**Comment by adamduncan** [comment]
Ah, I see. There's also this type of warning:

```
Property Value Collisions:
Collision detected at: color.success-weaker! Original value: {color.green.900.value}, New value: {color.green.50.value}
```

So by correctly configuring the `include` and `source` to be mutually exclusive, we should avoid this type of warning, though we'd still expect to get the "filtered out token references..." warnings?

In which case I need to revisit our configuration. We're getting both 🙃 

Appreciate the response, @dbanksdesign 👍

**Comment by yevgeniy-belov** [comment]
I'm using the 3.1.0 and still getting these warnings.
It complaints about the Output names despite the fact that the full paths are not identical.

**Comment by alecgeatches** [comment]
For anyone still having this issue, the `nested` property can be set to `true` on your formatter function to avoid nested collision false positives:

```js
const { minifyDictionary } = StyleDictionary.formatHelpers;

const formatter = ( { dictionary } ) => {
    return JSON.stringify( minifyDictionary( dictionary.tokens ), null, 2 );
};

// Avoid nested collision warnings
formatter.nested = true;

styleDictionary.registerFormat( {
    name: 'custom/json/nested',
    formatter: formatter,
} );
```

Note this is the same way built-in formats like `json/nested` work:

https://github.com/amzn/style-dictionary/blob/28787befb1a2c7173c64a2a4bef5b029d0799cce/lib/common/formats.js#L1243-L1246

**Comment by The-Code-Monkey** [comment]
```nestedJson.nested = true;

StyleDictionary.registerFormat({
  name: 'custom/nested/json',
  formatter: nestedJson,
});```

Ive just tried this and i still get Collisions detected.

```
Collision detected at: sizes.1/12! Original value: true, New value: true
Collision detected at: sizes.2/12! Original value: 16.666667%, New value: 16.666667%
```

How do i fix this its really bugging me as they are not colliding.

**Comment by The-Code-Monkey** [comment]
https://github.com/The-Code-Monkey/TechStack/tree/dev/packages/theme Here is a link to my theme stuff. the config file is the style dictionary config and the index.ts file is the logic. Is it possible to reopen this ticket as to me there are no collisions. Yet i am still being warned.

**Comment by pmqueiroz** [comment]
While this robust log still in the backlog for 4 years, that's was my solution:

```sh
function _removeDuplicatedNewLines(
  while read -r line; do
    if [[ "$line" != $'\r' ]]; then
      echo $line
    fi
  done
)

function build(){
  rm -rf ./dist

  # build removing collisions logging. see: https://github.com/amzn/style-dictionary/issues/411
  script -qec "npx tsx ./src/build.ts " /dev/null \
    | grep -vE "Collision detected at|Property Value Collisions:|While building|filtered out token references|This is caused when combining a filter and \`outputReferences\`|No properties for .*\. File not created\." \
    | sed -E '/^$/d; /    [^ ]/d' \
    | _removeDuplicatedNewLines
}
```

pretty ugly to remember that style-dictionary isn't fixing it

**Comment by markevans** [comment]
> For anyone still having this issue, the `nested` property can be set to `true` on your formatter function to avoid nested collision false positives:
> 
> const { minifyDictionary } = StyleDictionary.formatHelpers;
> 
> const formatter = ( { dictionary } ) => {
>     return JSON.stringify( minifyDictionary( dictionary.tokens ), null, 2 );
> };
> 
> // Avoid nested collision warnings
> formatter.nested = true;
> 
> styleDictionary.registerFormat( {
>     name: 'custom/json/nested',
>     formatter: formatter,
> } );
> Note this is the same way built-in formats like `json/nested` work:
> 
> [style-dictionary/lib/common/formats.js](https://github.com/amzn/style-dictionary/blob/28787befb1a2c7173c64a2a4bef5b029d0799cce/lib/common/formats.js#L1243-L1246)
> 
> Lines 1243 to 1246 in [28787be](/amzn/style-dictionary/commit/28787befb1a2c7173c64a2a4bef5b029d0799cce)
> 
>  // Mark which formats are nested 
>  module.exports['json/nested'].nested = true; 
>  module.exports['javascript/module'].nested = true; 
>  module.exports['javascript/object'].nested = true;

This worked for me - given my setup just needed the line
```
myFormatter.nested = true;
```

**Comment by jorenbroekema** [comment]
@pastelcyborg Yeah what you're seeing is a group level collision due to the "$type" property "font" colliding with the same one in the other file. https://github.com/amzn/style-dictionary/issues/1316 open issue here, if you need to track it.
