### ISSUE TITLE
Attribute/CTI overwrites existing attributes

### ISSUE THREAD

**Issue by tonyjwalt** [amzn/style-dictionary#414]
The `Attribute/CTI` transform overwrites existing `category`, `type`, `item`, `sub-item`, and `state` values. It also assigns `undefined` if the path isn't long enough.

This prevents a user from using `Attribute/CTI` for most tokens, then also manually assigning category attributes for specific tokens. There are other ways around this, but I think the most elegant may be to adjust `Attribute/CTI` to respect manually assigned values.

I wrote a different default attributes generator to handle "option" and "component" tokens, but that relies on an array of possible "option" token types, so I'm not sure it belongs in Style dictionary. However, I could adjust the Attribute/CTI transform to allow this:

```
{
  "button": {
    "border": {
      "width": {
        "value": 1,
        "attributes": { 
          "component": "button",
          "category": "size"
        }
      }
    }
  }
}
```
to resolve it's attributes to:
```
{
  component: "button",
  category: " size"
  type: "border",
  item: "width"
}
```

If this looks useful, and you want it, let me know.

**Comment by dbanksdesign** [comment]
I like the idea of having the `attribute/cti` transform honor previously defined attributes so that it doesn't wipe out user-defined ones. If you have the time, feel free to submit a PR. Thanks for bringing this up!
