### ISSUE TITLE
The native parseFloat() only has one argument

### ISSUE THREAD

**Issue by tlehtimaki** [amzn/style-dictionary#416]
There is minor bug in ./lib/common/transforms.js where parseFloat is given two arguments. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/parseFloat

I assume it has been accidentally been confused with parseInt() which has second optional argument for radix.

**Comment by dbanksdesign** [comment]
🤦‍♂ my bad

**Comment by chazzmoney** [comment]
Fixed in merge of #417
