### ISSUE TITLE
Drop support for Node 8

### ISSUE THREAD

**Issue by dbanksdesign** [amzn/style-dictionary#437]
Node 8 is no longer a supported version of node. Node 10 is currently in maintenance long-term support and the current version of node is 14. 

https://nodejs.org/en/about/releases/

**Comment by ruppysuppy** [comment]
@dbanksdesign  I would like to work on this issue. I only need to update [package.json](https://github.com/amzn/style-dictionary/blob/master/package.json#L27)? What is the version I should replace it with?

**Comment by chazzmoney** [comment]
Done.
