### ISSUE TITLE
Filter object not working with json format.

### ISSUE THREAD

**Issue by juanfabrega** [amzn/style-dictionary#438]
Hi, thanks for all the work you do!

I currently have a problem when trying to export different sets of tokens to different files. I have three format needs: scss, css, and json. I use JSON to consume in our design systems website in order to dynamically generate documentation.

The issue is that the filter key does not seem to work for our JSON format. This is what my config file looks like at the moment:

```
{
  "source": ["properties/**/*.json"],
  "platforms": {
    "scss": {
      "transformGroup": "scss",
      "buildPath": "build/scss/",
      "files": [{
        "destination": "colors.scss",
        "format": "scss/variables",
        "filter": {
          "attributes": {
            "category": "color"
          }
        }
      }]
    },
    "css": {
      "transformGroup": "css",
      "buildPath": "build/css/",
      "files": [
        {
          "destination": "colors.css",
          "format": "css/variables",
          "filter": {
            "attributes": {
              "category": "color"
            }
          }
        }
      ]
    },
    "json": {
      "buildPath": "build/json/",
      "files": [
        {
          "destination": "colors.json",
          "format": "json",
          "filter": {
            "attributes": {
              "category": "color"
            }
          }
        }
      ]
    }
  }
}
```

The expected result is that I would see the following file structure exported:

* css
  * colors.css
* scss
  * colors.scss
* json
  * colors.json

While this does happen as expected, the json file is completely empty. The other two work just fine. 

I removed the filter and my json export worked properly again, leading me to believe that filters are not working with the json format. Is this a known issue or limitation? I have not been able to find anything in the docs about it. Thanks!

**Comment by dbanksdesign** [comment]
It looks like your "js" platform is missing transforms or a transformGroup. At the very least, add the 'attribute/cti' transform which the css and scss transformGroups include. That transform adds category, type, item on the attributes object of each token based on the object path. Let me know if that works and if you have any other questions!

**Comment by juanfabrega** [comment]
Thanks a lot @dbanksdesign! The basic `'attribute/cti'`  transform did not work, but I just added the `'js'` transformGroup and that did the trick. Appreciate the help on this basic question.
