### ISSUE TITLE
Help with Combining Values

### ISSUE THREAD

**Issue by mbulfair** [amzn/style-dictionary#452]
I am attempting to output a hex8 value from a **hex6 + alpha** value. I have each of these in other properties. I am having some issues figuring out how to get both to return the referenced values. 

I've manually imported tinycolor into my build.js, and trying to set things manually, but it always returns black. 

Any help or guidance in best practices on how to achieve this would be great.

**Comment by dbanksdesign** [comment]
Apologies for the lateness of this reply, but this is something that we are making easier in the next version of Style Dictionary. You can try it out by installing it with the `next` tag: `npm install style-dictionary@next`. I made a new example using the next version of Style Dictionary that I believe solves your case in 2 different ways: https://github.com/amzn/style-dictionary/tree/3.0/examples/advanced/transitive-transforms

Let me know if you have any questions!

**Comment by chazzmoney** [comment]
This is now possible with the main release of Style Dictionary 3.0

Please check out https://github.com/amzn/style-dictionary/tree/main/examples/advanced/transitive-transforms for an example.
