### ISSUE TITLE
SD V3 Release Date

### ISSUE THREAD

**Issue by The-Code-Monkey** [amzn/style-dictionary#466]
Hi Guys,

When are you planning to release V3 as the project says Summertime 2020, im guessing COVID delayed that is there any update as to when the new release date will be.

Keep it up.

**Comment by dbanksdesign** [comment]
Thank you for bringing that up, we should update the project timeline. And as you brought up, 2020 hasn't exactly gone to plan... But the good news is we are actively working on 3.0 right now (see 3.0 branch). Our plan is to release it before the end of the year. I know that is a fairly large target, but I don't want to over-promise on a timeline. We will have a pre-release available before actual release to have users test to make sure we don't break anyone. While it is a major release, we want it to be backwards compatible so as to not break anyone. Stay tuned!

**Comment by chazzmoney** [comment]
I don't have anything to add - just want to say thank you for asking. Knowing that people are waiting provides a sense of both value and urgency to the work.

So, thanks!

**Comment by dbanksdesign** [comment]
A pre-release version of 3.0 is available now. You can get it by installing it with the `next` tag in npm: `npm install style-dictionary@next`. Here is a page describing the changes: https://amzn.github.io/style-dictionary/#/version_3

**Comment by dbanksdesign** [comment]
We just released a new release candidate version of 3.0, you can install it with `npm install style-dictionary@next`

**Comment by chazzmoney** [comment]
3.0 has been released as per #636. Feel free to continue any conversation on #638
