### ISSUE TITLE
Are there setting for indentation in style dictionary

### ISSUE THREAD

**Issue by cojaco** [amzn/style-dictionary#469]
Hi there,

just a quick question is it possible to configure the indentation of the scss output?
Because in our Team we have indentation of for space instead of two.

**Comment by dbanksdesign** [comment]
There is not with the built-in SCSS formats. However, you can create a custom format that fits your formatting needs.

You can take a look at how the built-in SCSS formats work here: https://github.com/amzn/style-dictionary/blob/main/lib/common/formats.js

Here is a quick and rough example:

```javascript
StyleDictionary.registerFormat({
  name: 'scss/variables'
  formatter: (dictionary, config) => {
    return dictionary.allProperties.map(token => {
      return `    $${token.name}: ${token.value};`
    }).join('\n')
  }
});
```

Hope that helps!

**Comment by cojaco** [comment]
Ah Thanks for the hint, I'll check it out!

**Comment by cojaco** [comment]
An easier solution for me was, since I'm already using stylelint, letting stylelint taking care of indentation:

package.json

```
}
  "scripts": {
    "style-dictionary-build": "node ./style-dictionary-build && npx stylelint 'src/assets/styles/_settings/**/*.scss' --fix", 
  }
}
```

**Comment by dbanksdesign** [comment]
That is a way better solution! That is really smart to use a code formatter like stylelint/prettier to take care of formatting and indentation.

**Comment by chazzmoney** [comment]
Thank you for the question - and for the solution! We will include this as a best practice recommendation from now on.
