### ISSUE TITLE
Enhanced Terminal Output

### ISSUE THREAD

**Issue by dbanksdesign** [amzn/style-dictionary#50]
Text colors, emojis, loading, and better messaging!

**Comment by chazzmoney** [comment]
Danny, seems like you have some ideas here.  Can you elaborate some?  I might be able to get something done on this if you have some specifics in mind.

**Comment by dbanksdesign** [comment]
* **Better error messaging:** those were all the things you did a few weeks ago, so we got that done.
* **Text colors:** I was thinking of using chalk (npm library to have colorized text output in the terminal)
* **Emojis:** just for fun throwing some emojis in the output, nothing important, just thought it would be cool. I don't know have anything specific in mind. Maybe we can find some emojis that signify a 'style dictionary' or something
* **Loading:** I was thinking of showing some timer stats stuff like build time and how many files were created and how many style properties there are. Maybe also showing an ASCII loader like when you install modules with npm or yarn.

**Comment by chazzmoney** [comment]
Color (Chalk) support added in PR #99

**Comment by dbanksdesign** [comment]
Closing this, @chazzmoney enhanced the terminal output and this is launched.
