### ISSUE TITLE
Generate multiple tokens per property

### ISSUE THREAD

**Issue by nuno-mrks** [amzn/style-dictionary#508]
Is it possible to generate multiple tokens for a single property?

The specific case I'm looking for is, given a Hex color property, generate both Hex and RGB color tokens.
```
{
  "color": {
    "white": { "value": "#FFFFFF" },
    "black": { "value": "#000000" }
  }
}
```
Would produce something like this:
```
$color-white: #FFFFFF;
$color-black: #000000;
$color-white-rgb: 255,255,255;
$color-black-rgb: 0,0,0;
```

I know I can transform a value into another format and I used that in the past, but what I'm looking for is multiple formats for a single input value (in my case just colors).

On a side note, is there an official Discord or Slack channel for Style Dictionary discussions/help?

**Comment by dbanksdesign** [comment]
Transforms are 1-in-1-out. A transform is applied to each token, it can't generate other tokens from it. However what you could do is add the extra hex/rgb/etc. values into the attributes of a single toke using the [attribute/color](https://amzn.github.io/style-dictionary/#/transforms?id=attributecolor) transform. Then in a custom format you could use those attributes to output more sass variables. Let me know if this makes sense, or if you need a quick example code. 

There is no official Slack or Discord for Style Dictionary, but a lot of us hang out on the design systems slack: http://design.systems/slack/ There is a #tool-style-dictionary channel in there as well. Maybe one day there will be enough interest for its own discord or something. The best place to get help would be asking questions here so everyone can learn from it.

**Comment by nuno-mrks** [comment]
If you wouldn't mind, could you provide an example code then?
I'm still trying to figure out all of Style Dictionary's perks and I doubt I could get manage this case alone.
Thanks

**Comment by dbanksdesign** [comment]
Here is a quick example:

```javascript
const StyleDictionary = require('style-dictionary');

// Custom format
const multipleSassTokensFormat = function(dictionary) {
  return dictionary.allProperties.map(token => {
    let output = `$${token.name}: ${token.value};`
    // If the token is a color, it will output 2 lines
    if (token.attributes.category === 'color') {
      // 'attributes/color' transform added an rgba object
      // as well as hsl and hsv
      const {r,g,b,a} = token.attributes.rgb;
      // add a second line to the output
      output += `\n$${token.name}-rgb: rgba(${r},${g},${b},${a});`
    }
    return output;
  }).join(`\n`);
}

StyleDictionary.extend({
  // directly adding design tokens here to make this example self-contained
  // you would probably use source: ['paths/to/tokens']
  properties: {
    color: {
      white: { value: "#ffffff" },
      black: { value: "#000000" }
    },
    size: {
      padding: {
        base: { value: 1 }
      }
    }
  },
  
  // Adding the custom format here. This is equivalent
  // to calling `StyleDictionary.registerFormat({
  //    name: 'multipleSassTokensFormat'
  //    formatter: multipleSassTokensFormat
  // })
  format: {
    multipleSassTokensFormat
  },
  
  platforms: {
    scss: {
      transforms: ['attribute/cti','attribute/color','color/css','size/rem','name/cti/kebab'],
      files: [{
        destination: 'variables.scss',
        format: 'multipleSassTokensFormat'
      }]
    }
  }
}).buildAllPlatforms();
```

That will output:

```scss
$color-white: #ffffff;
$color-white-rgb: rgba(255,255,255,1);
$color-black: #000000;
$color-black-rgb: rgba(0,0,0,1);
$size-padding-base: 1rem;
```

**Comment by nuno-mrks** [comment]
Thanks @dbanksdesign, just tried it and it works.

On my current workflow, I'm generating multiple formats (scss/variables, scss/map-deep and json/nested) as they are being neede in different ways on my web applications.
If I were to support colors in Hex and RGB for all of these formats, then I'd probably need to create custom formats for the ones mentioned previously, or is it possible to add the Hex colors to the deep-merged JSON file before any platform transforms occurs (according to what is described of the build process)?

**Comment by dbanksdesign** [comment]
You would have to create custom formats for each of the ones you mentioned. Another possible solution would be to use Node modules as your source files instead of JSON. You can take a look at [this example](https://github.com/amzn/style-dictionary/tree/main/examples/advanced/node-modules-as-config-and-properties). Then what you would do is have a `color.js` file like this:

```javascript
const Color = require('tinycolor2');

const white = "#fff";
const black = "#000";

module.exports = {
  color: {
    'white': { value: white },
    'black': { value: black },
    'white-rgb': { value: Color(white).toRgbString() },
    'black-rgb': { value: Color(black).toRgbString() }
  }
}
```

One thing to note is that if you go this route you will need to *not* transform the value or else the 'rgb' tokens might be hex or the other way around.

**Comment by nuno-mrks** [comment]
@dbanksdesign, the node modules example helped me somewhat, but probably not in the way you intended :D
Here's what I ended up doing:

```javascript
const StyleDictionary = require('style-dictionary');
const Color = require('tinycolor2');

StyleDictionary.registerFilter({
  name: 'filter-colors',
  matcher: (prop) => prop.attributes.category === 'color'
});

StyleDictionary.registerTransform({
  name: 'rgb-colors',
  type: 'value',
  matcher: (prop) => prop.attributes.category === 'color' && prop.path.includes('rgb'),
  transformer: (prop) => {
    var color = Color(prop.original.value).toRgb();
    return `${color.r},${color.g},${color.b}`;
  }
});


module.exports = {
  source: ['properties/index.js'],
  platforms: {
    scss: {
      transforms: ['attribute/cti', 'color/hex', 'name/cti/kebab', 'rgb-colors'],
      transformGroup: 'scss',
      buildPath: 'build/scss/',
      files: [
        {
          destination: 'root.scss',
          format: 'css/variables',
          filter: 'filter-colors' // Only the color CSS properties are relevant for this format
        },
        {
          destination: 'tokens.scss',
          format: 'scss/map-deep'
        }
      ]
    },
    json: {
      transforms: ['attribute/cti', 'color/hex', 'name/cti/kebab', 'rgb-colors'],
      transformGroup: 'js',
      buildPath: 'build/json/',
      files: [{
        destination: 'sd.json',
        format: 'json/nested'
      }]
    }
  }
}
```

My color module looks like this:

```javascript
const colors = {
  "black": { "value": "#000000" },
  "white": { "value": "#ffffff" }
}

const properties = {
  "color": {
    hex: colors,
    rgb: colors
  }
}

module.exports = properties;
```

It looks a bit weird, but it does what I was looking for. I only have to define once my colors. Then they are transformed as I wanted for each format.
Not sure if this is what you had in mind though...

**Comment by dbanksdesign** [comment]
That is not what I had in mind, but I think I like your way better actually! The reason is in my example I am kind of breaking the idea of what a token is. In the format I am generating multiple tokens from a single one. Your code you actually have a 1:1 of tokens, you are just creating multiple tokens when you are defining them. 

One of the intentions of Style Dictionary is that it is very un-opinionated, most problems have multiple solutions based on preference. There is no right or wrong way to do things for the most part.

**Comment by dbanksdesign** [comment]
@nuno-mrks are you good with closing this issue or do you have other questions on this topic?

**Comment by nuno-mrks** [comment]
@dbanksdesign yes, please.
Sorry for not getting back earlier. Feel free to close this issue.

**Comment by dbanksdesign** [comment]
No worries at all! Closing for now. Feel free to re-open or open a new issue if you have any more questions!
