### ISSUE TITLE
Overriding an existing transform

### ISSUE THREAD

**Issue by nhoizey** [amzn/style-dictionary#519]
Based on https://github.com/amzn/style-dictionary/blob/master/examples/advanced/component-cti/config.js where I read that "Using .registerTransform() with the same transform name, 'attribute/cti', would work as well", I tried.

But I get a "RangeError: Maximum call stack size exceeded" error, as it seems the code loops the 'attribute/cti' transform.

**Comment by dbanksdesign** [comment]
Ah you are correct. The quick fix is to keep a reference of the original transformer function:

```javascript
const transformer = StyleDictionary.transform['attribute/cti'].transformer;

StyleDictionary.registerTransform({
  name: 'attribute/cti',
  type: 'attribute',
  transformer: (prop) => {
    // Only do this custom functionality in the 'component' top-level namespace.
    if (prop.path[0] === 'component') {
      // When defining component tokens, the key of the token is the relevant CSS property
      // The key of the token is the last element in the path array
      return propertiesToCTI[prop.path[prop.path.length - 1]];
    } else {
      // Fallback to the original 'attribute/cti' transformer
      return transformer(prop);
    }
  }
});
```

**Comment by nhoizey** [comment]
@dbanksdesign it works like that indeed, thanks! 👍

Do you think the example should use this syntax? I can make a PR if you want.

**Comment by dbanksdesign** [comment]
Yea I think we should correct this in the example so others don't get confused. If you'd like to open a PR that would be wonderful. If you can, make it on the '3.0' branch because that will be the next release. Thanks!

**Comment by dbanksdesign** [comment]
This is fixed now!
