### ISSUE TITLE
Generate tokens into the same folder as source (json)

### ISSUE THREAD

**Issue by StefanKandlbinder** [amzn/style-dictionary#525]
Is it possible to to generate e.g. scss tokens into the same folder as the source(json) file?
I am working on a component library and i want the scss file to be generated next to the json file.
my folder structure should then look like that:
- my-component.ts
- my-component.html
- my-component.tokens.scss (the generated file)
- my-component.tokens.json

right now all the tokens are generated into a single file.

Thx for sharing this awesome tool and i would be very happy if someone can help me out...

it would also be nice, if i can scope the output to a component like that:

.my-component {
  --my-component-button-font-family: var(--font-family-condensed)
  ...
}

**Comment by dbanksdesign** [comment]
Anything is possible™ with the right setup. There is an example in the upcoming version (3.0) that has a similar example of 1:1 input and output files: https://github.com/amzn/style-dictionary/tree/3.0/examples/advanced/matching-build-files

Here is a quick and rough example based on your requirements:

```javascript
// sd.config.js

const glob = require('glob');

// put all token json files into an array of file paths
const tokenFiles = glob.sync(`components/**/*.tokens.json`);

module.exports = {
  source: [
    // include your token files as you normally would here
    `components/**/*.tokens.json`
  ],
  platforms: {
    scss: {
      transformGroup: `scss`,
      // map the array of toke file paths to style dictionary output files
      files: tokenFiles.map(filePath => {
        return {
          format: `scss/variables`,
          destination: filePath.replace(`.json`, `.scss`),
          // the next version of style dictionary adds a filePath property
          // you can filter against
          filter: (token) => token.filePath === filePath
        }
      }),
    }
  }
}
```

The package json file would have a build script like:

```json
  "scripts": {
    "build": "style-dictionary build --config ./sd.config.js"
  },
```

For this to work you will need a pre-release of 3.0 which you can get with `npm install style-dictionary@next`

This does not handle the CSS variable scoping, the `css/variables` format does not yet have a way to change the scope, but that would be a welcomed addition. 

Let me know if this makes sense or you have any questions!

**Comment by StefanKandlbinder** [comment]
Thx for the fast answer:
`filter: (token) => token.filePath === filePath` doesn't work, because there is no filePath attribute on token.
if i do a console.log on token i get this: ```
{
  value: '4rem',
  original: { value: '4rem' },
  name: 'colibri-space-16',
  attributes: { category: 'colibri', type: 'space', item: '16' },
  path: [ 'colibri', 'space', '16' ]
}
```

cheers
stefan

**Comment by dbanksdesign** [comment]
Can you confirm for me you are using the latest release candidate version of Style Dictionary (3.0.0-rc.2)? We added the `filePath` attribute in the 3.0 branch of Style Dictionary. You can get the 3.0 release candidate with `npm install style-dictionary@next`. If you still can't see filePath on the token let me know.

**Comment by dbanksdesign** [comment]
@StefanKandlbinder just checking in to see if this works or if you are still having trouble. Let me know!

**Comment by shivjsdev** [comment]
I'm also trying to achieve something like this to generate component based css tokens referencing to brand (or base - optional) tokens. so that each component have its own CSS and consumers of my library can refer component specific css. I do not want to combine all the css tokens for components together.

![image](https://user-images.githubusercontent.com/59453978/141172859-44ad0a60-f315-4aea-82db-8b6b2d22f642.png)

In Order to achieve this, I'm using following config

```js
module.exports = {
  // In order to avoid missing reference error, 
  // I'm including base and brand related tokens
  include: [
    "./src/tokens/properties/base/**/*.json",
    `./src/tokens/properties/brands/default/**/*.json`,
  ],
  source: ["./src/tokens/properties/components/button.json"],
  platforms: {
    css: {
      prefix: "dui",
      transformGroup: "css",
      buildPath,
      useVariables: true,
      files: [
        {
          destination: `button.css`,
          format: "css/variables",
          options: {
            // here want to keep the reference,
            // so if I include brandA.css and button.css
            // variables in button.css reference to variables in brandA.css
            outputReferences: true,
          },
          // I want to keep only tokens in button.json 
          // but not the ones in include array
          filter: (token) => token.isSource,
        },
      ],
      transforms: [
        "attribute/cti",
        "name/cti/kebab",
        "time/seconds",
        "size/unitless",
      ],
    },
  },
};
```

It does the job but getting a warning as follows. Is there a way to suppress this warning or a different way to make this work.

![image](https://user-images.githubusercontent.com/59453978/141174639-9dfc00e0-90f6-4b98-b562-4b0ca9563c96.png)

**Comment by jorenbroekema** [comment]
Closing question issue, considered as answered.

As for logging, see https://styledictionary.com/reference/logging/
