### ISSUE TITLE
Support for Stylus format

### ISSUE THREAD

**Issue by klausbayrhammer** [amzn/style-dictionary#526]
Some of our internal projects use [Stylus](https://www.npmjs.com/package/stylus) as a preprocessor, and we've written a custom formatter to support this (which works great).

Since stylus is relatively popular we would happily contribute it. However we were not sure if based on the ["what should be included" section in the contributing guidelines](https://github.com/amzn/style-dictionary/blob/main/CONTRIBUTING.md#what-should-be-included) stylus support is something you would like to see within the style-dictionary.

**Comment by dbanksdesign** [comment]
Stylus would definitely be something we would see within Style Dictionary. That section in the contribution doc is mainly so we don't get non-generic formats, but we always want to add support for languages. If you would like to contribute that, take a look at the Less, SCSS, and CSS formats. I'm not as familiar with Stylus, I assume we don't need to add any new transforms to support Stylus.

**Comment by chazzmoney** [comment]
This will be included in the next release candidate for 3.0. Once that is done (probably next Monday, Feb 15th, 2021), you can try it out using:

`npm install --save-dev style-dictionary@next`

**Comment by dbanksdesign** [comment]
Just released the next release candidate, it should now be available with the `next` tag like @chazzmoney said above
