### ISSUE TITLE
How to use functions from lib/common/formats.js in my custom format?

### ISSUE THREAD

**Issue by notbear** [amzn/style-dictionary#543]
I created and registered my own format. I'd like to reuse fileHeader() and variablesWithPrefix() functions in my implementation. How can I achieve that?

**Comment by chazzmoney** [comment]
This is a great suggestion... we should add a formatHelpers import to provide these (and future) helper functions to make custom formats easier...

**Comment by chazzmoney** [comment]
@notbear this has now been merged and will be part of the 3.0 release. You can check out the documentation [here](https://github.com/amzn/style-dictionary/blob/3.0/docs/formats.md#custom-format-helpers).
