### ISSUE TITLE
Missing TypeScript types

### ISSUE THREAD

**Issue by yoniholmes** [amzn/style-dictionary#545]
Hello!

Thanks so much for sharing this library, nice work! 

I recently tried out using StyleDictionary with TypeScript (on the 3.0 brach), but noticed some missing types. Those are:

1. `parsers` & `transform` on the `Config` interface. This is causing a type error in the `component-cti` example.
2. `registerParser` doesn't have any types defined.
3. The Transform `options` are marked as required, but, again, in the `component-cti` example, these aren't defined, so this is causing a type error.

I'm raising a PR to address these – I thought it best to track these in a ticket.

**Comment by dbanksdesign** [comment]
Thank you for this fix @yoniholmes !
