### ISSUE TITLE
How to alias in values from external files?

### ISSUE THREAD

**Issue by phun-ky** [amzn/style-dictionary#578]
Currently I have separated tokens into their respective package (typo, color, size etc), but how can i alias in `size` into  `typo`? The generation of tokens happens in their respective packages. 

like so, a spacing file at `packages/size:

```json
{
  "size": {
    "spacing": {
      "4": { "value": "0.25rem" }
    }
  }
}
```

That i want to be inherited into this file, at `packages/typography:

```json
{
  "size": {
    "line-height": {
      "4": { "value": "{tokens.size.spacing.4.value}" }
    }
  }
}
```

**Comment by nhoizey** [comment]
Style Dictionary merges all sources before evaluating aliases, so you should be able to write this, without `tokens.`:

```json
{
  "size": {
    "line-height": {
      "4": { "value": "{size.spacing.4.value}" }
    }
  }
}
```

**Comment by phun-ky** [comment]
I'm sorry if I was unclear, all packages has their separate token generation. So your suggestion won't help :(

**Comment by dbanksdesign** [comment]
There are a few ways... For simplicity let's focus on 2 packages, package A and package B. You want to reference a token from package A in package B. 

1) You could export an extended style dictionary from each package. 
The `.extend()` function on Style Dictionary is like creating a new instance of Style Dictionary with the configuration and tokens added into it (from source and include arrays). You can then export this object from one package (package A), import it in another package (package B) and add more tokens and configuration to it. You would need to filter out any tokens not from package A, which can be done with the new `filePath` attribute added in the upcoming version. 

```js
// package A
const StyleDictionary = require('style-dictionary);
module.exports = StyleDictionary.extend({
  source: [`${__dirname}/tokens/**/*.json`],
  //...
});

// package B
const spaceStyleDictionary = require('package-a');

spaceStyleDictionary.extend({
  source: [`${__dirname}/tokens/**/*.json`],
  //...
}).buildAllPlatforms();
```

2) Generate a JSON file of tokens and include it
This is why there is an `include` array in the configuration, if you wanted to include tokens from another package. In package A you can generate a plain JSON file with the [json](https://amzn.github.io/style-dictionary/#/formats?id=json) format. Then in package B you can include that generated file. You will still need to filter out tokens when generating files in package B, but there is another token attribute, `isSource` you can use. 

Hope this helps!

**Comment by chazzmoney** [comment]
@phun-ky does the include functionality meet your needs?

**Comment by chazzmoney** [comment]
@phun-ky I'm closing since it looks like you have what you need. If not, feel free to reopen it.

**Comment by phun-ky** [comment]
@chazzmoney yeah, sorry. haven't tested the proposed solution yet, but will do. I had to manually insert values for the separate pacakges. Thank you :)
