### ISSUE TITLE
Config missing filePath when registering platform.file.filter

### ISSUE THREAD

**Issue by chemoish** [amzn/style-dictionary#581]
I would expect `size.breakpoint.small` (seen below) to have a `filePath` property when registering a filter. However, if a token's value is `0`, `filePath` seems to be missing. 

If the value is changed to `"0"`, everything works as expected.

## Config

```js
files: [{
  filter: (prop) {
    if (prop.filePath) {
      return true;
    }

    console.log(prop);

    return true;
  }
}]
```

## Input

```json
{
  "size": {
    "breakpoint": {
      "small": { "value": 0 },
      "medium": { "value": 600 },
      "large": { "value": 900 },
      "xlarge": { "value": 1200 },
      "xxlarge": { "value": 1920 }
    }
  }
}
```

## Console

```sh
{
  value: '0rem',
  original: { value: 0 },
  name: 'size-breakpoint-small',
  attributes: { category: 'size', type: 'breakpoint', item: 'small' },
  path: [ 'size', 'breakpoint', 'small' ]
}
```

**Comment by dbanksdesign** [comment]
We did a RC release yesterday, so 3.0.0-rc.8 is now available with `npm install style-dictionary@next` and this should be fixed. 🚀

**Comment by dbanksdesign** [comment]
Closing out this issue as it should be fixed now. Feel free to reopen this issue or open a new issue if you are still having this problem. Thanks!
