### ISSUE TITLE
Missing option to remove "Generated on"

### ISSUE THREAD

**Issue by phun-ky** [amzn/style-dictionary#595]
Is there a way to remove "Generated on" ?  When no new design tokens are added or tokens have changed, the generated date is set regardless, making unwanted commits for every build. How can this be avoided?

**Comment by dbanksdesign** [comment]
We just added the ability to define custom file headers in 3.0. If you have the latest RC version (3.0.0-rc.8) you can this feature to define your own file header comment that appears in all files. Here is an example: https://github.com/amzn/style-dictionary/tree/3.0/examples/advanced/custom-file-header 

You could use version number or a hash of the file or remove any dynamic content altogether. Or you could use the `showFileHeader: false` option for file configuration: https://amzn.github.io/style-dictionary/#/config?id=configjson

Hope this helps!

**Comment by phun-ky** [comment]
@dbanksdesign Then I need some more guidance I think. I tested with rc8 now, with this config:

```javascript

const StyleDictionary = require('style-dictionary').extend({
  source: ['./src/tokens/*.json'],
  platforms: {
    scss: {
      transformGroup: 'scss',
      buildPath: 'src/variables/scss/',
      transforms: ['attribute/cti', 'name/cti/kebab', 'time/seconds', 'font/family', 'color/rgb'],
      files: [
        {
          destination: 'variables.scss',
          showFileHeader: false,
          format: 'scss/variables'
        }
      ]
    }
});
```
And I still get generated headers..

**Comment by phun-ky** [comment]
Ah crud, nevermind, the documentation wasn't clear enough regarding where the option would be:

```javascript

const StyleDictionary = require('style-dictionary').extend({
  source: ['./src/tokens/*.json'],
  platforms: {
    scss: {
      transformGroup: 'scss',
      buildPath: 'src/variables/scss/',
      transforms: ['attribute/cti', 'name/cti/kebab', 'time/seconds', 'font/family', 'color/rgb'],
      files: [
        {
          destination: 'variables.scss',
          options: { showFileHeader: false },
          format: 'scss/variables'
        }
      ]
    },
    });
```

**Comment by dbanksdesign** [comment]
That is good feedback, I will try to make the documentation more clear about where that option goes. Thanks!
