### ISSUE TITLE
Complete android sample is quite outdated

### ISSUE THREAD

**Issue by mkovalyk** [amzn/style-dictionary#601]
Sample from https://github.com/amzn/style-dictionary/tree/3.0/examples/complete/android looks to be quite outdated. It:
- targets and compiles with API 25.
- referencing to build tools 25.*.*
- uses deprecated support libraries
- uses Java

**Comment by dbanksdesign** [comment]
Thank you for raising this. You are correct the complete example for Android (and iOS and web) are quite outdated.

**Comment by mkovalyk** [comment]
I have created PR to resolve it. It would be nice if someone could merge it in. Thanks!

**Comment by dbanksdesign** [comment]
Thank you for your contribution! This is now merged into the 3.0 branch and released in 3.0.0-rc.9!
