### ISSUE TITLE
Exclude tokens from export

### ISSUE THREAD

**Issue by withinsight** [amzn/style-dictionary#606]
Is it possible to exclude tokens per export format? For example, all global tokens from our sass output, in order to force users to use alias tokens?

**Comment by dbanksdesign** [comment]
It is! The way to do that is with [filters](https://amzn.github.io/style-dictionary/#/formats?id=filtering-tokens). You can add/use a filter in a number of ways:
* Registering a filter with the `registerFilter` method
* Passing in an object that uses lodash's `filter` method
* Directly as a function in the file configuration:

```javascript
StyleDictionary.extend({
  source: [],
  platforms: {
    scss: {
      transformGroup: 'scss',
      files: [{
        destination: 'colors.scss',
        format: 'scss/variables',
        filter: (token) => token.attributes.category === `color`,
      }]
    }
  }
});
```

Note that filter is *inclusive* meaning if the function returns `true` for a token it will be included, if it is `false` it will be excluded. This works just like Array.prototype.filter in Javascript. 

In the upcoming version (3.0) of style dictionary we are also adding some [extra metadata](https://amzn.github.io/style-dictionary/#/version_3?id=adding-filepath-and-issource-entries-on-tokens) to all tokens you can use for filtering:
* `filePath` the file path of the file the token was defined in
* `isSource` if the token was defined in the `source` array as opposed to `include` array

You can get a pre-release of 3.0 today with `npm install style-dictionary@next`

**Comment by chazzmoney** [comment]
@withinsight Did we answer your question? Or did you have further inquiries?

**Comment by withinsight** [comment]
It did, thank you!
