### ISSUE TITLE
Allow other selectors than ":root" in css output format 

### ISSUE THREAD

**Issue by alirezamirian** [amzn/style-dictionary#626]
Right now, there is no option for changing the selector, and it's hard coded to `:root`:
https://github.com/amzn/style-dictionary/blob/a88e622bcc06a98972dddb2b11903828ba3dab2b/lib/common/formats.js#L111

It would be nice to have an option for it. It especially helps in the context of having multiple themes.

**Comment by dbanksdesign** [comment]
This is a great suggestion. So great in fact that it is actually available in the upcoming version (3.0)! You can get access to a pre-release version with `npm install style-dictionary@next`. Here is the pull request we added that feature in: #582

**Comment by alirezamirian** [comment]
Ah, didn't know about it, and already opened a PR for it 😄
Thanks for responding
