### ISSUE TITLE
HAPPY 3.0, Style Dictionary! 🎉

### ISSUE THREAD

**Issue by chazzmoney** [amzn/style-dictionary#638]
I just thought it would be fun to make an issue to celebrate.

Thank you to everyone in the community who has helped us continue to improve Style Dictionary!

To 4.0 and beyond! 🚀

**Comment by dbanksdesign** [comment]
Release notes:
https://github.com/amzn/style-dictionary/releases/tag/v3.0.0

![yas](https://media.giphy.com/media/2116PkgyWRPz2/giphy.gif "Yas"))
