### ISSUE TITLE
OutputReferences for json formats

### ISSUE THREAD

**Issue by lewishealey** [amzn/style-dictionary#646]
I have a requirement to visually display our outputted tokens in somewhere like storybook. It's beneficial for our design team to see the references to the original token, is it possible to get outputReferences for json formats?

**Comment by dbanksdesign** [comment]
@lewishealey did you figure this out? What you can do if you want to output tokens for use in documentation you can use the `json` format which will output the entire token objects which contain the original token which will contain the reference (along with other metadata about the token).
