### ISSUE TITLE
Custom format add a space before the carriage return

### ISSUE THREAD

**Issue by bhdicaire** [amzn/style-dictionary#660]
My repository is [here]( https://github.com/dicaire/designTokens ).

I have a created a custom format to generate a text file with the hex color code and the color name. However, the output generate a space before the carriage return when I'm returning _`${token.value} ${token.name}`).join("\n");_ in my custom format and NOT if I swap the items to _`${token.name} ${token.value}`).join("\n");._

I'll like to remove the whitespace before the carriage return and I'll need help.
--------------------------------------
The text file (ouput/colorPalette.txt) look like this:
#ffffff white[space here]
#1d1f24 black[space here]
#000000 pure-black[space here]
...

My custom format (./config.js) look like this:
StyleDictionary.registerFormat({
  name: "colorPalette",
  formatter: function({ dictionary, file }) {
    return dictionary.allTokens.map(token => `${token.value} ${token.name}`).join("\n");
  }
});

The platform item (./config.js) look like this:
    colorPalette: {
      transforms: ["attribute/cti", "name/human", "color/hex"],
      buildPath: "output/",
      files: [{
        format: "colorPalette",
        destination: "colorPalette.txt",
        options: {
          "showFileHeader": false
        },
        filter: {
          attributes: {
            category: "color",
            type: "palette"
           }
        }
     }]
    },

The YML color palette (output/colors/colorrPalette.yml) look like this:
color:
  palette:
    "white":
      value: "ffffff"
    black:
      value: "1d1f24"
      comment: "It's easier on the eyes than pure black"
    pure-black:
      value: "000000"
...

**Comment by chazzmoney** [comment]
I played with your repo. Looks like it is due to the [name/human transform](https://github.com/dicaire/designTokens/blob/main/config.js#L59). Remove that and you should be good.

**Comment by bhdicaire** [comment]
Thank you very much @chazzmoney

**Comment by bhdicaire** [comment]
Comprehension error by the user and fixed by @chazzmoney.

Modified the transform from  transforms: ["attribute/cti", "name/human","color/hex"], to transforms: ["attribute/cti", "color/hex"],
