### ISSUE TITLE
basePxFontSize is not documented

### ISSUE THREAD

**Issue by equinusocio** [amzn/style-dictionary#663]
hello, i just found a text mentioning a `basePxFontSize` configuration which is not documented anywhere inside the doc. This is really useful to use inside custom transforms and it should be documented.

**Comment by langsmith** [comment]
Yes, would be great to have documentation for this. I'm trying to understand where to set a custom `basePxFontSize` but can't find any docs/examples.

cc @dbanksdesign

**Comment by equinusocio** [comment]
@langsmith I found how to use it by checking the lib source code. You have to define it inside the platform object:

```
  "platforms": {
    "web": {
      "basePxFontSize": 18,
```

**Comment by langsmith** [comment]
Excellent, @equinusocio ! Thanks

**Comment by dbanksdesign** [comment]
Thank you for bringing this up! We definitely need to fix the documentation about this as it is sparse and inconsistent. Some transform descriptions like https://amzn.github.io/style-dictionary/#/transforms?id=sizeremtodp mention `basePxFontSize` and others don't. I'm thinking we should add a section on the transforms page about platform configurations that affect transforms like `basePxFontSize`. Another one is `prefix` which affects name transforms. Then also updating the descriptions in the JSDoc comments for the size transforms that use basePxFontSize to be consistent. 

What are your thoughts? If anyone would like to submit a PR for this that would be great or we can try to do hopefully sometime soon.

**Comment by chazzmoney** [comment]
Thanks for solving @spirkolos !

🥳
