### ISSUE TITLE
Tokenizing animation and keyframes

### ISSUE THREAD

**Issue by chemoish** [amzn/style-dictionary#664]
Hello! I wasn't able to find any information on how keyframes and animation might be handled (more than just duration and easing values).

* How are people tokenizing complex animation?
* Does style dictionary have a recommendation?

**Example:**

https://github.com/amzn/style-dictionary/blob/a88e622bcc06a98972dddb2b11903828ba3dab2b/examples/advanced/create-react-app/src/App.scss#L23

https://github.com/amzn/style-dictionary/blob/a88e622bcc06a98972dddb2b11903828ba3dab2b/examples/advanced/create-react-app/src/App.scss#L45-L52

**Comment by dbanksdesign** [comment]
Thank you for bringing this up! We don't have any recommendation right now for how to handle keyframes and animation. I would love to hear if others have tackled this challenge and maybe we could build a recommendation.

**Comment by chemoish** [comment]
I decided to go with a very basic implementation, based on convention, with no transformations. The assumption is that keyframes will hold `<keyframe-selector>: { <declaration-list> }`. I don't know how this will scale to other platforms, but I will iterate as they are onboarded.

```js
animation: {
  delay: { value: "" },
  direction: { value: "" },
  iterationCount: { value: "" },
  timing: { value: "" },

  keyframes: {
    from: {
      color: "white",
    },
    to: {
      color: "hotpink",
    },
  },
} 
```

**Comment by ng-model** [comment]
before i ask this question, we love `style-dictionary` your contributions and examples are awesome.
 @didoo or @dbanksdesign Is there a way to get key-frames generated using SD, or we need to write custom config to start
