### ISSUE TITLE
Bug fix: Convert nested calcs to parenthesis to support ie

### ISSUE THREAD

**Issue by CodeByAlex** [amzn/style-dictionary#671]
IE doesn't support nested calcs in css. Would it be possible to replace all calcs within a parent calc with parenthesis during variable  generation so we can use the variables across all browsers. All browsers understand parenthesis within a calc function.

See the spec here:
https://developer.mozilla.org/en-US/docs/Web/CSS/calc()

**Comment by chazzmoney** [comment]
I'm a bit unsure how this is cropping up for you. Can you share more about what your dictionary files and configuration?

**Comment by CodeByAlex** [comment]
So in the example below we have a calc function call that leverages another token
"padding":{
                "value":"calc({test.spacer.value}*2)"
 },

If test.spacer.value also uses calc, the value of padding will include nested calcs.

**Comment by chazzmoney** [comment]
I'm not sure how best to achieve this. Maybe a new transform?

If you have something in mind, we would love a PR / would love to hear suggestions.

**Comment by chazzmoney** [comment]
@dbanksdesign suggestions?

**Comment by chazzmoney** [comment]
For clarity, this is not an SD issue in my opinion, but an issue with the confluence CSS, the dictionary values, and reference chains. However, it can be solved by someone with commitment to the problem via a formatter or transform solution that could be utilized within the SD realm.

**Comment by c3-andrewkim** [comment]
@CodeByAlex Hey Alex how did you go about solving for this? I'm also facing issues with nested calcs in the resulting build scss file generated by styledictionary. 

I'm attempting to generate font sizes strictly based on a baseTextSize and a scalingratio variable.
`"03" : {
          "value": "calc({font.size.04} / {font.size.majorSecondScale})",
          "comment": "the large size of the font"
        },
        "04" : {
          "value": "{font.size.baseTextSize}",
          "comment": "the large size of the font"
        },
        "05" : {
          "value": "calc({font.size.04} * {font.size.majorSecondScale})",
          "comment": "the large size of the font"
        },`
