### ISSUE TITLE
Compiler for transparent values?

### ISSUE THREAD

**Issue by brycesnyder** [amzn/style-dictionary#672]
I'm not sure if this is supported. I am looking for a way to convert transparent to the android equivalent of @android:color/transparent within the xml etc.

Is there anyway to specify this? And example would be a button that has a transparent background.

`{ button: { background: { value: "transparent" } } }`

To be able to compile out to css

`$buttonBackground: transparent;`

and android or ios with their required format.

**Comment by dbanksdesign** [comment]
The built-in transforms do _technically_ work with the 'transparent' keyword for colors. The output might not be exactly what one would expect though. For color transformations we pass the color value to the tinycolor2 library, which accepts any CSS color keywords like 'transparent' or 'teal'. From there we output a hex or rgba value depending on the platform. For android this would be `#00000000` and CSS would be `rgba(0,0,0,0)`  (black with 0% opacity). So it won't output the keyword 'transparent', but still be in effect the same thing. Here is a quick example of that:

https://stackblitz.com/edit/style-dictionary-example-6typ1a?file=config.js

**Comment by chazzmoney** [comment]
If you have further questions, feel free to re-open.
