### ISSUE TITLE
`className` missing from `File` type

### ISSUE THREAD

**Issue by alexsurelee** [amzn/style-dictionary#684]
Currently, `className` is missing from the `File` object, meaning that if you are using a TypeScript configured project you may be missing some config. For example, the `ios-swift` format seems to require the `className` to be provided, else the class generated will be missing the name entirely. 

This can normally be provided in a `json` configured project, e.g. https://github.com/amzn/style-dictionary/blob/main/examples/complete/config.json#L14

**Comment by dbanksdesign** [comment]
Fixed! Thank you so much!
