### ISSUE TITLE
Ability to supress filtered out reference warnings

### ISSUE THREAD

**Issue by lennartbuit** [amzn/style-dictionary#687]
(Great tool, btw!)

We split the output of style dictionary into multiple files with a filter as demonstrated in the [matching-build-files](https://github.com/amzn/style-dictionary/tree/main/examples/advanced/matching-build-files) example. Furthermore, we also have a custom export to scss/styled components that properly generates imports for those splitted files like this:

<img width="449" alt="Screenshot 2021-08-26 at 15 20 29" src="https://user-images.githubusercontent.com/37534243/130969838-db11d125-a3c9-4697-ad76-6afe92f7d7e3.png">

So all is well, except that style dictionary continues to warn us that using a filter + output references can cause issues:

```
While building _toggle.scss, filtered out token references were found; output may be unexpected. Here are the references that are used but not defined in the file
```

Even if I lie to style dictionary, and turn `outputReferences: false`, it still continues to warn me.

For us it would be desirable to turn off the warning (or, better, tell style dictionary that everything is actually okay!). How could we accomplish that?

**Comment by chazzmoney** [comment]
Also in #688

**Comment by jakobe** [comment]
Hey, I can chip in here, as we're doing something similar to @lennartbuit.

In our approach we are rendering individual css files for each component in a component library and are referring to css variables inside those css declarations. As we do not want every component to include all the tokens/css vars referenced, we also output a global stylesheet that contains the css vars definitions of all the references (using the built in `css/variables` formatter).

To me there are 3 things to consider before warnings about the filtered out references:
1. If we don't `outputReferences` the warnings should be supressed
2. If we `outputReferenceFallbacks` the warning should be supressed (as we in that case already are outputting fallback values for each css var created, hence the css var/reference doesn't need to be defined)
3. If we DO `outputReferences` but DON'T `outputReferenceFallbacks` we should have a configuration option to supress the warning, i.e. telling SD "Don't worry, I know what I'm doing" (e.g. by outputting the references/css vars in a separate file as in @lennartbuit  and our case)

As far as I can see this could be achieved in [buildFile.js](https://github.com/amzn/style-dictionary/blob/main/lib/buildFile.js) using the existing `outputReferences` and `outputReferenceFallbacks` options and adding a new `supressfilteredReferencesWarnings` option:

```js
const { outputReferences, outputReferenceFallbacks, supressfilteredReferencesWarnings } = file.options || {};
if (filteredReferencesCount > 0 && (outputReferences && !outputReferenceFallbacks && !supressfilteredReferencesWarnings)) {
  let filteredReferencesWarnings = GroupMessages.flush(GroupMessages.GROUP.FilteredOutputReferences).join('\n    ');
  let title = `While building ${chalk.keyword('orangered').bold(destination)}, filtered out token references were found; output may be unexpected. Here are the references that are used but not defined in the file`;
  let help = chalk.keyword('orange')([
    'This is caused when combining a filter and `outputReferences`.',
  ].join('\n    '));
  let warn = `${title}\n    ${filteredReferencesWarnings}\n${help}`;
  console.log(chalk.keyword('darkorange').bold(warn));
}
```

**Comment by jakobe** [comment]
> Also in #688

@chazzmoney I see this is related, but to me that's a more general issue about supressing warnings where as this issue is specifically about outputting references.

**Comment by mel-miller** [comment]
+1 for @jakobe's proposal. We have a custom way to reference internal tokens on output and would love to be able to suppress this warning since I know it's not an issue in our system.

**Comment by kwickramasekara** [comment]
+1 👀

**Comment by jorenbroekema** [comment]
It's now possible in v4 to configure the logging behavior, making these logs less verbose by default and allowing you to disable warning logs altogether.

This PR: also adds a feature that should allow you to ensure tokens containing filtered out references will not output references but resolved values instead. This should be somewhat of an improvement over using outputReferenceFallbacks if you want to save some bytes of CSS.

We're working on the new v4 docs, soon there will be a button on the v3 docs to visit the v4 docs which has docs on how to configure the logging, but for now you could check out https://github.com/amzn/style-dictionary/blob/v4/CHANGELOG.md or the docs folder https://github.com/amzn/style-dictionary/blob/v4/docs/src/content/docs/reference/logging.md
