### ISSUE TITLE
StyleDictionaryButton doesnt exist file.

### ISSUE THREAD

**Issue by MarcosiOSdev** [amzn/style-dictionary#692]
Hello . 

When I will try the iOS sample in complete example. 

There arent `StyleDictionaryButton.h`

**Comment by chazzmoney** [comment]
I'll give it a shot, but the file appears to be present and in the correct location.

https://github.com/amzn/style-dictionary/blob/main/examples/complete/ios/Classes/StyleDictionaryButton.h

**Comment by MarcosiOSdev** [comment]
It didn't come in my git clone.

Thank you !
