### ISSUE TITLE
Load filters, formats and transformers from other files

### ISSUE THREAD

**Issue by lukasoppermann** [amzn/style-dictionary#693]
Hey,

I would love to extract my filters & co into separate files. This also makes it easy to share them as modules.
E.g. you could create an android FontSize transformer and share it. Maybe they could even be added to this repo via merge requests.

However, currently I create them like this:

```js
StyleDictionary.registerTransform({
  name: 'android/fontSizes',
  type: 'value',
  matcher: function (token) {
    return token.type === 'dimension' && token.data.category === 'font'
  },
  transformer: function (token) {
    return `${token.value}sp`
  }
})
```

Is there a way to load this code from another file into my build.js?

Or do I need to create a function and do this in my build.js:

```js
StyleDictionary.registerTransform(androidFontSizeTransformer())
```
While this would be a workaround, it would be neat to be able to just import a file with the definitions without setting up every Transform in the build.js file.

**Comment by dbanksdesign** [comment]
There is actually! The configuration object that is passed to `.extend()` can actually include custom filters, transforms, transformGroups, formats, etc.

Take a look at this demo: https://stackblitz.com/edit/style-dictionary-example-ctyyuj?file=config.js

If you add a `transform` object in your config where the keys of the object are the transform names, you can add custom transforms without calling `.registerTransform()`. You can do this with any custom functions you would normally use register functions for. 

This also means that you could export a package of transforms, formats, etc. that other people could consume.

```js
module.exports = {
  transform: { /* transforms */ },
  format: { /* formats */ }
}
```

```js
const StyleDictionaryPlugin = require('style-dictionary-plugin');

module.exports = {
  ...StyleDictionaryPlugin,
  source: [],
  platforms: {
  // ...
  }
}
```

**Comment by dbanksdesign** [comment]
You can also take a look at this example: https://github.com/amzn/style-dictionary/blob/main/examples/advanced/node-modules-as-config-and-properties/config.js

**Comment by dbanksdesign** [comment]
And this RFC issue describes the plugin architecture: https://github.com/amzn/style-dictionary/issues/311

**Comment by lukasoppermann** [comment]
🤦‍♂️ how did I miss this. Thank you very much.

Is the `extend` version implemented? Could I have three files: `ios.ts`, `android.ts`, `web.ts`, each with an exported module:

```js
export default {
  transform: { /* transforms */ },
  format: { /* formats */ }
}
```

And in my `build.js` just run:
```js
import ios from './ios'
import android from './android'
import web from './web'

StyleDictionary
  .extend( ios )
  .extend( android )
  .extend( web )
```

Or does this not work yet?

**Comment by dbanksdesign** [comment]
That should work! (I've never tried running Style Dictionary with typescript files, but as long there are no typescript issues running Style Dictionary it should work)

**Comment by lukasoppermann** [comment]
Great, got all working. I opted for importing multiple configs (iOS, Android, Web) and doing a deepMerge on the objects.

So within my build.js it looks like this:

```js
const deepMerge = require('deepmerge')
const StyleDictionary = require('style-dictionary')
const androidConfig = require('./libs/android')
const iosConfig = require('./libs/ios')
const webConfig = require('./libs/web')

const StyleDictionaryExtended = StyleDictionary.extend({
  // adding imported configs
  ...deepMerge.all([androidConfig, iosConfig, webConfig]),
  source: ['./tests/files/standard-tokens.json'],
  // ...
 ```
 
 Thanks for the help @dbanksdesign
