### ISSUE TITLE
How to access the full dictionary in registerTransform ?

### ISSUE THREAD

**Issue by silversonicaxel** [amzn/style-dictionary#701]
Pretty simple question, I'm registering a transformation and the transformer need one item, actually one design token, that lives in the same file I'm applying this transformation.
So I would need to access the `dictionary.properties` to retrieve this element via its `name`, used to transform all the others.

```
    this.#handler.registerTransform({
      name: 'my/size/transform',
      type: 'value',
      matcher: (prop) => {
        return prop?.attributes?.category === 'size'
      },
      transformer: (prop, options) => {
        return parseFloat(prop.original.value) + [A DESIGN TOKEN DATA COMING FROM DICTIONARY];
      }
    })
```
in `transformer` I've access only to `prop` and `options`, not enough and I don't think it is information available in `this.#handler` too (to clarify `this.#handler = require('style-dictionary')`)
is it possible to have access to this info? 
thanks

**Comment by silversonicaxel** [comment]
I found out this approach, since there is the `prop.filePath` information, I read it directly from file system and parse it as an object.
It works, I don't see substantial decrease of performances (because this access is done in a loop), but it works:


```
    this.#handler.registerTransform({
      name: 'my/size/transform',
      type: 'value',
      matcher: (prop) => {
        return prop?.attributes?.category === 'size'
      },
      transformer: (prop) => {
        const dictionary = JSON.parse(
          fs.readFileSync(prop.filePath).toString()
        )
        return parseFloat(prop.original.value) + dictionary['design-token-to-fetch'].value;
      }
    })
```

Maybe like this to reduce the file system access:

```
    let dictionary: any

    this.#handler.registerTransform({
      name: 'my/size/transform',
      type: 'value',
      matcher: (prop) => {
        return prop?.attributes?.category === 'size'
      },
      transformer: (prop) => {
        dictionary ??= JSON.parse(
          fs.readFileSync(prop.filePath).toString()
        )
        return parseFloat(prop.original.value) + dictionary['design-token-to-fetch'].value;
      }
    })
```


Better ideas are more than welcome!

**Comment by dbanksdesign** [comment]
We don't allow access to the dictionary within a transformer because when that transformer is run, the dictionary could be in any number of states depending on which other tokens have been transformed and/or resolved. You wouldn't get a deterministic result because the transforms modify the dictionary. 

As a workaround, what you have works. You could also read/import your token files outside of Style Dictionary and pass it to the Style Dictionary configuration and custom transform, psuedo code:

```javascript
// config.js

const tokens = fs.readFileSync();
// or
// const tokens = require('./tokens/);

module.exports = {
  tokens: tokens,
  transform: {
    myTransform: {
      type: 'value',
      transformer: (token) => {
        // do something with the tokens object
      }
    }
  //...
}
```

**Comment by silversonicaxel** [comment]
Indeed it could be read just once instead of every time I need it for a `transform` function.
Still, the workaround I implemented works without a particular time increase.
But thanks for answering and giving an extra answer.

**Comment by bennypowers** [comment]
This feature is handy for polyfilling DTCG recommendations, particularly, group-level token types.

Here's my implementation of the community group's `$type` spec. It's not perfect for the above-cited reasons, but assuming no dynamic shenanigans, it works:

```yaml
breakpoint:
  $type: dimension

  2xs:
    value: 575px
    comment: Corresponding to mobile portrait
  xs:
    value: 767px
    comment: Corresponding to mobile landscape
  sm:
    value: 991px
    comment: Corresponding to tablet portrait
  md:
    value: 1199px
    comment: Corresponding to tablet landscape
  lg:
    value: 1439px
    comment: Corresponding to small desktop
  xl:
    value: 1679px
    comment: Corresponding to medium desktop
```

```js
// /lib/sources.js
import YAML from 'yaml';
import { readFile } from 'node:fs/promises';
import { promisify } from 'node:util';
import { fileURLToPath } from 'node:url';

import g from 'glob';
import deepmerge from 'deepmerge';

const glob = promisify(g);

const cwd = fileURLToPath(new URL('../tokens/', import.meta.url));

const files = await glob('**/*.y?(a)ml', { absolute: true, cwd });

const parsed = await Promise.all(files.map(async x => YAML.parse(await readFile(x, 'utf8'))));

/** merged static tokens sources files */
export const sources = deepmerge.all(parsed);
```

```js
// lib/transforms/dtcg.js
/**
 * Inherits `$type` per Design Tokens Format Module
 * @type {Transform}
 * @see https://design-tokens.github.io/community-group/format/#type-0
 */
export const typeNested = {
  name: 'dtcg/type/nested',
  type: 'attribute',
  transitive: true,
  transformer: token => {
    token.$type ??= token.path.reduceRight(($, name) => $ ?? sources[name]?.$type, null);
    if (token.$type == null) {
      delete token.$type;
    }
    return token.attributes;
  },
};
```

```js
// build.js
StyleDictionary
  // yadda yadda
  .registerTransform(DTCGTransforms.typeNested)
  .registerTransformGroup(TransformGroups.css) // includes dtcg/type/nested
  // yadda yadda
```

**Comment by jorenbroekema** [comment]
```js
import StyleDictionary from 'style-dictionary';

const sd = new StyleDictionary(config);
await sd.hasInitialized;
const tokens = sd.tokens;

// you can use the tokens object in the transform now
// recommended is to register it on the instance level, to avoid confusion
sd.registerTransform(...);
```

As for handling token group level $type, see https://styledictionary.com/reference/utils/dtcg/ for DTCG related utils, there's one for delegating the group level $type's to the token level and also one for converting it back to DTCG and distilling $type's to the farthest common ancestor in the object
