### ISSUE TITLE
Auto-rebuild-watcher watches wrong folder properties rather than tokens

### ISSUE THREAD

**Issue by JackHowa** [amzn/style-dictionary#705]
- Have fix but wasn't sure if this was intended https://github.com/JackHowa/auto-rebuild-watcher-scss-css/blob/main/package.json#L13
- https://github.com/amzn/style-dictionary/blob/main/examples/advanced/auto-rebuild-watcher/package.json#L13

**Comment by dbanksdesign** [comment]
Good catch! You are right `properties` in that npm script should be changed to `tokens`

**Comment by chazzmoney** [comment]
Thanks @JackHowa for the heads up!

**Comment by JackHowa** [comment]
no worries -- good work all @chazzmoney @dbanksdesign
