### ISSUE TITLE
attribute/color transform output

### ISSUE THREAD

**Issue by nrakochy** [amzn/style-dictionary#710]
Hi there, 

Thanks for the great library 👍 . I am trying to add a new config entry which outputs to `json`, and I can't seem to get [attribute/color](https://amzn.github.io/style-dictionary/#/transforms?id=attributecolor) to work. Given this palette

```js
const color = {
    white: { value: "#ffffff" },
    black: { value: "#000000" }
}
```

and this config
```js
 {
    transforms: ["attribute/color"],
    buildPath: `src/`,
            files: [
                {
                    destination: `ye-olde-variables.json`,
                    format: "json/flat",           //-> json/nested does not transform either
                }
            ]
}
```

I get this JSON output
```js
{
  "white": "#ffffff",
  "black": "#000000",
}
```

whereas the docs seems to indicate I could get something like this 
```js
{
  "hex": "009688",
  "rgb": {"r": 0, "g": 150, "b": 136, "a": 1},
  "hsl": {"h": 174.4, "s": 1, "l": 0.294, "a": 1},
  "hsv": {"h": 174.4, "s": 1, "l": 0.588, "a": 1},
}
```

Is there any additional config which is necessary to use the `attribute/color` transform? Any help would be greatly appreciated. Many thanks.

**Comment by gearsandcode** [comment]
Your token needs token.attributes.category.

**"// Matches: token.attributes.category === 'color'"**

``{
  color: {
    white: {
      value: "#ffffff`,
      attributes: {
        category: "color"
      }
    }
  }``

**Comment by nrakochy** [comment]
🤦 Ah! I assumed the attribute was picked up by the nested JS format of `{color: {white: ...}}`. Thanks for your help.
