### ISSUE TITLE
[Question] Can I generate extensions in iOS Swift?

### ISSUE THREAD

**Issue by antoniogamiz** [amzn/style-dictionary#719]
Hi, I have been using Style Dictionary and it's great! Thanks a lot for the hard work.

I have a question. I have the following configuration file to generate styles sheets on iOS Swift from design tokens hosted on Invision App:

~~~json
{
  "source": [
    "tokens/**/*.json"
  ],
  "platforms": {
    "ios-swift-separate-enums": {
      "transformGroup": "ios-swift-separate",
      "buildPath": "build/ios-swift/",
      "files": [
        {
          "destination": "StyleDictionaryColor.swift",
          "format": "ios-swift/enum.swift",
          "className": "StyleDictionaryColor",
          "filter": {
            "attributes": {
              "category": "color"
            }
          }
        },
        {
          "destination": "StyleDictionarySize.swift",
          "format": "ios-swift/enum.swift",
          "className": "StyleDictionarySize",
          "type": "float",
          "filter": {
            "attributes": {
              "category": "size"
            }
          }
        }
      ]
    },
  }
}
~~~

The result is something like this:

~~~swift
import UIKit

public enum StyleDictionaryColor {
    public static let basicGrayDark = UIColor(red: 0.345, green: 0.345, blue: 0.345, alpha: 1)
    public static let basicGrayDark60 = UIColor(red: 0.000, green: 0.000, blue: 0.000, alpha: 0.6)
}

~~~

But, I would like to generate something like this: 

~~~swift
extension Color {
    static let oldPrimaryColor = Color(UIColor.systemIndigo)
    static let darkGreyColor = Color("darkGrey")
}
~~~

Is that currently possible? Or would I need to create my own transformer? Thanks in advance (if this is not the place for this type of question, please redirect to the correct place if you which is, thanks! :))

**Comment by antoniogamiz** [comment]
Okay, I will try to implement it in the near future! Thanks for the fast response :smiley: .

**Comment by antoniogamizbadger** [comment]
PR made for the SwiftUI Color transformer, let me now if I need change something.

**Comment by tfmart** [comment]
In case anyone wants an example on how to create a Swift extension file, on your iOS swift file object in `config.json`, use `ios-swift/any.swift` as the format and add a `options` object, in which you can provide a `objectType` with a `extension` value. Here's an example:
```json
{
  "source": [
    "tokens/**/*.json"
  ],
  "platforms": {
    "ios-swift": {
      "transforms": [
        "..."
      ],
      "buildPath": "files/ios-swift/",
      "files": [
        {
          "destination": "MyCustomSpacing.swift",
          "format": "ios-swift/any.swift",
          "className": "CGFloat",
          "filter": "foundation/spacing",
          "options": {
            "objectType": "extension"
          }
        }
      ]
    }
  }
}
```

**Comment by colinhumber** [comment]
@tfmart I'm doing the same thing and it's working great. Shouldn't need any custom formats or templates for this.

**Comment by jorenbroekema** [comment]
Closing question issue, considered as answered.
