### ISSUE TITLE
static-style-guide template css files not included

### ISSUE THREAD

**Issue by dbanksdesign** [amzn/style-dictionary#72]
The 'static-style-guide/index.html' template has references to external css files here:

https://github.com/amzn/style-dictionary/blob/master/lib/common/templates/static-style-guide/index.html.template#L42

But we don't include those css files. We should package these files up somehow or reference raw files in our github repo or something. Open to ideas.

**Comment by davixyz** [comment]
It seems that you are using those just to style the static example stie; Maybe you can inline only the styles you see as a general and dynamically add the other CSS based on config

**Comment by dbanksdesign** [comment]
After some discussion, I think it is best to remove this as a template. The static style guide is available as an [example](https://github.com/amzn/style-dictionary/tree/master/example/complete). It doesn't make as much sense to have this as a template as it is not very generic. Having hardcoded css is probably not great because users could not modify it to their needs. 

What I think would be helpful is a fully baked style dictionary example with a style guide site, and tied into web/iOS/Android apps. 

Open to other thoughts though.

**Comment by mix3d** [comment]
I came across style-dictionary hoping for an auto style-guide generator, so I would certainly recommend having a more fully baked example. 

The video on the style-dictionary homepage was cool but misleading, especially since the demo website had all the sectioned headers that matched the dict's sections, so I just assumed.

**Comment by dbanksdesign** [comment]
Yea, I've been working on getting the code in the demo video ready to be released, but it's still in progress. I know I really need to finish it. 

If you want a starter static html style guide, you can use the 'complete' example, `style-dictionary init complete`. That has an html style guide in there. You can take a look at it in here: https://github.com/amzn/style-dictionary/tree/master/example/complete

**Comment by dbanksdesign** [comment]
Fixed in #157
