### ISSUE TITLE
Kotlin Support for Jetpack Compose

### ISSUE THREAD

**Issue by brycesnyder** [amzn/style-dictionary#728]
Just wondering if there is any support for Kotlin variables or if there is any plan to support it?

**Comment by bherbst** [comment]
There is indeed support for Compose!

There's a [`compose/object` format](https://amzn.github.io/style-dictionary/#/formats?id=composeobject) and a [`compose` transform group](https://amzn.github.io/style-dictionary/#/transform_groups?id=compose) that should get you most of what you need.

**Comment by brycesnyder** [comment]
@bherbst, thank you for this! Are there any examples of the config with it leveraged anywhere? I didn't see anything within the advanced examples.

**Comment by bherbst** [comment]
Yep! The basic sample uses `compose/object`.

Config: https://github.com/amzn/style-dictionary/blob/1fe585f196211200b3de671a941aae9b87e1163b/examples/basic/config.json#L23-L35
