### ISSUE TITLE
Tokens with aliases don't get transformed

### ISSUE THREAD

**Issue by bytelabsco** [amzn/style-dictionary#736]
I'm sure I'm doing something wrong here.  I looked through existing issues, and saw a few posts referencing aliased values not being run through custom transforms.  However, I'm attempting to use out of the box transforms (specifically `size/rem`).  I assume the process is the same, but those previous tickets seemed to allude to this being fixed in Style-Dictionary 3.0+

At any rate, here's what I'm trying to do.  I have a base configuration where I define a scale that I would like to be transformed into 'numbers' in the output (so I can use this scale downstream to create things like utility classes).  That looks something like this:

`tokens/base/base.json`
````
{
    "base": {
        "size": {
            "scale": {
                "100": { "value": 0.5 },
                "200": { "value": 1 },
                "300": { "value": 1.5 },
                "400": { "value": 2 },
                "500": { "value": 2.5 },
                "600": { "value": 3 },
                "700": { "value": 3.5 },
                "800": { "value": 4 },
                "900": { "value": 4.5 }
            }
        }
    }
}
````

I want to use this scale, exactly as is to generate the 'standard' size scale, which normally has 'rem' appended using the `size/rem` transform.  So I have this:

`tokens/size/scale.json`
````
{
    "size": {
        "scale":{
            "100": { "value": "{base.size.scale.100.value}" },
            "200": { "value": "{base.size.scale.200.value}" },
            "300": { "value": "{base.size.scale.300.value}" },
            "400": { "value": "{base.size.scale.400.value}" },
            "500": { "value": "{base.size.scale.500.value}" },
            "600": { "value": "{base.size.scale.600.value}" },
            "700": { "value": "{base.size.scale.700.value}" },
            "800": { "value": "{base.size.scale.800.value}" },
            "900": { "value": "{base.size.scale.900.value}" }
        }
    }
}
````

However, that simply duplicates the base.size.scale output (as integers), but with size-scale variable name prefixes.  It does not appear to actually run through the `size/rem` transform.  I've even tried adding `"attributes": { "category": "size" }` to the token definition, but there is no change.

I've also tried this by converting all JSON to JavasScript, as well as trying to introduce my own transform/transformGroup (which still runs into the same issues that those previously mentioned tickets do).

I must have missed something in the documentation that shows me how to correctly do this.  Any pointers?

**Comment by chazzmoney** [comment]
Hi @bytelabsco 

Can you share your configuration file as well? It will help determine the source of the issue. Thanks!

**Comment by martikaljuve** [comment]
According to the [size/rem](https://amzn.github.io/style-dictionary/#/transforms?id=sizerem) documentation, the transform only applies to tokens where "category" is "size":

> Matches: token.attributes.category === 'size'

With your current structure in `tokens/base/base.json`, [attribute/cti](https://amzn.github.io/style-dictionary/#/transforms?id=attributecti) will set `token.attributes.category` to "base". 

Maybe you could swap the 1st and 2nd levels, e.g:

```json5
// tokens/base/base.json
{
    "size": {
        "base": {
            "scale": {
                /../
            }
        }
    }
}

**Comment by martikaljuve** [comment]
You could also turn the built-in "size/rem" transform into a "[transitive](https://amzn.github.io/style-dictionary/#/version_3?id=transitive-transforms)" one, as in this example: https://github.com/amzn/style-dictionary/blob/main/examples/advanced/transitive-transforms/sd.config.js#L40-L44

```js
// style-dictionary.config.js
const StyleDictionary = require('style-dictionary');

module.exports = {
  transform: {
    "size/rem": Object.assign({}, StyleDictionary.transform[`size/rem`], {
      transitive: true,
    }),
   /* rest of the config */
  },
}
```

The "size/rem" transform would then be correctly applied to the tokens in `tokens/size/scale.json`, but not to tokens in `tokens/base/base.json`.

**Comment by bytelabsco** [comment]
The solution by @martikaljuve to override the `size/rem` definition and add transitive worked for me.  Thanks.
