### ISSUE TITLE
Unable to transform the value of color

### ISSUE THREAD

**Issue by WangJiaoJo** [amzn/style-dictionary#738]
Hi, 

I have configured the color variable with value like this,
```
{
    "color": {
        "background": {
            "primary": { "value": "var(--color-background-primary)" }
        }
    }
}
```
and I use the 'registerTransform' to transform the value like this,
```
StyleDictionary.registerTransform({
    name: 'time/seconds',
    type: 'value',
    matcher: function(token) {
      return token.attributes.category === "color";
    },
    transformer: function(token) {
      return token.original.value'; // which is 'var(--color-background-primary)'
    }
});
```
But I am not able the get value of 'var(--color-background-primary)' and I got 
`$color-background-primary: #000000;`.

So is there a way to transform the color value with a string but not the '`#000000`' by default?
I am looking forward to your reply. Thanks.

**Comment by dbanksdesign** [comment]
Can you also post the rest of your configuration? I am guessing another color transform is being applied, and when a color transform sees a string it does not understand it defaults to '#000000' by default.

**Comment by WangJiaoJo** [comment]
@dbanksdesign Sorry just saw your reply and really thanks.

Here is the whole configuration.
`
[`tokens`].forEach((themeType) => {
  StyleDictionary.extend({ 
    source: [`src/assets/design-tokens/${themeType}/*.json`, "src/assets/design-tokens/themes/*.json"],
    platforms: {
      scss: {
        transformGroup: "scss",
        buildPath: "src/assets/scss/",
        files: [{
            destination: `${themeType === 'tokens' ? '_variables' : '_themes'}.scss`,
            format: "scss/variables",
            filter: (token) => {
              
              if (themeType === 'tokens') {
                // if (token.attributes.category === "color") {
                //   console.log(token);
                // }
                return token.original.group ===  "color" || token.original.group === "token";
              }
              return true;
            },
            options: {
              showFileHeader: false,
              outputReferences: true
            }
        }]
      }
    }
  }).registerTransform({
    name: 'time/seconds',
    type: 'value',
    matcher: function(token) {
      return token.attributes.category === "color";
    },
    transformer: function(token) {
      return token.original.value; // which is 'var(--color-background-primary)'
    }
  }).buildAllPlatforms();
});
`
And the token json looks like this,
`
{
    "color": {
        "background": {
              "primary": { "value": "var(--color-background-primary)", "group": "color", "description": "Default color for primary interactive elements…" }
        }
    }
}
`
But I got the `$color-background-primary: #000000;` in the SCSS file it created while the value should be `var(--color-background-primary)`. 
So does style dictionary support to use the CSS variable string for colors?
Thank you!

**Comment by cbou** [comment]
I have almost the same problem with this code:

```
const StyleDictionary = require("./index").registerTransform({
  type: 'value',
  transitive: true,
  name: 'figma/web/flatten-properties',
  matcher: ({ type }) => {
    return ['typography', 'composition'].includes(type);
  },
  transformer: ({ value, name, type }) => {
    if (!value) return;

    const entries = Object.entries(value);

    const flattendedValue = entries.reduce(
      (acc, [key, v], index) =>
        `${acc ? `${acc}\n  ` : ''}--${name}-${StyleDictionary.transform['name/cti/kebab'].transformer(
          { path: [key] },
          { prefix: '' },
        )}: ${v}${index + 1 === entries.length ? '' : ';'}`,
      `${name.includes(type) ? '' : `${type}-`}${name}-group;`,
    );

    return flattendedValue;
  },
}).extend({
  source: [`${__dirname}/tokens.json`],
  platforms: {
    scss: {
      transformGroup: "scss",
      buildPath: "",
      files: [
        {
          destination: "variables.scss",
          format: "scss/variables",
        },
      ],
    },
  },
});

StyleDictionary.buildAllPlatforms();

```

**Comment by cbou** [comment]
I ended adding `StyleDictionary.transformGroup.scss.push('figma/web/flatten-properties');` and it worked.

**Comment by jorenbroekema** [comment]
Closing question issue, considered as answered. although I should note that v4 has some breaking changes that change the answers given slightly, see migration guidelines https://styledictionary.com/version-4/migration/
