### ISSUE TITLE
Missing transform "color/rgba"

### ISSUE THREAD

**Issue by silversonicaxel** [amzn/style-dictionary#744]
Currently Style Dictionary supports _color/rgb_ as transform but it doesn't support _color/rgba_.

It would be a nice feature.

**Comment by dbanksdesign** [comment]
The `color/rgb` transform should handle both colors with an alpha channel and ones without. Take a look at this example: https://stackblitz.com/edit/style-dictionary-example-l7ksfy?file=config.js

**Comment by silversonicaxel** [comment]
I was thinking more of something always creating `rgba` as output, but maybe yeah it is overwhelming and not so necessary
