### ISSUE TITLE
Output formatted string instead of writing the file?

### ISSUE THREAD

**Issue by bdrtsky** [amzn/style-dictionary#751]
Hello. I can't find anywhere in documentation how can I output formatted tokens (let's say CSS variables) into a string for programmatic usage? They only thing I found is writing into a file, and every function I tried from API (like, exportPlatform) is returning raw tokens object, not actual generated output.

**Comment by dbanksdesign** [comment]
I don't believe there is a way to do that right now, at least not directly. Although formatters are functions that return strings, so you could call them yourself, with some help from some internal Style Dictionary methods. I made a quick example:

https://stackblitz.com/edit/style-dictionary-example-mcpo9x?file=build.js

**Comment by dbanksdesign** [comment]
@bdrtsky checking in, was the example I provided what you are looking for?

**Comment by bdrtsky** [comment]
@dbanksdesign yes it was! Thanks a lot for this helpful example
