### ISSUE TITLE
Is there a way to overwrite some data from the extended json config file?

### ISSUE THREAD

**Issue by silversonicaxel** [amzn/style-dictionary#754]
Question is simple:

I've a javascript file
```
const StyleDictionary = require('style-dictionary').extend('color-config.json');
```

and a json config file
```
{
  "source": ["tokens/color.json"],
  "platforms": {
    "css": {
      "transforms": ["color/css"],

```

Since I'm using a particular architecture, I need to prefix the source of all token config jsons with a pre path, so currently the situation is the following in my build process the _source_ `tokens/color.json` is not working, instead I need to use for instance something like this `/extra/architecture/private/tokens/color.json`. 
But I would like not to append this pre path in the json directly, I would like to be able to add it maybe via javascript through one single config parameter.

At the moment I couldn't find a good way to do it, only good approach is to edit directly the config json file. 

Any better ideas?

**Comment by dbanksdesign** [comment]
I made a quick example for ya: https://stackblitz.com/edit/style-dictionary-example-v2nu9z?file=build.js

The short answer is: yes. You can `extend` multiple times and pass new configuration and you also have access to the options passed to Style Dictionary in the `options` object.

**Comment by silversonicaxel** [comment]
Hello @dbanksdesign , it seems the solution... but unluckily it is not working in my codebase 

```
  initExtensions(configurator: string[]): void {
    configurator.forEach(item =>
      this.#configurators.push(
        this.#handler.extend(`${this.#configsFolder}${item}.json`)
      )
    )

    this.#configurators.map(designTokensConfigurator => {
      designTokensConfigurator.extend({
        source: designTokensConfigurator?.options?.source
          ? designTokensConfigurator.options.source.map(
              source => `/extra/architecture/private/${source}`
            )
          : [],
        platforms: designTokensConfigurator.options.platforms
      })
    })
  }
```

where `this.#handler` is

```
  constructor() {
    this.#handler = require('style-dictionary')
  }
```

the value of `source` is still the initial one, `/extra/architecture/private/` is not added.

the only difference I see from your example is the need of adding also platform since it is mandatory in type `Config`.

I am trying to check if my code is wrong, but, it is quite simple. any more ideas? thanks

**Comment by silversonicaxel** [comment]
another hint is:


```
const StyleDictionary = require('style-dictionary').extend('./config.json');

StyleDictionary.extend({
  source: StyleDictionary.options.source.map((path) => {
    return `extra/architecture/private/${path}`;
  }),
  platforms: StyleDictionary.options.platforms,
});

StyleDictionary.buildAllPlatforms();
```

this doesn't work either.

reason is `extend` function returns the new updated object. Solved.
