### ISSUE TITLE
Update dependencies and clean up package/yarn files

### ISSUE THREAD

**Issue by dbanksdesign** [amzn/style-dictionary#77]
* Update dependencies if necessary
* Make sure package-lock.json, yarn.lock, and package.json files are in sync so that fresh installs are deterministic and don't change those files
* Update contribution docs to reflect the proper way to checkout the repo and install dependencies

**Comment by chazzmoney** [comment]
package and package.lock are synched and yarn.lock has been removed

Just need to update the documentation.
