### ISSUE TITLE
Adding husky to test in git commit

### ISSUE THREAD

**Issue by davixyz** [amzn/style-dictionary#81]
While adding some more testing I noticed that we don't run the tests on commit. It would good to add a pre-commit hook to run the tests so engineers don't have to rely on the CI to catch any integration issues. This also goes well with the 3rd point in the contribution guidelines
https://github.com/amzn/style-dictionary/blob/master/CONTRIBUTING.md#code-rules

I can quickly add this on a PR:
https://github.com/typicode/husky

**Comment by dbanksdesign** [comment]
Love it!

**Comment by dbanksdesign** [comment]
Code merged, closing issue
