### ISSUE TITLE
prefix removing addition `-` 

### ISSUE THREAD

**Issue by sturobson** [amzn/style-dictionary#815]
I'm trying to get the compiled design tokens as Sass variables to be something like –

`$token--this-is-a-token`

But adding `prefix: "token--"` or `prefix: "token-"` or `prefix: "tokens`&hyphen;`" and many other permutations give me this result:

`$token-this-is-a-token`.

Is there any way to get the double dash?

**Comment by dbanksdesign** [comment]
Off the top of my head, not using the built-in transforms. I haven't tested this, but I'm fairly certain this would work:

```js
StyleDictionary.registerTransform({
  name: 'name/cti/kebab',
  type: 'name',
  transformer: function(token, options) {
    return `${options.prefix}--${_.kebabCase(token.path.join(' '))}`;
  }
});
```

**Comment by sturobson** [comment]
Thanks @dbanksdesign! <3 

This breaks because it doesn't know that `_` is looking for `lib/utils/es6_`.

Adding `const _ = require('../../node_modules/style-dictionary/lib/utils/es6_');` to the top of my config `.js` file fixed this -- worked as needed. 

Thanks for taking a look and providing the answer. I'll close this <3
