### ISSUE TITLE
How can I test my custom formatters?

### ISSUE THREAD

**Issue by Vanals** [amzn/style-dictionary#817]
Hi,

I am looking for suggestions and/or example for how to test my JS application, using Style Dictionary, that is working as expected.
I am creating and using a custom format
`StyleDictionary.registerFormat({ ...`

How would you suggest testing it out? and which packages for doing so?
I 've done a quick search on the issues but haven't found anything.

I guess, I want to have a test that allows me to run Style Dictionary, and check what's the output of it.. which files(and their content) would is being created.

Thank you.

**Comment by dbanksdesign** [comment]
Hi @Vanals! 

You can take a look at the '__tests__/formats/' directory in our codebase, that is were we test the output of the built-in formats. What I would do is have the custom formatter functions in their own files or exported separately so that you can import them in a test as a standalone function. Then in your tests you can pass different dictionary objects and validate the output using snapshot testing. You can take a look at this file https://github.com/amzn/style-dictionary/blob/main/__tests__/formats/all.test.js for how we create the arguments to pass to the formatter function. 

Hope this helps!

**Comment by Vanals** [comment]
Thank you @dbanksdesign ! We will try out!

**Comment by Vanals** [comment]
> Hi @Vanals!
> 
> You can take a look at the '**tests**/formats/' directory in our codebase, that is were we test the output of the built-in formats. What I would do is have the custom formatter functions in their own files or exported separately so that you can import them in a test as a standalone function. Then in your tests you can pass different dictionary objects and validate the output using snapshot testing. You can take a look at this file https://github.com/amzn/style-dictionary/blob/main/__tests__/formats/all.test.js for how we create the arguments to pass to the formatter function.
> 
> Hope this helps!

Hi @dbanksdesign ! I am on this ticket right now. I was wondering, what is the different between the test you have in `all.test.js` and the specific format tests? such as `javascriptModule.test.js`

all.tests tests all the formats in one go? if yes why you need the specific ones as well?

Thank you

**Comment by Vanals** [comment]
Implementing the custom functions in our repo for testing custom formats feels a bit overwhelming, I think we should not have to implement those in our own repo repo, what you think? Is there a better way?

At the moment I have been adding createFormatArgs, isPlainObject, deepExtend, and now I see createDictionary is needed as well and brings more function with them. Feels a bit too much for just testing custom formats. Ideally I would like be able to import what is needed from style-dictionary or a package ad hoc anyway, for testing. @dbanksdesign

**Comment by Vanals** [comment]
Sorry for the spam @dbanksdesign , I have progresses and with them a different question.

I managed to create the tests, but kind of differently than how you do. So I am not using all your internal functions but I call directly `buildAllPlatform`


```
import StyleDictionary, {Config} from 'style-dictionary';
import {nkThemeFormatter} from '../nk-theme-formatter';
import {clearOutput} from './helpers/helpers';

describe('nk-theme-formatter', () => {
  afterEach(() => {
    clearOutput();
  });

  it('should create a Newskit theme format object', () => {
    StyleDictionary.registerFormat({
      name: 'nk-theme',
      formatter: nkThemeFormatter,
    });

    const styleDictionaryConfig: Config = {
      source: [
        './src/style-dictionary/formatters/__tests__/nk-tokens-mock.json',
      ],
      platforms: {
        'nk-doc-theme': {
          transformGroup: 'js',
          buildPath: 'src/style-dictionary/formatters/__output__/',
          files: [
            {
              destination: 'nk-doc-themes.json',
              format: 'nk-theme',
            },
          ],
        },
      },
    };

    StyleDictionary.extend(styleDictionaryConfig).buildAllPlatforms();

    const nkThemeObject = require('../__output__/nk-doc-themes.json');
    expect(nkThemeObject).toMatchSnapshot();
  });
});

```

I am then requiring the file and matching the snapshot! What you think about it :)?
Also, could you give me some insight on why you have a `test for all` then test for specific formatters?

Thank you!
