### ISSUE TITLE
CSS/SCSS Variables Format Doesn't Wrap Math Values in Calc()

### ISSUE THREAD

**Issue by yuschick** [amzn/style-dictionary#820]
## The Problem

Whenever I have a token which contains a math expression as its value, the value is not wrapped in a `calc()` function when formatting as `css/variables`.

## Example
I have this spacing token, which multiples the base space value by 0.5, coming from Figma Tokens.

```json
"base-half": {
  "value": "{space.base} * 0.5",
  "type": "spacing"
},
````

When this is transformed, the reference is retained, but the expression isn't wrapped inside of a `calc()` function,

```css
--px-space-base-half: var(--px-space-base) * 0.5;
````

Without the `calc()` function, this value is invalid CSS.

## Expected Result

I would expect, when having a token with a math expression as its value, that the value would be wrapped in a `calc()` function per CSS and SCSS syntax.

```css
--px-space-base-half: calc(var(--px-space-base) * 0.5);
````

Is this a bug with the format? Or is it expected that I would write a custom transform to support this functionality?

**Comment by dbanksdesign** [comment]
This isn't a bug, but more of a limitation. Right now style dictionary does not handle any sort of math in values like `"{space.base} * 0.5"`. Style dictionary is a bit more low-level, we can't assume a value with "*" means to multiplication, someone could be storing UI strings in values like `"* required fields"`.  A custom transform would be needed to handle this scenario. This could be something we add as a built-in transform or release as a plugin or something.

**Comment by mthines** [comment]
@yuschick 
That transformer could look something like this 

```js
StyleDictionary.registerTransform({
  type: `value`,
  transitive: true,
  name: `figma/calc`,
  matcher: ({ value }) => typeof value === 'string' && value?.includes('*'),
  transformer: ({ value }) => `calc(${value})`,
});
```
