### ISSUE TITLE
json from Figma Tokens is transformed to [object Object]

### ISSUE THREAD

**Issue by marcello-palmitessa** [amzn/style-dictionary#826]
Using the Figma plugin "Figma Tokens" I'm getting a json file like this:

```json
{
 "global": {
     "Card Title": {
      "value": {
        "fontFamily": "$fontFamilies.philosopher",
        "fontWeight": "$fontWeights.philosopher-0",
        "lineHeight": "$lineHeights.0",
        "fontSize": "$fontSize.1",
        "letterSpacing": "$letterSpacing.0",
        "paragraphSpacing": "$paragraphSpacing.0",
        "textCase": "$textCase.none",
        "textDecoration": "$textDecoration.none"
      },
      "type": "typography"
    }
 }
}
```

The issue I have is that the token "Card Title" is transformed (with format css/variable) to:
```css
:root {
   --global-card-title: [object Object];
}
```

My config.json is this one:
`{
  "source": [
    "./design-tokens/data/**/*.json"
  ],
  "platforms": {
    "css": {
      "transforms": [
        "name/cti/kebab"
      ],
      "transformGroup": "custom/css",
      "buildPath": "./src/styles/",
      "files": [
        {
          "destination": "_tokens.css",
          "format": "css/variables",
          "options": {
            "showFileHeader": false,
            "outputReferences": true
          }
        }
      ]
    }
  }
}
`

Someone can help me please, I'm very desperate to get this working...

**Comment by ACNdgproductions** [comment]
Facing exactly the same... I see that only happens using figma tokens.... 
I know this plugins works really great with tons of features but... If you use 'design tokens'... for me most of the properties that wasn't working fine.... appears divided and worked fine.
![image](https://user-images.githubusercontent.com/79651668/170356987-73a86c22-7f0e-469b-b69f-3c9c5b632e3d.png)
With that said.... help us community!!! 
Is there any transformGroup / transform allow us to convert these props into several tokens like...

Before
```
:root {
   --global-card-title: [object Object];
}

```
Desired
```
:root {
   --global-card-title-font-family: "fontFamilies.philosopher";
   --global-card-title-font-weight: "$fontWeights.philosopher-0"
....
}

```

Thanks in advance!

**Comment by marcello-palmitessa** [comment]
@jam-awake thank you very much! now it works!!!!

**Comment by marcobertonati** [comment]
> Using the Figma plugin "Figma Tokens" I'm getting a json file like this:
> 
> ```json
> {
>  "global": {
>      "Card Title": {
>       "value": {
>         "fontFamily": "$fontFamilies.philosopher",
>         "fontWeight": "$fontWeights.philosopher-0",
>         "lineHeight": "$lineHeights.0",
>         "fontSize": "$fontSize.1",
>         "letterSpacing": "$letterSpacing.0",
>         "paragraphSpacing": "$paragraphSpacing.0",
>         "textCase": "$textCase.none",
>         "textDecoration": "$textDecoration.none"
>       },
>       "type": "typography"
>     }
>  }
> }
> ```
> 
> The issue I have is that the token "Card Title" is transformed (with format css/variable) to:
> 
> ```css
> :root {
>    --global-card-title: [object Object];
> }
> ```
> 
> My config.json is this one: `{ "source": [ "./design-tokens/data/**/*.json" ], "platforms": { "css": { "transforms": [ "name/cti/kebab" ], "transformGroup": "custom/css", "buildPath": "./src/styles/", "files": [ { "destination": "_tokens.css", "format": "css/variables", "options": { "showFileHeader": false, "outputReferences": true } } ] } } } `
> 
> Someone can help me please, I'm very desperate to get this working...

Could you find a solution with Figma Tokens?

**Comment by Parvin-Gasimli** [comment]
"scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "transformer": "token-transformer demo test/output.json  --expandTypography=true expandShadow=true",
    "dictionary": "style-dictionary build --config config.json"
  },   // clone the package.json file into

**Comment by beihai-shinan** [comment]
> @jam-awake thank you very much! now it works!!!!
https://docs.google.com/document/d/1VsO0dReQ70cxttT7CfzBDZmN9qucvEaPEbev4a8Oi3I/edit#

**Comment by harshmer** [comment]
if anyone could please help with a custom transformer for the problem @marcobertonati posted above? I'm in the same boat and can't figure out. Token-transformer expands the typography but the type is messed up once it expands. Type shows as type: type. which is wrong and it should be type: typography. 

Any help would be greatly appreciated. Thanks a million.

**Comment by jorenbroekema** [comment]
We've deprecated token-transformer in favor of using style-dictionary with this package: https://github.com/tokens-studio/sd-transforms
