### ISSUE TITLE
Incorrect type definition in Config.d.ts

### ISSUE THREAD

**Issue by yunhao** [amzn/style-dictionary#832]
## What happened

When using the NPM Module and Typescript to write a build script, the following code compiles successfully. It passes TypeScript's type system.

```typescript
StyleDictionary.extend({
  transformGroup: {
    "custom/ios-swift": {
      transforms: [
        "category/normalize",
        'attribute/cti',
        // ...
      ]
    }
  },
  platforms: {
    // ...
  }
})
```

However, when you run the code, you will see an error:
```bash
to_ret.transforms = transforms.map(function(name) {
                                 ^

TypeError: transforms.map is not a function
```

## Expect

After looking at the source code, I found that the correct code should be:

```typescript
StyleDictionary.extend({
  transformGroup: {
    "custom/ios-swift": [
      "category/normalize",
      'attribute/cti',
      // ...
    ]
  },
  platforms: {
    // ...
  }
})
```

Unfortunately, the code will not compile because of type mismatches. However, if you make some changes to make the code compilable (e.g. using `any` type) and then run it, it will work fine.

## How to fix it

https://github.com/amzn/style-dictionary/blob/3b520d226b15775b109179a11cb8fbb9fde23a36/types/Config.d.ts#L27

I think we should change this line of code to:

```typescript
transformGroup?: Record<string, TransformGroup['transform']>;
```

**Comment by jorenbroekema** [comment]
Fixed in v4
