### ISSUE TITLE
Required global npm install?

### ISSUE THREAD

**Issue by Wrecklaimer** [amzn/style-dictionary#840]
According to the Quick Start, we should be able to install style-dictionary as a dev dependency with `npm install -D style-dictionary`.

Which adds the following to `package.json`:
```
"devDependencies": {
    "style-dictionary": "^3.7.1"
}
```

However, running any `style-dictionary` command results in the error:
```
style-dictionary : The term 'style-dictionary' is not recognized as the name of a cmdlet, function, script file, or operable program. 
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

The only way to get the command `style-dictionary` to be recognized is to install the package globally with `npm install -g style-dictionary`.

This is a problem if style-dictionary needs to run as part of a build pipeline on a server.

Is global installation required, or am I missing something?

**Comment by dbanksdesign** [comment]
Global install is not required. However, you will need to call the `style-dictionary` command within an npm script. This is a feature of the npm CLI, and not necessarily a limitation of the style dictionary package. This is the same for any npm package that has a CLI (rollup, eslint, vite, etc.). After you add style dictionary to your devDependencies, you can call it in an npm script like this: https://stackblitz.com/edit/style-dictionary-example-vchubn?file=config.json%3AL13,package.json%3AL9

Does that answer your question?

**Comment by Wrecklaimer** [comment]
@dbanksdesign Yes, thanks.
