### ISSUE TITLE
Will it be possible to add another option for the `css/variables` format to allow :root, ::after, ::before ?

### ISSUE THREAD

**Issue by silversonicaxel** [amzn/style-dictionary#844]
At the moment the [css/variables](https://amzn.github.io/style-dictionary/#/formats?id=cssvariables) format is creating an output like the following 

```
:root {
  ...
}
```

Would be possible to have an option that is set to root as default, but that can also provide as output something like this

```
:root,
::after,
::before {
  ...
}
```

An example for the configuration could be something like this, in the field for instance called `targets`

```
"platforms": {
    "css": {
      "transforms": ["spacing/ratio/web", "size/px"],
      "buildPath": "dist/css/",
      "files": [
        {
          "destination": "spacing.css",
          "format": "css/variables",
          "options": {
            "targets": ["root"]
          }
        }
      ]
    },
```
or
```
"platforms": {
    "css": {
      "transforms": ["spacing/ratio/web", "size/px"],
      "buildPath": "dist/css/",
      "files": [
        {
          "destination": "spacing.css",
          "format": "css/variables",
          "options": {
            "targets": ["root", "after", "before"]
          }
        }
      ]
    },
```

So `targets` could support a limited amount of keywords, like `root`, `after`, `before`, `backdrop` ...

What do you think? Thanks

**Comment by dbanksdesign** [comment]
The `css/variables` format does have that option already, it is called `selector`: https://amzn.github.io/style-dictionary/#/formats?id=cssvariables

Here is an example: https://stackblitz.com/edit/style-dictionary-example-vchubn?file=config.json%3AL13,build%2F_variables.css 

Does that work for your use-case?

**Comment by silversonicaxel** [comment]
It was exactly this, I didn't notice the parameter. Thanks!
