### ISSUE TITLE
Question: How are `formattedVariables` and `createPropertyFormatter` related / different?

### ISSUE THREAD

**Issue by chris-dura** [amzn/style-dictionary#851]
I need to create a custom Swift format for one of our internal iOS SDKs. For the most part, I'm using the various transforms that already are provided, but I'll pretty much need to create a highly custom format using a highly customized `template` as well. I think the docs for SD around custom formats and format helpers give me the info I need, in particular around using output references etc.

However, I have some naive questions around `formattedVariables` and `createPropertyFormatter`...

1. It's not quite clear from the docs what the difference between those two helpers are exactly? And, what scenarios you would use one instead of the other?
2. AFAICT, the `createPropertyFormatter` ultimately generates a literal `${indentation}${prefix}${prop.name}${separator} ${prop.value}${suffix}`... this doesn't really work for what I need for my custom format, so I'm assuming that `createPropertyFormatter` wouldn't really help me? And, I'd probably just have to write my own function that replicates the logic if I need to?

**Comment by Charlene-Bx** [comment]
Have similare question after noticied that `formattedVariables({...})` DON'T reflect transformed value applied to the dictionary. Wondering if using `createPropertyFormatter` will fix my issue or not. Can someone can shed some light on that please?

**Comment by chris-dura** [comment]
@Charlene-Bx -- I'm still somewhat interested in a detailed answer to better understand how SD works. But, I asked this question quite awhile ago (pre-v4).

I've ended up writing a lot of custom formats since then, and fwiw, I basically resorted to copy+pasta'ing the logic I wanted from the core functions into my own formats. Here's a snippet of a code comment I left for myself in one of those custom formats a long time ago...

```javascript
	// The `createFormatProperty` helper returns a function that ultimately
	// returns a `${indentation}${prefix}${token.name}${separator} ${token.$value}${suffix}` line.
	// That won't work for every token, and we need to do some custom logic to get
	// the proper syntax, like adding `token.$type` to the line, or,
	// systemize the intent colors for dark mode.
	// So, instead of using the `createPropertyFormatter` helper, we lift the useful logic
	// @see https://v4.styledictionary.com/reference/utils/format-helpers/#createpropertyformatter
	// @see https://github.com/amzn/style-dictionary/blob/main/lib/common/formatHelpers/createPropertyFormatter.js#L26
```

**Comment by jorenbroekema** [comment]
The `formattedVariables` helper is a wrapper around `createPropertyFormatter`.

So basically: `css/variables` format -> uses `formattedVariables` -> uses `createPropertyFormatter`

Depending on how granular you want to go, you could use the built-in format directly, use the helper to get a but more custom, use the other helper to get even more custom, or register a custom format without using either of those helpers to get the full control over how you want to format your design tokens in the output

**Comment by jorenbroekema** [comment]
Closing question issue, considered as answered.
