### ISSUE TITLE
[FEATURE REQUEST] outputReferences with fallbacks?

### ISSUE THREAD

**Issue by fredboyle** [amzn/style-dictionary#856]
Would it be possible to add functionality to the `outputReferences` option to force a fallback scenario per token?

This would allow the generation of valid references in formatters such as CSS and Sass/SCSS when the reference may have been filtered out but the reference is still desired to create an API surface.

For our context it is particularly handy when creating separate additive "themes" that are generated as separate files, base/foundation and overrides/enhancements that might be created by us internally or customers externally.

JSON source
```json
{
    "typography": {
        "font": {
            "headings": { "value": 'Helvetica Neue,Helvetica,Arial,sans-serif' }
        }
}

{
    "marketing": {
        "headings": {
            "value": "{typography.font.headings.value}",
            "outputReferencesFallback": true
        }
}
```

CSS output
```css
--scope-marketing-headings: var(--scope-typography-font-headings, 'Helvetica Neue,Helvetica,Arial,sans-serif');
```

The above would generate the output without doing a reference validation lookup. So the first value in the reference would be the literal reference, and the second value is the literal fallback value found by the standard reference lookup as if the `outputReferences` option wasn't used.

Hopefully this makes sense.

**Comment by jorenbroekema** [comment]
This was added a while ago, so closing this now
