### ISSUE TITLE
outputReference does not handle multiple references properly

### ISSUE THREAD

**Issue by Javernus** [amzn/style-dictionary#886]
I came across a weird behaviour when working with `outputReference`. The output seems to be bugged. Here is a config to recreate the issue:

```
{
    "colour": {
      "10": {
        "value": "#000000"
      }
    },
    "opacity": {
      "0": {
        "value": "0"
      }
    },
    "test": {
      "value": "{colour.10.value}, {opacity.0.value}"
    }
}
```

Here is the output token `test` for this code for both css and scss exports:

```
$test: $colour-1$opacity-0, 0;
--test: var(--colour-1var(--opacity-0)), 0;
```

As is clear, this is incorrect. I would expect this:

```
$test: $colour-10, $opacity-0;
--test: var(--colour-10), var(--opacity-0);
```

I tested this on version 3.7.1.

**Comment by Javernus** [comment]
Could someone actually look at this issue?

**Comment by Javernus** [comment]
Has there been any focus on this issue?

**Comment by ohearonkg** [comment]
I recently encountered a similar issue. As mentioned in the other referenced issue, I believe the problem area is related to https://github.com/amzn/style-dictionary/blob/main/lib/common/formatHelpers/createPropertyFormatter.js#L115

Specifically, when resolving references and updating the content of the `value` property.

In your example the string would start out as:

`#000000 0` 

My understanding is that Style Dictionary works backwards and resolved each value to it's top level reference. So on the first pass the string would be updated to:

`var(--color-10), 0` 

Then it attempts to call JavaScript's `string.replace` function on this string, attempting to replace the value `0` with the referenced token `opacity-0`.  This results in the unexpected out:

`var(--color-1var(--opacity-0), 0`

Where the first instance of the string `0` has been replaced with what Style Dictionary believes is its referenced token name.

**Comment by ohearonkg** [comment]
@Javernus - For what it's worth, if you're willing to (hopefully temporarily patch the package) it seems that updating the code within the `createPropertyFormatter.js` file as done within [this](https://github.com/amzn/style-dictionary/pull/1002/files#diff-7d3da3814c15150a5b46668d647b2addabf5a15e86980bd4809137cb4826e0e5) PR fixed the issue for me :)

**Comment by jorenbroekema** [comment]
Fixed, not sure when but the use case described in this issue works: [reproduction](https://configurator.tokens.studio/#project=lVPBjtsgEP0VxGVbyYmlVU/ppYdVe62aY1lVGHBC1wbEDFFSy/9eDLZju92qe7HhzcybN8NMRwGD1Hb/E6yhB9oxQwijUrfKgLaG0QNJ2ICC4I1aIAN24U1IGKOPjBZ3A97ciIP+pc2J0Wzri4nuCq9zfXDXN7JB+zpbN9ezv0JfkMU91dT/X67hFz89LahXJw2o/PHpczACIxPEFsYG6tZZj+SIt0Y96WTh/kZqb1vyAAO6kzP88JGZMaAjEyXpR+9PaF+iyl1+oRLkDj03UFvfwhDJTFmSFVqQRyOJ4563amCKILEuqSOCG1IpwqVUMkUelSLSCjiQM6KDQ1meNJ5DtRe2Lf+RmplJ6btNle+jqNgbYU2tT5uJAhu8SG39Pr/YffJyi5+L7NvY02ruLspXFjTe8qtIVfPQYI7pxxjnlfNWKADrYZVmVco6kWs45pqW6QRsB3Mu/ou3wWUVG9riL95LHdlk4sOUL6ri1TRUk5hsr4Ju5FeO55wjXcuop1wlqHWjttzd/ZgWWAFqw3FcYUZ/XLjXvIqB+1RfsfYf5HLMrkO+2fsPz3GeVh2abQFdwG+qVl4ZkTWij1u48Ovvl/n4vF2w/jc=)
