### ISSUE TITLE
Support for nested transformGroups

### ISSUE THREAD

**Issue by jreichenberg** [amzn/style-dictionary#90]
Would help with extensibility to allow transformGroups to declare other transformGroups. For example:
```
StyleDictionary.registerTransformGroup({
  name: 'my-group',
  transforms: [
    'custom/transform',
    'scss'
  ]
});
```

That way, custom transforms don't need to redeclare the contents of an existing transform group when adding net-new transforms.

**Comment by jreichenberg** [comment]
...or...make transformGroup optionally take an array, which would then allow the contents of multiple groups to be concated and allow platform generic transformGroups to be registered once and reused. Dunno...

**Comment by dbanksdesign** [comment]
You could do it pure JS with Array.concat or push, etc. There are also times when you might want new transforms to come before, or after, or in the middle of the transformGroup. It might get messy. 

One thing I've come across as well is people trying to extend the built-in transformGroups by adding more transforms. This is possible now, but not super pretty.

```js
//...
const transformGroups = require('style-dictionary/lib/common/transformGroups');
StyleDictionary.registerTransformGroup({
  name: 'my-group',
  transforms: transformGroups.scss.concat([
    'custom/transform'
  ])
});
```

**Comment by jreichenberg** [comment]
That works!  Thanks.  I'll close this.
