### ISSUE TITLE
How to create extend as ES6 module

### ISSUE THREAD

**Issue by Rajdeepc** [amzn/style-dictionary#902]
How to write the below line in ES6 Module

CommonJS:
const StyleDictionary = require('style-dictionary').extend('config.json');

ES6??

**Comment by Rajdeepc** [comment]
Ok I figured out that it can be written  as 
```
import StyleDictionary from 'style-dictionary'
const styleDictionary = StyleDictionary.extend( 'config.js' );
```

But I have written this line in build-css.js and this is my file structure
build-css.js
config.js

But I am getting this error
Error: Cannot find module '/Users/rajdeepc/Documents/Projects/project/config.js'

**Comment by jorenbroekema** [comment]
v4 has first-class ESM support, see https://github.com/amzn/style-dictionary/blob/v4/CHANGELOG.md
