### ISSUE TITLE
How would you output certain tokens but not others?

### ISSUE THREAD

**Issue by informa** [amzn/style-dictionary#93]
How would you output certain tokens but not others?

Say I setup my colors in a color.json
```
{
  "color": {
    "brand": {
        "grey": {
      	 "lighter" : { "value": "#F3F4F5" },
         "light"   : { "value": "#E8EAEC" },
         "medium"  : { "value": "#DCDFE1" },
         "dark"    : { "value": "#687480" },
         "darker"  : { "value": "#2E3E4F" }
      },
   },
}
```
and I wanted to use this color in other files like fonts.json
```
{
  "fonts": {
    "color": {
      "base": {color.brand.grey.darker}
    }
  }
}
```
In SCSS I want only to output `$fonts-color-base: #2E3E4F;`  But I don't want to output `$color-brand-grey-darker:  #2E3E4F` etc.

**Comment by informa** [comment]
Maybe one way would be to add an action
```
StyleDictionary.registerAction({
  name: 'filterOutput',
  do: function(dictionary, config) {
    fs.readFile('./build/scss/_variables.scss', 'utf-8', function(err, data){
      if (err) throw err;

      const filteredData = 
        data
          .split('\n')
          .filter(item => !item.includes('$color-'))
          .slice(1)
          .join('\n');
      
      fs.writeFile('./build/scss/_variables.scss', filteredData, 'utf-8', function (err) {
        if (err) throw err;
      });
    });
  }
});
```
This might suit a specific output like `scss` but maybe not suited others like `html`?

**Comment by informa** [comment]
actually I can do for HTML

```
<% 
      var props = _.filter(allProperties, function(property) {
        return property.attributes.category !== 'color'
      }); 
    %>
    <% _.each(props, function(property) { %>
```
Nice

**Comment by informa** [comment]
Actually I can add custom requirement `filter` to a `registerFormat` rather than adding a `action` after build.

**Comment by dbanksdesign** [comment]
Apologies, I was on vacation over the weekend. You are on the right track, you can filter the properties in a format or template. Unfortunately not all built-in formats/templates have a standard filtering, which is what this ticket is referring to: https://github.com/amzn/style-dictionary/issues/86. But if you write your own format/template, you can either filter in it with whatever you need to filter by, or you can create a generic one that takes a filter object like here:
https://github.com/amzn/style-dictionary/blob/master/lib/common/templates/ios/static.m.template#L23

In templates, `this` is bound to the file object in your config.json. 
```json
{
  "source": ["test/properties/**/*.json"],
  "platforms": {
    "web": {
      "transformGroup": "web",
      "buildPath": "build/web/",
      "files": [
        {
          "destination": "_icons.css",
          "template": "custom-template",
          "filter": {
            "attributes": {
              "category": "color"
            }
        },{
```

`this.filter` would return `{attributes: {category: 'color'}}`. You can do the same in filters as well:
https://github.com/amzn/style-dictionary/blob/master/lib/common/formats.js#L265

**Comment by informa** [comment]
Thanks @dbanksdesign, was just getting my head around the right tokens to serve up.
Great to have good feedback, thanks again.
