### ISSUE TITLE
How to use transforms

### ISSUE THREAD

**Issue by mybigman** [amzn/style-dictionary#94]
Hi Guys,

Just came across this project which seems pretty interesting.

Referring to https://github.com/amzn/style-dictionary/issues/91#issuecomment-390873157

How do you use this? The documentation shows you how to create them but nothing on how to use them :(

How do I utilise this please.

Thanks

**Comment by chazzmoney** [comment]
@mybigman Did this help? I'm working on making the documentation more clear and would love your feedback.

**Comment by samuelg0rd0n** [comment]
I was definitely missing something like this in the docs and would love to see it there 😊
