### ISSUE TITLE
'Size' token dropping rem units and replacing with px

### ISSUE THREAD

**Issue by dgibson666** [amzn/style-dictionary#944]
In Style Dictionary 3.7.2, I'm seeing some weird behavior where my `size` tokens are dropping my specified (rem) units and replacing with px, while doing no conversion or translation to the numeric value itself. I duplicated this token as `space` and no such issue occurred there - only in the size token. Is this a bug or is there some automatic transform being applied (and how can I override it)?

**Comment by Sidnioulz** [comment]
@dgibson666 it would be impossible to help you in this case without you sharing your whole config file. Are you by chance using a transformGroup?

**Comment by dgibson666** [comment]
transformGroup is "web". Sorry, I'm not used to working on public repos - the whole file is here:

https://github.com/US-CBP/design-system/blob/feature/token-css-variables/packages/styles/config.json#L56

If I change that _space.scss to _size.scss, it replaces the rem units with px.

**Comment by dgibson666** [comment]
Thanks, that does clarify it. I figured that some transform was being applied, but I didn't think it would be desired functionality to remove the rem units and replace with px. It would be smarter to only do this for unitless values but the behavior is in line with the documentation.

**Comment by Sidnioulz** [comment]
@dgibson666 glad it helped! Feel free to close the issue (button left of the 'Comment' button) if you think it's resolved, to help maintainers spot unanswered issues ;-)
