### ISSUE TITLE
Missing newline at the end of generated file

### ISSUE THREAD

**Issue by AugustinasVainius** [amzn/style-dictionary#949]
Good day, 
some in-built formats produce output which is missing newline at the end of file. Github doesn't like that 
![image](https://user-images.githubusercontent.com/87965398/225267364-8412c961-6dd2-4574-9208-76b7127b75e6.png) as well as it may cause other [problems](https://stackoverflow.com/a/729795) down the line.

The formats I've encountered this problem with: `scss/variables`, `json/flat`, `javascript/es6`, `typescript/es6-declarations`. More formats might be affected by this.

To replicate, using `style-dicitonary@3.7.2` & `node@16.14.2`, build [basic example](https://github.com/amzn/style-dictionary/tree/main/examples/basic) and see file `examples/basic/build/scss/_variables.scss` - it doesn't have newline on the final line.
![image](https://user-images.githubusercontent.com/87965398/225293327-11e8fd97-514a-498a-861c-40ccaeb0ed1c.png)

Thank you, looking forward to hear your input on this.

**Comment by chazzmoney** [comment]
Thanks for the note @AugustinasVainius. If you want to submit a PR for this, we would be happy to review it and merge it.

**Comment by AugustinasVainius** [comment]
Hi, @chazzmoney, thanks for the response. I have the changes on my local, could you grant me permission to create a PR?

**Comment by dbanksdesign** [comment]
Looks like this was fixed and released! Closing this issue. Please reopen if it is still appearing.
