### ISSUE TITLE
Docs not aligned with latest stable release

### ISSUE THREAD

**Issue by lucoel** [amzn/style-dictionary#959]
It looks like there is a mismatch in the documentation and the latest stable release. 

Took me a while today to figure out why the `compose/object` for doesn't accept the import parameter. Then I saw that this parameter comes with the next version `3.7.3`, although it already appears in the [current build](https://amzn.github.io/style-dictionary/#/formats?id=composeobject) of the docs page for `3.7.2`. 👀 Not sure if there are other sections not aligned at the moment.

It would be great if the documentation only shows features of the current stable version and then maybe have a preview version for upcoming releases at some point. 🔭 

Thanks!

**Comment by chazzmoney** [comment]
Whoops. Thanks for pointing this out. Will release the next version.

**Comment by dbanksdesign** [comment]
This should be fixed now, we released v3.8.0 earlier today which has that change!
