### ISSUE TITLE
The chameleon mascot is cute and deserves a name!

### ISSUE THREAD

**Issue by iglvzx** [amzn/style-dictionary#97]
Hello, I love the chameleon mascot. This one right here:

<img src="https://raw.githubusercontent.com/amzn/style-dictionary/master/docs/assets/logo.png"  width="200" />

Please give the chameleon a name. Thank you.

**Comment by dbanksdesign** [comment]
We have stickers of it, you can get some at our [hackathon](https://github.com/amzn/style-dictionary/wiki/Hackathon:-Friday,-June-29th-at-the-Amazon-office-in-Santa-Cruz,-CA)! 

As for the name... I'm open to suggestions. Cammy? Carmen? [Vitruvius](https://en.wikipedia.org/wiki/Vitruvius)?

**Comment by chazzmoney** [comment]
Would definitely love suggestions!

**Comment by mix3d** [comment]
Casper, Comet, Crayon?

**Comment by bolora** [comment]
Eddie, Pascal, Jason, Gizmo, Prim

**Comment by chazzmoney** [comment]
As a Math and CS geek, I love the idea of Pascal.  It encompasses the idea of structured decendency.

**Comment by chazzmoney** [comment]
So, where do we put the name?  Should I add a "Mascot" section in the documentation?

**Comment by chazzmoney** [comment]
Thanks @iglvzx !

**Comment by StefanEndress** [comment]
hi there … is there a black and white svg version available?
