### ISSUE TITLE
Issue running default "quickstart" template

### ISSUE THREAD

**Issue by mix3d** [amzn/style-dictionary#98]
Windows 10x64, Node v8.11.2, npm v6.1.0, first time install of style-dictionary.

Run `>npm install -g style-dictionary` then `> style-dictionary init basic`
Output:
```
Copying starter files...

Source style dictionary starter files created!

Running `style-dictionary build` for the first time to generate build artifacts.

Reading config file from ./config.json
module.js:549
    throw err;
    ^
Error: Cannot find module '.\properties/color/base.json'
```

Any suggestions on how to resolve this? Is it the windows file path inconsistencies with backwards/forwards slashes? I didn't see a required version of any dependencies.

**Comment by dbanksdesign** [comment]
Darn, that does look like a windows issue with path inconsistencies. Just to confirm, the init script did create these files/folders: https://github.com/amzn/style-dictionary/tree/master/example/basic

**Comment by mix3d** [comment]
Correct; I also ran the initialized program from the Linux Subsystem for Windows thing, and it ran fine. Sounds like a path problem.

**Comment by dbanksdesign** [comment]
We did recently make a change to how the framework loads the style dictionary files [in this PR](https://github.com/amzn/style-dictionary/pull/89), can you try something? Try installing the previous version, `npm i -g style-dictionary@2.1.0` and then see if you get the same problem.

**Comment by mix3d** [comment]
2.1.0 built correctly.

**Comment by dbanksdesign** [comment]
Awesome, that helps a lot. I'll see about getting 2.2 fixed and push out a 2.2.1

**Comment by dbanksdesign** [comment]
@jreichenberg if you have time, could you help debug this issue? It looks like the code for requiring style dictionary files no longer works on Windows.

**Comment by jreichenberg** [comment]
Rats. I’ll take a peek @dbanksdesign

**Comment by dbanksdesign** [comment]
Thanks! Let me know if you need help. I'll see if I can try running node on my windows box at home to help debug the issue.

**Comment by jreichenberg** [comment]
Going to assume this is the bomb: https://github.com/amzn/style-dictionary/blob/master/lib/utils/combineJSON.js#L39 (the `.` prepended to non-absolute paths)

**Comment by dbanksdesign** [comment]
Would that mean it is a bug in resolve-cwd then? Because that is how that module is supposed to work.

**Comment by jreichenberg** [comment]
I may have gotten too fancy using path.sep... will test a fix today if I can get windows running

**Comment by mix3d** [comment]
Glad to help test if need be. I know all the cool kids use Macs or Linux these days :/

**Comment by jreichenberg** [comment]
Based on https://github.com/nodejs/node/issues/6049 and the docs in https://www.npmjs.com/package/resolve-cwd itself, I think I tried to get too smart using path.sep and should have stuck with `/`, which require can handle just fine in windows. My proposed fix in https://github.com/jreichenberg/style-dictionary/tree/issue/98 ( https://github.com/jreichenberg/style-dictionary/commit/b9553f667bf22abc21ecef3d327d742addbfa4d3 ) should work, but I can't really test b/c I can't drum up an open enough windows environment here at work. A little help testing?

**Comment by mix3d** [comment]
LGTM 👍

**Comment by dbanksdesign** [comment]
@mix3d the fix was merged in and I pushed a patch release (2.2.1) so you should be able to grab the latest from npm and it should work!

**Comment by chazzmoney** [comment]
@mix3d Let us know if this fixed the issue for you (it should), and we will mark this as closed.

**Comment by mix3d** [comment]
Sorry for the delay; builds on windows again 👍

**Comment by mix3d** [comment]
You guys are the most patient, thoughtful, and kind repo's I've ever had the pleasure of working with so far, btw.

**Comment by dbanksdesign** [comment]
A satisfied customer! Closing this issue. Don't hesitate to file new ones if you find problems.
