### ISSUE TITLE
Build names only the lowest level in object after transofm using build.js

### ISSUE THREAD

**Issue by johannesdz** [amzn/style-dictionary#989]
Hi!

as soon as i apply a transforms with registerTransform, my token names do not respect the specified format anymore.

Desired output:
`$core-color-neutral-grey: rgba(18, 18, 18, 0.74);
$core-color-neutral-blue: rgba(18, 18, 18, 0.93);`

Actual output:
$grey: rgba(18, 18, 18, 0.74);
$blue: rgba(18, 18, 18, 0.93);

Do you have any suggestion on this?

**Comment by Baribj** [comment]
paste the code, I am positive you are forgetting to add the `name/cti/kebab` transform

**Comment by johannesdz** [comment]
ok thanks!
i was assuming it will take default transformations and overwrite with additional custom format.
