### ISSUE TITLE
Platform in transformer is not optional anymore

### ISSUE THREAD

**Issue by lukasoppermann** [amzn/style-dictionary#991]
Hey @dbanksdesign,

in this commit: https://github.com/amzn/style-dictionary/commit/c43263bfd5223a7f24525f20aa87958aeedab812# you changed `Platform` to be required in `transformer`. Is this on purpose or was that an accident and it should stay optional?

**Comment by pascalduez** [comment]
Hey,

also in this commit, the `options` argument for a transformer is becoming required. Whereas it's not if I scan the code and all the docs, it's completely fine to solely use a `token` param.  

It now errors when trying to reuse a core transformer such as:
```js
const pxToRem = token =>
  StyleDictionary.transform['size/pxToRem'].transformer(token);
```
```
Transform.d.ts(23, 5): An argument for 'options' was not provided.
```

**Comment by jorenbroekema** [comment]
I think this is intended, many of our built-in transforms rely on those options being passed and in general our consumers that create transforms should be able to assume they are passed. If you call the transformer callback yourself imperatively, you should adhere to that signature
