### ISSUE TITLE
DTCG format support

### ISSUE THREAD

**Issue by PavelLaptev** [amzn/style-dictionary#992]
Hi! I think I saw it somewhere, but I can't find if Style Dictionary supports DTCG format where they add a dollar sign ($) to all reserved property keys like `$value`, `$type` etc.

**Comment by kachkaev** [comment]
I believe that this is happening in v4 via https://github.com/amzn/style-dictionary/pull/1100.

**Comment by jorenbroekema** [comment]
This landed, feel free to try the latest v4 prerelease, reach out to me by issue or slack if something doesn't work
