### ISSUE TITLE
Associate or transform key names

### ISSUE THREAD

**Issue by PavelLaptev** [amzn/style-dictionary#996]
In my design tokens file, I have keys like `$value` instead of just `value`.
Is there a way ho I can tell to Style Dictionary that `$value` is `value`?

**Comment by fALKENdk** [comment]
Have a look here: [w3c-token-json-parser.ts](https://github.com/lukasoppermann/style-dictionary-utils/blob/main/src/parser/w3c-token-json-parser.ts)

@lukasoppermann also wrote an article about that: [W3C Design Tokens with Style Dictionary](https://lukasoppermann.medium.com/w3c-design-tokens-with-style-dictionary-f7ff5f2ba98c)

**Comment by PavelLaptev** [comment]
Thank you @fALKENdk that's really helpful

**Comment by jorenbroekema** [comment]
W3C support added to v4 branch, so you can use it without needing a custom parser
