### ISSUE TITLE
Consider async formatters support

### ISSUE THREAD

**Issue by pascalduez** [amzn/style-dictionary#999]
Hi,

as far as I can see, custom formatters have to be synchronous.
This prevent the use of third parties that only ship asynchronous APIs in formatters.

I hit this while upgrading from [Prettier 2 to 3](https://prettier.io/blog/2023/07/05/3.0.0.html#api-1) used to process the result of a custom formatter.

```js
import { format } from 'prettier';

{
  name: 'something/something',
  formatter: async ({ dictionary, file, platform }) => {
    // Formatter logic here.
    // output = ...
    return await format(ouput, { ... });
 }
```

This is not currently possible.   
Would that be something to consider?

**Comment by ovidb** [comment]
Plus one on this one. Having to rewrite everything using callbacks that return the registration. For now I think the path of least resistance is to downgrade prettier for us.

**Comment by timsnadden** [comment]
One workaround is to use the `@prettier/sync` package. https://github.com/prettier/prettier-synchronized

**Comment by jorenbroekema** [comment]
landed in v4 :)
